from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, get_args

from pydantic import BaseModel

from experience.canvas import (
    CanvasContextPack,
    CanvasDiffSpec,
    CanvasRole,
    CanvasStage,
    MingliCanvasSpec,
    TemporalSandboxState,
)
from experience.contracts import (
    CompiledTopic,
    CueTemplate,
    MingliExperienceEnvelope,
    PerformanceCueInstance,
    TheaterEvent,
    TopicExploration,
    TopicPackage,
)
from experience.experiments import MechanismSandboxState
from experience.lab import (
    LabCandidateRevision,
    LabEvidenceSet,
    LabPathComparison,
    LabPromotionProposal,
    MingliLabSession,
    MingliLabStudy,
)
from experience.narration import NarrationManifest, NarrationSegment, SpeechAsset
from experience.product_projection import (
    CanvasChangeGroup,
    CanvasContextResponse,
    CanvasLayer,
    CanvasLayerProjection,
    CanvasStageProjection,
    ExperienceCaseSummary,
    ExperienceCasesResponse,
    NarrationManifestResponse,
    NarrationStatus,
    ReadOnlySixPillarCanvas,
    SpeechAssetResponse,
)
from experience.workspace import CaseWorkspaceEnvelope, CaseWorkspaceState


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_OUTPUT = ROOT / "docs" / "product" / "contracts" / "abu-living-theater-v1"
TYPESCRIPT_OUTPUT = ROOT / "apps" / "product" / "experience_shell" / "src" / "contracts.generated.ts"
CONTRACTS = {
    "mingli_experience_envelope_v1.schema.json": MingliExperienceEnvelope,
    "topic_package_v1.schema.json": TopicPackage,
    "compiled_topic_v1.schema.json": CompiledTopic,
    "cue_template_v1.schema.json": CueTemplate,
    "performance_cue_instance_v1.schema.json": PerformanceCueInstance,
    "theater_event_v1.schema.json": TheaterEvent,
    "mingli_canvas_spec_v1.schema.json": MingliCanvasSpec,
    "canvas_diff_spec_v1.schema.json": CanvasDiffSpec,
    "canvas_context_pack_v1.schema.json": CanvasContextPack,
    "narration_manifest_v1.schema.json": NarrationManifest,
    "speech_asset_v1.schema.json": SpeechAsset,
    "read_only_six_pillar_canvas_v1.schema.json": ReadOnlySixPillarCanvas,
    "case_workspace_state_v2.schema.json": CaseWorkspaceState,
    "case_workspace_envelope_v1.schema.json": CaseWorkspaceEnvelope,
    "mingli_lab_session_v1.schema.json": MingliLabSession,
    "mingli_lab_study_v1.schema.json": MingliLabStudy,
    "lab_candidate_revision_v1.schema.json": LabCandidateRevision,
    "lab_evidence_set_v1.schema.json": LabEvidenceSet,
    "lab_path_comparison_v1.schema.json": LabPathComparison,
    "lab_promotion_proposal_v1.schema.json": LabPromotionProposal,
    "temporal_sandbox_state_v2.schema.json": TemporalSandboxState,
    "mechanism_sandbox_state_v2.schema.json": MechanismSandboxState,
    "topic_exploration_v1.schema.json": TopicExploration,
}
TYPESCRIPT_ROOTS: tuple[type[BaseModel], ...] = (
    MingliExperienceEnvelope,
    ExperienceCaseSummary,
    ExperienceCasesResponse,
    NarrationSegment,
    NarrationManifest,
    NarrationStatus,
    NarrationManifestResponse,
    SpeechAsset,
    SpeechAssetResponse,
    MingliCanvasSpec,
    CanvasDiffSpec,
    CanvasContextPack,
    CanvasLayerProjection,
    CanvasChangeGroup,
    CanvasStageProjection,
    ReadOnlySixPillarCanvas,
    CanvasContextResponse,
    CaseWorkspaceState,
    CaseWorkspaceEnvelope,
    MingliLabSession,
    MingliLabStudy,
    LabCandidateRevision,
    LabEvidenceSet,
    LabPathComparison,
    LabPromotionProposal,
    TemporalSandboxState,
    MechanismSandboxState,
    TopicExploration,
)
TYPESCRIPT_ALIASES = {
    "CanvasRole": get_args(CanvasRole),
    "CanvasStage": get_args(CanvasStage),
    "CanvasLayer": get_args(CanvasLayer),
}


def main() -> None:
    SCHEMA_OUTPUT.mkdir(parents=True, exist_ok=True)
    for filename, contract in CONTRACTS.items():
        (SCHEMA_OUTPUT / filename).write_text(
            json.dumps(contract.model_json_schema(), ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    TYPESCRIPT_OUTPUT.write_text(render_typescript_contracts(), encoding="utf-8")
    print(
        f"schemas={len(CONTRACTS)} typescript={TYPESCRIPT_OUTPUT.relative_to(ROOT)}"
    )


def render_typescript_contracts() -> str:
    definitions: dict[str, dict[str, Any]] = {}
    for model in TYPESCRIPT_ROOTS:
        schema = model.model_json_schema()
        _merge_definition(definitions, schema["title"], {k: v for k, v in schema.items() if k != "$defs"})
        for name, definition in schema.get("$defs", {}).items():
            _merge_definition(definitions, name, definition)

    lines = [
        "// Generated by scripts/v50_export_experience_schemas.py. Do not edit.",
        "// Python Pydantic contracts are the authoritative source.",
        "",
    ]
    for name, values in TYPESCRIPT_ALIASES.items():
        rendered = " | ".join(json.dumps(value, ensure_ascii=False) for value in values)
        lines.append(f"export type {name} = {rendered};")
    lines.append("")
    for name in sorted(definitions):
        lines.extend(_render_definition(name, definitions[name]))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _merge_definition(
    definitions: dict[str, dict[str, Any]],
    name: str,
    definition: dict[str, Any],
) -> None:
    previous = definitions.get(name)
    if previous is not None and previous != definition:
        raise ValueError(f"typescript_schema_name_collision:{name}")
    definitions[name] = definition


def _render_definition(name: str, schema: dict[str, Any]) -> list[str]:
    if schema.get("type") != "object" and "properties" not in schema:
        return [f"export type {name} = {_render_type(schema)};"]
    # API response models serialize declared defaults, so output properties are present.
    lines = [f"export interface {name} {{"]
    for field, field_schema in schema.get("properties", {}).items():
        lines.append(f"  {_property_name(field)}: {_render_type(field_schema, indent=2)};")
    if isinstance(schema.get("additionalProperties"), dict):
        lines.append(f"  [key: string]: {_render_type(schema['additionalProperties'], indent=2)};")
    lines.append("}")
    return lines


def _render_type(schema: dict[str, Any], *, indent: int = 0) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    for union_key in ("anyOf", "oneOf"):
        if union_key in schema:
            return " | ".join(_render_type(item, indent=indent) for item in schema[union_key])
    if "allOf" in schema:
        return " & ".join(_render_type(item, indent=indent) for item in schema["allOf"])
    schema_type = schema.get("type")
    if schema_type == "array":
        item_type = _render_type(schema.get("items", {}), indent=indent)
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema:
        if isinstance(schema.get("additionalProperties"), dict) and not schema.get("properties"):
            return f"Record<string, {_render_type(schema['additionalProperties'], indent=indent)}>"
        properties = schema.get("properties", {})
        if not properties:
            return "Record<string, unknown>"
        pad = " " * indent
        child_pad = " " * (indent + 2)
        body = []
        for field, field_schema in properties.items():
            body.append(
                f"{child_pad}{_property_name(field)}: "
                f"{_render_type(field_schema, indent=indent + 2)};"
            )
        return "{\n" + "\n".join(body) + f"\n{pad}}}"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(schema_type, "unknown")


def _property_name(value: str) -> str:
    return value if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", value) else json.dumps(value)


if __name__ == "__main__":
    main()
