from __future__ import annotations

from pydantic import Field

from v30.contracts import FeatureEvidence, V30Model


KRP_LIBRARY_PACK_ID = "v30.krp.pack.core_runtime"
KRP_LIBRARY_PACK_VERSION = "2026-05-21"


class KnowledgeRulePortraitUnit(V30Model):
    unit_id: str
    pack_id: str = KRP_LIBRARY_PACK_ID
    pack_version: str = KRP_LIBRARY_PACK_VERSION
    unit_type: str
    domain: str
    family: str = "core_runtime"
    title: str
    source_family_ids: list[str] = Field(default_factory=list)
    reference_asset_ids: list[str] = Field(default_factory=list)
    required_context: list[str] = Field(default_factory=list)
    counter_context: list[str] = Field(default_factory=list)
    condition_supports: list[str] = Field(default_factory=list)
    condition_weakens: list[str] = Field(default_factory=list)
    mechanism_hooks: list[str] = Field(default_factory=list)
    question_hooks: list[str] = Field(default_factory=list)
    portrait_dimensions: list[str] = Field(default_factory=list)
    portrait_tags: list[str] = Field(default_factory=list)
    answer_guidance: list[str] = Field(default_factory=list)
    training_tags: list[str] = Field(default_factory=list)
    locale_terms: dict[str, str] = Field(default_factory=dict)
    boundary: str


DEFAULT_SOURCE_FAMILY_BY_DOMAIN = {
    "chart": ["v30.source.san_ming_tong_hui_system_catalog"],
    "element": ["v30.source.san_ming_tong_hui_system_catalog"],
    "ten_god": ["v30.source.yuan_hai_zi_ping_pattern_catalog"],
    "branch_relation": ["v30.source.san_ming_tong_hui_system_catalog", "v30.source.yuan_hai_zi_ping_pattern_catalog"],
    "time_context": ["v30.source.san_ming_tong_hui_system_catalog"],
    "structure_pattern": ["v30.source.zi_ping_pattern_month_command"],
    "useful_god": ["v30.source.zi_ping_pattern_month_command"],
    "structure_dynamic": ["v30.source.di_tian_sui_flow_mechanism"],
    "wealth": ["v30.source.yuan_hai_zi_ping_pattern_catalog"],
    "career": ["v30.source.yuan_hai_zi_ping_pattern_catalog"],
    "relationship": ["v30.source.yuan_hai_zi_ping_pattern_catalog"],
    "health": ["v30.source.san_ming_tong_hui_system_catalog"],
    "hidden_factor": ["v30.source.yuan_hai_zi_ping_pattern_catalog"],
    "rule_counterevidence": ["v30.source.shen_feng_tong_kao_disease_medicine"],
}


KRP_LIBRARY_UNITS = (
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.chart.context_bound",
        unit_type="knowledge",
        domain="chart",
        required_context=["day_master", "natal_pillars"],
        title="Chart facts are bound context and cannot be rewritten by downstream models.",
        condition_supports=["chart_context_bound"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["context_integrity"],
        portrait_tags=["chart_context_bound"],
        answer_guidance=["Treat day-master and pillar facts as immutable runtime context."],
        training_tags=["fact_boundary", "llm_no_mutation"],
        locale_terms={"zh": "原局事实边界", "en": "chart fact boundary", "ko": "원국 사실 경계"},
        boundary="knowledge_unit_chart_fact_not_interpretation",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.element.day_master_context",
        unit_type="knowledge",
        domain="element",
        required_context=["day_master_element"],
        title="Day-master element is deterministic context before any strength interpretation.",
        condition_supports=["element_context_bound"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["element_context"],
        portrait_tags=["day_master_element_context"],
        answer_guidance=["Separate deterministic element context from later balance review."],
        training_tags=["element_context", "fact_boundary"],
        locale_terms={"zh": "日主五行上下文", "en": "day-master element context", "ko": "일간 오행 맥락"},
        boundary="knowledge_unit_day_master_element_not_strength_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.ten_god.visibility_context",
        unit_type="knowledge",
        domain="ten_god",
        required_context=["visible_stems"],
        title="Visible ten-god markers describe context, not personality verdicts.",
        condition_supports=["ten_god_visibility"],
        mechanism_hooks=["mechanism.ten_god_visibility_context"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["ten_god_visibility"],
        portrait_tags=["ten_god_context_marker"],
        answer_guidance=["Explain visible ten-god context only through bound evidence."],
        training_tags=["ten_god_context", "no_personality_verdict"],
        locale_terms={"zh": "十神显性上下文", "en": "visible ten-god context", "ko": "드러난 십성 맥락"},
        boundary="knowledge_unit_no_personality_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.ten_god.output_expression_review",
        unit_type="portrait",
        domain="ten_god",
        family="ten_god_family",
        title="Output ten-god markers are expression/release context, not personality claims.",
        condition_supports=["ten_god_family:output", "hidden_ten_god_family:output"],
        mechanism_hooks=["dynamic_graph.v2"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["expression_pattern"],
        portrait_tags=["output_expression_context"],
        answer_guidance=["Explain output markers as bounded expression or release channels."],
        training_tags=["ten_god_family", "output"],
        boundary="portrait_unit_output_family_not_personality_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.ten_god.wealth_resource_review",
        unit_type="portrait",
        domain="ten_god",
        family="ten_god_family",
        title="Wealth ten-god markers require structure and timing context before outcome language.",
        condition_supports=["ten_god_family:wealth", "hidden_ten_god_family:wealth"],
        mechanism_hooks=["dynamic_graph.v2"],
        question_hooks=["review_useful_god_candidate_paths"],
        portrait_dimensions=["wealth_pattern"],
        portrait_tags=["wealth_marker_context"],
        answer_guidance=["Keep wealth markers as pressure/resource allocation context until structure review resolves them."],
        training_tags=["ten_god_family", "wealth"],
        boundary="portrait_unit_wealth_family_not_financial_prediction",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.ten_god.authority_pressure_review",
        unit_type="rule",
        domain="ten_god",
        family="ten_god_family",
        title="Authority ten-god markers can pressure the day-master path and require dynamic review.",
        condition_supports=["ten_god_family:authority", "hidden_ten_god_family:authority"],
        mechanism_hooks=["dynamic_graph.v2", "mechanism.branch_relation_dynamic_review"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["authority_pressure"],
        portrait_tags=["authority_pressure_context"],
        answer_guidance=["Use authority markers as pressure-path evidence, not fixed career or relationship verdicts."],
        training_tags=["ten_god_family", "authority", "dynamic_review"],
        boundary="rule_unit_authority_family_requires_dynamic_review",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.ten_god.resource_support_review",
        unit_type="knowledge",
        domain="ten_god",
        family="ten_god_family",
        title="Resource ten-god markers can support the day-master path without becoming a useful-god verdict.",
        condition_supports=["ten_god_family:resource", "hidden_ten_god_family:resource"],
        mechanism_hooks=["dynamic_graph.v2"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["resource_support"],
        portrait_tags=["resource_support_context"],
        answer_guidance=["Separate resource support context from fixed favorable/unfavorable labels."],
        training_tags=["ten_god_family", "resource"],
        boundary="knowledge_unit_resource_family_not_useful_god_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.ten_god.self_competition_review",
        unit_type="knowledge",
        domain="ten_god",
        family="ten_god_family",
        title="Self/peer ten-god markers create competition context and need balancing against other paths.",
        condition_supports=["ten_god_family:self", "hidden_ten_god_family:self"],
        mechanism_hooks=["dynamic_graph.v2"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["self_peer_competition"],
        portrait_tags=["self_peer_context"],
        answer_guidance=["Treat peer markers as structure competition context, not a standalone temperament claim."],
        training_tags=["ten_god_family", "self_peer"],
        boundary="knowledge_unit_self_family_not_temperament_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.ten_god.hidden_stem_context",
        unit_type="portrait",
        domain="ten_god",
        required_context=["hidden_stems"],
        counter_context=["user_denied_hidden_factor"],
        title="Hidden-stem ten-god markers are dialogue hypotheses before calibration.",
        condition_supports=["hidden_stem_context"],
        mechanism_hooks=["mechanism.hidden_factor_dialogue_probe"],
        question_hooks=["discover_hidden_factor_amplifier"],
        portrait_dimensions=["latent_pattern"],
        portrait_tags=["hidden_stem_hypothesis"],
        answer_guidance=["Present hidden-stem markers as hypotheses that need boundary-event feedback."],
        training_tags=["hidden_factor", "dialogue_required"],
        boundary="portrait_unit_hidden_stem_requires_dialogue",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.useful_god.candidate_gate",
        unit_type="rule",
        domain="useful_god",
        required_context=["useful_god_candidate_evidence"],
        counter_context=["useful_god_path_resolved"],
        title="Useful-god remains a candidate path until review evidence resolves it.",
        condition_supports=["rule_useful_god_candidate_gate"],
        mechanism_hooks=["mechanism.useful_god_candidate_gate"],
        question_hooks=["review_useful_god_candidate_paths"],
        portrait_dimensions=["candidate_path"],
        portrait_tags=["candidate_path_review"],
        answer_guidance=["Avoid fixed favorable/unfavorable wording before evidence path resolution."],
        training_tags=["useful_god_boundary", "candidate_gate"],
        boundary="rule_unit_candidate_only",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.useful_god.resolved_counter",
        unit_type="rule",
        domain="useful_god",
        title="Resolved useful-god feedback counters the candidate gate without removing traceability.",
        condition_supports=["useful_god_path_resolved", "rule_decision_state:countered"],
        question_hooks=["review_useful_god_candidate_paths"],
        portrait_tags=["useful_god_feedback_counter"],
        answer_guidance=["Use resolved-path feedback as bounded evidence, not untracked favorable/unfavorable wording."],
        boundary="rule_unit_useful_god_resolution_preserves_trace",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.time_context.missing_boundary",
        unit_type="rule",
        domain="time_context",
        required_context=["time_layer_missing"],
        counter_context=["explicit_luck_or_flow_layer"],
        title="Missing explicit time context blocks timing and special-year claims.",
        condition_supports=["rule_time_boundary"],
        condition_weakens=["timing_claim", "special_year_claim"],
        question_hooks=["confirm_missing_time_context"],
        portrait_dimensions=["time_context"],
        portrait_tags=["time_context_missing"],
        answer_guidance=["Ask for luck or flow context before discussing timing or event years."],
        training_tags=["time_boundary", "anti_timing_drift"],
        boundary="rule_unit_no_timing_without_time_layer",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.time_context.activation_review",
        unit_type="knowledge",
        domain="time_context",
        title="Explicit luck or flow layers activate review, not fixed event prediction.",
        condition_supports=["time_activation_review"],
        question_hooks=["review_current_chart_mainline"],
        portrait_tags=["time_layer_available"],
        answer_guidance=["Use explicit time layers as review context, not deterministic event proof."],
        boundary="knowledge_unit_time_layer_not_fixed_event",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.element.balance_review",
        unit_type="knowledge",
        domain="element",
        title="Element distribution is a review signal, not a standalone strength verdict.",
        condition_supports=["element_balance_review"],
        question_hooks=["review_current_chart_mainline"],
        portrait_tags=["element_distribution_context"],
        answer_guidance=["Explain element distribution with confidence and boundary wording."],
        boundary="knowledge_unit_element_distribution_not_strength_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.strength.seasonal_review",
        unit_type="knowledge",
        domain="structure_pattern",
        family="strength_review",
        title="Seasonal support or pressure is a strength-review input, not a final旺衰 verdict.",
        condition_supports=[
            "strength_review_candidate",
            "seasonal_support:day_master",
            "seasonal_pressure:day_master",
            "seasonal_indirect_context:day_master",
        ],
        condition_weakens=["fixed_strength_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["strength_review"],
        portrait_tags=["seasonal_strength_review"],
        answer_guidance=["Describe seasonal support/pressure as a review factor and keep final strength unresolved until paths are checked."],
        training_tags=["strength_review", "seasonal_context"],
        boundary="knowledge_unit_seasonal_strength_review_not_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.structure.pattern_candidate_review",
        unit_type="rule",
        domain="structure_pattern",
        family="pattern_candidate",
        title="Structure pattern signals are candidates until path, rule, and time context resolve them.",
        condition_supports=["structure_pattern_candidate"],
        condition_weakens=["fixed_geju_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["pattern_candidate"],
        portrait_tags=["geju_candidate_review"],
        answer_guidance=["Use 格局 language only as candidate review language until supporting paths are validated."],
        training_tags=["pattern_candidate", "geju_boundary"],
        boundary="rule_unit_pattern_candidate_not_fixed_geju",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.useful_god.family_candidate_review",
        unit_type="rule",
        domain="useful_god",
        family="useful_god_candidate_family",
        title="Useful-god families are review candidates generated from strength and path evidence.",
        condition_supports=[
            "useful_god_candidate_family:resource",
            "useful_god_candidate_family:self",
            "useful_god_candidate_family:output",
            "useful_god_candidate_family:wealth",
            "useful_god_candidate_family:authority",
            "useful_god_candidate_family:balance_review",
        ],
        condition_weakens=["fixed_useful_god_verdict"],
        mechanism_hooks=["mechanism.useful_god_candidate_gate", "dynamic_graph.path_resolution"],
        question_hooks=["review_useful_god_candidate_paths"],
        portrait_dimensions=["useful_god_candidate_family"],
        portrait_tags=["useful_god_family_candidate"],
        answer_guidance=["Treat candidate useful-god families as ranked review inputs, not final favorable/unfavorable output."],
        training_tags=["useful_god_boundary", "candidate_family"],
        boundary="rule_unit_useful_god_family_candidate_only",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.wealth.domain_path_review",
        unit_type="rule",
        domain="wealth",
        family="domain_rule",
        title="Wealth paths are review candidates and cannot become fixed financial outcomes.",
        condition_supports=["domain_rule_family:wealth_pressure", "domain_rule_family:wealth_competition"],
        condition_weakens=["fixed_wealth_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["wealth_path_review"],
        portrait_tags=["wealth_rule_candidate"],
        answer_guidance=["Use wealth language only as path pressure/allocation review, not income or outcome prediction."],
        training_tags=["domain_rule", "wealth", "anti_outcome_verdict"],
        boundary="rule_unit_wealth_domain_path_not_financial_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.wealth.competition_path_review",
        unit_type="rule",
        domain="wealth",
        family="domain_rule",
        title="Wealth competition paths require allocation review before any wealth language.",
        condition_supports=["domain_rule_family:wealth_competition"],
        condition_weakens=["fixed_wealth_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.competition_suppression"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["wealth_competition_path"],
        portrait_tags=["wealth_competition_candidate"],
        answer_guidance=["Describe wealth competition as resource/allocation pressure, not income gain or loss."],
        training_tags=["domain_rule", "wealth", "competition_path"],
        boundary="rule_unit_wealth_competition_path_not_financial_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.wealth.output_generation_path_review",
        unit_type="rule",
        domain="wealth",
        family="domain_rule",
        title="Output-to-wealth paths are generation candidates, not monetization outcomes.",
        condition_supports=["domain_rule_family:wealth_output_generation_path"],
        condition_weakens=["fixed_wealth_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["wealth_output_generation_path"],
        portrait_tags=["wealth_output_generation_candidate"],
        answer_guidance=["Frame output-to-wealth as an expression/resource path that needs context confirmation."],
        training_tags=["domain_rule", "wealth", "output_generation"],
        boundary="rule_unit_wealth_output_generation_path_not_income_prediction",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.wealth.authority_bridge_path_review",
        unit_type="rule",
        domain="wealth",
        family="domain_rule",
        title="Wealth-authority bridge paths need role-pressure review before outcome claims.",
        condition_supports=["domain_rule_family:wealth_authority_bridge_path"],
        condition_weakens=["fixed_wealth_outcome_claim", "fixed_career_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.conflict_family"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["wealth_authority_bridge_path"],
        portrait_tags=["wealth_authority_bridge_candidate"],
        answer_guidance=["Keep wealth-authority language at responsibility and pressure-review level."],
        training_tags=["domain_rule", "wealth", "authority_bridge"],
        boundary="rule_unit_wealth_authority_bridge_not_outcome_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.career.authority_path_review",
        unit_type="rule",
        domain="career",
        family="domain_rule",
        title="Career authority paths are pressure/resolution candidates, not fixed career outcomes.",
        condition_supports=["domain_rule_family:career_authority_path", "domain_rule_family:career_resource_resolution"],
        condition_weakens=["fixed_career_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["career_authority_path"],
        portrait_tags=["career_rule_candidate"],
        answer_guidance=["Frame authority paths as career pressure or responsibility review, not job-status prediction."],
        training_tags=["domain_rule", "career", "authority_path"],
        boundary="rule_unit_career_domain_path_not_outcome_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.career.authority_pressure_path_review",
        unit_type="rule",
        domain="career",
        family="domain_rule",
        title="Career authority pressure is a responsibility-review path, not a job outcome.",
        condition_supports=["domain_rule_family:career_authority_pressure_path"],
        condition_weakens=["fixed_career_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.conflict_family"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["career_authority_pressure_path"],
        portrait_tags=["career_authority_pressure_candidate"],
        answer_guidance=["Describe authority pressure as constraint/responsibility context without predicting status."],
        training_tags=["domain_rule", "career", "authority_pressure"],
        boundary="rule_unit_career_authority_pressure_not_job_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.career.resource_resolution_path_review",
        unit_type="rule",
        domain="career",
        family="domain_rule",
        title="Resource resolution can soften authority pressure but remains a candidate path.",
        condition_supports=["domain_rule_family:career_resource_resolution_path"],
        condition_weakens=["fixed_career_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["career_resource_resolution_path"],
        portrait_tags=["career_resource_resolution_candidate"],
        answer_guidance=["Use resource-resolution language as a support-path review, not promotion or role prediction."],
        training_tags=["domain_rule", "career", "resource_resolution"],
        boundary="rule_unit_career_resource_resolution_not_outcome_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.relationship.relation_path_review",
        unit_type="rule",
        domain="relationship",
        family="domain_rule",
        title="Relationship path review requires branch relation and ten-god context before any relationship language.",
        condition_supports=["domain_rule_family:relationship_relation_path"],
        condition_weakens=["fixed_relationship_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["relationship_relation_path"],
        portrait_tags=["relationship_rule_candidate"],
        answer_guidance=["Use relationship path language as interaction-structure review, not relationship event prediction."],
        training_tags=["domain_rule", "relationship", "branch_relation"],
        boundary="rule_unit_relationship_domain_path_not_event_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.relationship.conflict_path_review",
        unit_type="rule",
        domain="relationship",
        family="domain_rule",
        title="Relationship conflict paths are interaction-friction candidates, not event predictions.",
        condition_supports=["domain_rule_family:relationship_conflict_path"],
        condition_weakens=["fixed_relationship_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.conflict_family"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["relationship_conflict_path"],
        portrait_tags=["relationship_conflict_candidate"],
        answer_guidance=["Keep conflict language at interaction-pattern review and ask for context before emphasis."],
        training_tags=["domain_rule", "relationship", "conflict_path"],
        boundary="rule_unit_relationship_conflict_path_not_event_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.relationship.alignment_path_review",
        unit_type="rule",
        domain="relationship",
        family="domain_rule",
        title="Relationship alignment paths are continuity candidates, not relationship outcome claims.",
        condition_supports=["domain_rule_family:relationship_alignment_review_path"],
        condition_weakens=["fixed_relationship_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["relationship_alignment_path"],
        portrait_tags=["relationship_alignment_candidate"],
        answer_guidance=["Use alignment language only as branch-continuity review with clear uncertainty."],
        training_tags=["domain_rule", "relationship", "alignment_path"],
        boundary="rule_unit_relationship_alignment_path_not_event_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.relationship.marker_path_review",
        unit_type="rule",
        domain="relationship",
        family="domain_rule",
        title="Relationship markers require authority/wealth context review before use.",
        condition_supports=["domain_rule_family:relationship_authority_or_wealth_marker_path"],
        condition_weakens=["fixed_relationship_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["relationship_marker_path"],
        portrait_tags=["relationship_marker_candidate"],
        answer_guidance=["Treat authority/wealth markers as context prompts, not relationship verdicts."],
        training_tags=["domain_rule", "relationship", "marker_path"],
        boundary="rule_unit_relationship_marker_path_not_relationship_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.health.element_imbalance_review",
        unit_type="rule",
        domain="health",
        family="domain_rule",
        title="Health-related element imbalance is a cautionary review signal, not a disease claim.",
        condition_supports=["domain_rule_family:health_element_imbalance_review"],
        condition_weakens=["fixed_health_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["health_element_review"],
        portrait_tags=["health_rule_candidate"],
        answer_guidance=["Keep health language at element-balance review level and avoid illness claims."],
        training_tags=["domain_rule", "health", "safety_boundary"],
        boundary="rule_unit_health_domain_path_not_medical_claim",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.health.excess_review",
        unit_type="rule",
        domain="health",
        family="domain_rule",
        title="Element excess is only a balance-review signal and never a medical claim.",
        condition_supports=["domain_rule_family:health_element_excess_review"],
        condition_weakens=["fixed_health_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["health_element_excess_review"],
        portrait_tags=["health_excess_review_candidate"],
        answer_guidance=["Keep excess language as element-balance caution and avoid symptom or disease claims."],
        training_tags=["domain_rule", "health", "element_excess"],
        boundary="rule_unit_health_excess_review_not_medical_claim",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.health.thin_review",
        unit_type="rule",
        domain="health",
        family="domain_rule",
        title="Element thinness is only a balance-review signal and never a medical claim.",
        condition_supports=["domain_rule_family:health_element_thin_review"],
        condition_weakens=["fixed_health_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["health_element_thin_review"],
        portrait_tags=["health_thin_review_candidate"],
        answer_guidance=["Keep thin-element language as bounded balance review without medical inference."],
        training_tags=["domain_rule", "health", "element_thin"],
        boundary="rule_unit_health_thin_review_not_medical_claim",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.health.conflict_pressure_review",
        unit_type="rule",
        domain="health",
        family="domain_rule",
        title="Conflict pressure can inform cautionary review but cannot imply illness.",
        condition_supports=["domain_rule_family:health_conflict_pressure_review"],
        condition_weakens=["fixed_health_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.conflict_family"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["health_conflict_pressure_review"],
        portrait_tags=["health_conflict_pressure_candidate"],
        answer_guidance=["Frame conflict pressure as general caution and redirect medical questions to professionals."],
        training_tags=["domain_rule", "health", "conflict_pressure"],
        boundary="rule_unit_health_conflict_pressure_not_medical_claim",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.useful_god.domain_path_candidate_review",
        unit_type="rule",
        domain="useful_god",
        family="domain_rule",
        title="Domain paths can rank useful-god candidates but cannot finalize useful-god.",
        condition_supports=["domain_rule_family:useful_god_candidate_path"],
        condition_weakens=["fixed_useful_god_verdict"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.path_resolution"],
        question_hooks=["review_useful_god_candidate_paths"],
        portrait_dimensions=["useful_god_domain_path"],
        portrait_tags=["useful_god_domain_candidate"],
        answer_guidance=["Use domain paths only to prioritize useful-god review questions and evidence checks."],
        training_tags=["domain_rule", "useful_god_boundary"],
        boundary="rule_unit_domain_path_prioritizes_useful_god_review_only",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.structure.tongguan_resource_mediator_review",
        unit_type="rule",
        domain="structure_dynamic",
        family="tongguan",
        title="Resource mediation can be reviewed as 通关 path evidence, not as a final resolution verdict.",
        condition_supports=["domain_rule_family:tongguan_resource_mediator_path"],
        condition_weakens=["fixed_tongguan_resolution_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution", "dynamic_graph.tongguan_zhihua"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["tongguan_resource_mediator"],
        portrait_tags=["tongguan_resource_candidate"],
        answer_guidance=["Frame resource mediation as a path-resolution candidate and keep final resolution evidence-bound."],
        training_tags=["structure_dynamic", "tongguan", "path_resolution"],
        boundary="rule_unit_tongguan_resource_mediator_not_final_resolution",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.structure.tongguan_output_wealth_bridge_review",
        unit_type="rule",
        domain="structure_dynamic",
        family="tongguan",
        title="Output-to-wealth continuity can bridge a path but cannot imply wealth outcome.",
        condition_supports=["domain_rule_family:tongguan_output_wealth_bridge_path"],
        condition_weakens=["fixed_wealth_outcome_claim", "fixed_tongguan_resolution_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution", "dynamic_graph.tongguan_zhihua"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["tongguan_output_wealth_bridge"],
        portrait_tags=["tongguan_output_wealth_candidate"],
        answer_guidance=["Use output-to-wealth bridge language only to explain dynamic continuity, not monetization."],
        training_tags=["structure_dynamic", "tongguan", "wealth_boundary"],
        boundary="rule_unit_tongguan_output_wealth_bridge_not_outcome",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.structure.zhihua_output_authority_review",
        unit_type="rule",
        domain="structure_dynamic",
        family="zhihua",
        title="Output controlling authority is 制化 review evidence, not a settled structure claim.",
        condition_supports=["domain_rule_family:zhihua_output_controls_authority_path"],
        condition_weakens=["fixed_zhihua_resolution_verdict", "fixed_career_outcome_claim"],
        mechanism_hooks=["dynamic_graph.path_resolution", "dynamic_graph.tongguan_zhihua"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["zhihua_output_authority"],
        portrait_tags=["zhihua_output_authority_candidate"],
        answer_guidance=["Describe 制化 as candidate path transformation and require supporting path evidence."],
        training_tags=["structure_dynamic", "zhihua", "authority_boundary"],
        boundary="rule_unit_zhihua_output_authority_not_final_resolution",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.structure.zhihua_wealth_authority_resource_review",
        unit_type="rule",
        domain="structure_dynamic",
        family="zhihua",
        title="Wealth-authority-resource chains are 制化 candidates that still require bounded review.",
        condition_supports=["domain_rule_family:zhihua_wealth_authority_resource_path"],
        condition_weakens=["fixed_zhihua_resolution_verdict", "fixed_useful_god_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution", "dynamic_graph.tongguan_zhihua"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["zhihua_wealth_authority_resource"],
        portrait_tags=["zhihua_wealth_authority_resource_candidate"],
        answer_guidance=["Treat wealth-authority-resource chains as reviewable transformation candidates, not favorable-useful-god proof."],
        training_tags=["structure_dynamic", "zhihua", "useful_god_boundary"],
        boundary="rule_unit_zhihua_wealth_authority_resource_not_final_resolution",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.chart.bound_context_no_rewrite",
        unit_type="rule",
        domain="chart",
        family="foundation_boundary",
        title="Bound chart context is read-only evidence for every later judgment path.",
        condition_supports=["rule_chart_fact_boundary", "chart_context_bound"],
        condition_weakens=["chart_fact_mutation", "llm_chart_fact_generation", "training_chart_fact_generation"],
        mechanism_hooks=["dynamic_graph.foundation_boundary"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["calculation_foundation"],
        portrait_tags=["chart_read_only_boundary"],
        answer_guidance=["Keep pillars, day master, and deterministic chart facts as basis text, never generated claims."],
        training_tags=["m3_g2", "chart_boundary", "no_fact_mutation"],
        boundary="rule_unit_chart_context_read_only_not_interpretation",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.chart.output_fact_basis_required",
        unit_type="rule",
        domain="chart",
        family="foundation_boundary",
        title="Reading output must show its deterministic chart basis before interpretation.",
        condition_supports=["rule_chart_basis_required", "structure_pattern_candidate", "useful_god_candidate_question"],
        condition_weakens=["unsupported_reading_output", "fixed_bazi_verdict"],
        mechanism_hooks=["dynamic_graph.foundation_boundary"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["calculation_basis_trace"],
        portrait_tags=["reading_requires_chart_basis"],
        answer_guidance=["Attach interpretation language to explicit chart facts and evidence paths."],
        training_tags=["m3_g2", "chart_basis", "output_boundary"],
        boundary="rule_unit_reading_output_requires_chart_basis",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.element.balance_not_strength_verdict",
        unit_type="rule",
        domain="element",
        family="element_review",
        title="Element balance is a review input and cannot settle strength by itself.",
        condition_supports=["rule_element_balance_review_boundary", "element_balance_review"],
        condition_weakens=["fixed_strength_verdict", "single_factor_reading"],
        mechanism_hooks=["dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["element_balance_review"],
        portrait_tags=["element_balance_not_verdict"],
        answer_guidance=["Use element balance as one evidence layer and keep strength candidate-bound."],
        training_tags=["m3_g2", "element_balance", "strength_boundary"],
        boundary="rule_unit_element_balance_not_strength_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.element.seasonal_counterforce_review",
        unit_type="rule",
        domain="element",
        family="seasonal_state",
        title="Seasonal element state needs counterforce and path review before structure language.",
        condition_supports=["rule_seasonal_state_counterforce_review", "seasonal_state:xiang", "season_element:water"],
        condition_weakens=["fixed_strength_verdict", "fixed_geju_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["seasonal_counterforce_review"],
        portrait_tags=["seasonal_state_counterforce"],
        answer_guidance=["Pair seasonal state with counterforce and dynamic-path evidence before conclusion language."],
        training_tags=["m3_g2", "seasonal_state", "counterforce_review"],
        boundary="rule_unit_seasonal_state_requires_counterforce",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.foundation.m1_m2_m3_chain",
        unit_type="knowledge",
        domain="foundation",
        family="core_chain",
        title="M1/M2 deterministic facts must precede M3 evidence and judgment paths.",
        source_family_ids=["v30.source.san_ming_tong_hui_system_catalog"],
        condition_supports=["rule_foundation_m1_m2_m3_chain", "chart_context_bound", "element_context_bound"],
        condition_weakens=["chart_fact_mutation", "unsupported_reading_output"],
        mechanism_hooks=["dynamic_graph.foundation_boundary"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["core_calculation_chain"],
        portrait_tags=["m1_m2_m3_chain"],
        answer_guidance=["Explain calculation order as facts first, then evidence paths, then bounded reading."],
        training_tags=["m3_g2", "foundation", "core_chain"],
        boundary="knowledge_unit_foundation_chain_not_judgment_shortcut",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.foundation.module_handoff_trace",
        unit_type="knowledge",
        domain="foundation",
        family="core_chain",
        title="Module handoff must preserve fact/evidence boundaries across M3, M4, M5, and M6.",
        source_family_ids=["v30.source.di_tian_sui_flow_mechanism"],
        condition_supports=["rule_foundation_m1_m2_m3_chain", "rule_chart_basis_required"],
        condition_weakens=["unsupported_reading_output", "fixed_bazi_verdict"],
        mechanism_hooks=["dynamic_graph.foundation_boundary"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["module_handoff_trace"],
        portrait_tags=["module_boundary_trace"],
        answer_guidance=["Keep each module's contribution visible without collapsing evidence into verdicts."],
        training_tags=["m3_g2", "foundation", "module_handoff"],
        boundary="knowledge_unit_module_handoff_preserves_boundaries",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.foundation.training_read_only_boundary",
        unit_type="rule",
        domain="foundation",
        family="training_boundary",
        title="Training can tune M3 coverage and path priority but cannot create chart facts.",
        source_family_ids=["v30.source.synthetic_runtime_baseline"],
        condition_supports=["rule_foundation_m1_m2_m3_chain", "rule_chart_fact_boundary"],
        condition_weakens=["training_chart_fact_generation", "chart_fact_mutation"],
        mechanism_hooks=["dynamic_graph.foundation_boundary"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["training_boundary"],
        portrait_tags=["training_read_only_boundary"],
        answer_guidance=["Use training evidence only for coverage, weights, ranking, and question strategy."],
        training_tags=["m3_g2", "training_boundary", "no_fact_mutation"],
        boundary="rule_unit_training_tunes_coverage_not_chart_facts",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.romance.private_fact_boundary",
        unit_type="rule",
        domain="romance",
        family="domain_rule",
        title="Romance signals are relationship-path evidence, not private fact claims.",
        source_family_ids=["v30.source.yuan_hai_zi_ping_pattern_catalog"],
        condition_supports=["rule_romance_private_fact_boundary", "domain_rule_family:relationship_relation_path", "palace_position_review"],
        condition_weakens=["fixed_relationship_outcome_claim", "private_relationship_fact_claim"],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["romance_private_fact_boundary"],
        portrait_tags=["romance_not_private_fact"],
        answer_guidance=["Avoid private relationship facts; use romance language only as bounded topic-path review."],
        training_tags=["m3_g2", "romance", "privacy_boundary"],
        boundary="rule_unit_romance_path_not_private_fact",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.romance.marker_context_review",
        unit_type="portrait",
        domain="romance",
        family="domain_rule",
        title="Romance markers need ten-god, branch, palace, and timing context before emphasis.",
        source_family_ids=["v30.source.yuan_hai_zi_ping_pattern_catalog"],
        condition_supports=["domain_rule_family:relationship_authority_or_wealth_marker_path", "palace_position_review"],
        condition_weakens=["fixed_relationship_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.conflict_family"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["romance_marker_context"],
        portrait_tags=["romance_marker_review"],
        answer_guidance=["Treat romance markers as prompts for context, not events or relationship status."],
        training_tags=["m3_g2", "romance", "marker_context"],
        boundary="portrait_unit_romance_marker_context_not_event_claim",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.romance.conflict_alignment_review",
        unit_type="rule",
        domain="romance",
        family="domain_rule",
        title="Romance conflict or alignment paths require branch arbitration before interpretation.",
        source_family_ids=["v30.source.san_ming_tong_hui_system_catalog", "v30.source.yuan_hai_zi_ping_pattern_catalog"],
        condition_supports=["domain_rule_family:relationship_conflict_path", "domain_rule_family:relationship_alignment_review_path"],
        condition_weakens=["fixed_relationship_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.conflict_family"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["romance_conflict_alignment"],
        portrait_tags=["romance_conflict_alignment_review"],
        answer_guidance=["Use conflict/alignment as relational dynamics evidence only after branch arbitration."],
        training_tags=["m3_g2", "romance", "branch_arbitration"],
        boundary="rule_unit_romance_conflict_alignment_not_event_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.rule_counterevidence.original_trace_required",
        unit_type="rule",
        domain="rule_counterevidence",
        family="counterevidence_trace",
        title="Counter-evidence requires an explicit original rule trace.",
        source_family_ids=["v30.source.shen_feng_tong_kao_disease_medicine"],
        condition_supports=["rule_counterevidence_trace_required", "rule_decision_state:countered", "rule_chart_fact_boundary"],
        condition_weakens=["silent_rule_override", "untracked_policy_override"],
        mechanism_hooks=["dynamic_graph.counterevidence"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["counterevidence_trace"],
        portrait_tags=["original_rule_trace_required"],
        answer_guidance=["Show the original rule, the counter-evidence, and the resulting bounded state."],
        training_tags=["m3_g2", "counterevidence", "trace_required"],
        boundary="rule_unit_counterevidence_requires_original_trace",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.rule_counterevidence.policy_override_block",
        unit_type="rule",
        domain="rule_counterevidence",
        family="counterevidence_trace",
        title="Policy or training weights cannot silently override rule evidence.",
        source_family_ids=["v30.source.synthetic_runtime_baseline"],
        condition_supports=["rule_counterevidence_trace_required", "rule_chart_fact_boundary"],
        condition_weakens=["untracked_policy_override", "training_chart_fact_generation"],
        mechanism_hooks=["dynamic_graph.counterevidence"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["policy_override_boundary"],
        portrait_tags=["policy_override_requires_trace"],
        answer_guidance=["Use policy weights only as traceable priority hints, not hidden rule replacement."],
        training_tags=["m3_g2", "counterevidence", "policy_boundary"],
        boundary="rule_unit_policy_override_requires_trace",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.domain_rule.subfamily_gate",
        unit_type="rule",
        domain="domain_rule",
        family="domain_rule_gate",
        title="Domain readings require subfamily evidence before customer-facing emphasis.",
        source_family_ids=["v30.source.di_tian_sui_flow_mechanism"],
        condition_supports=["rule_domain_subfamily_evidence_required", "domain_rule_review_candidate"],
        condition_weakens=[
            "fixed_wealth_outcome_claim",
            "fixed_career_outcome_claim",
            "fixed_relationship_outcome_claim",
            "fixed_health_outcome_claim",
        ],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["domain_rule_subfamily_gate"],
        portrait_tags=["domain_subfamily_evidence_required"],
        answer_guidance=["Only emphasize a domain after its subfamily evidence path is visible."],
        training_tags=["m3_g2", "domain_rule", "subfamily_gate"],
        boundary="rule_unit_domain_subfamily_required_before_outcome_language",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.domain_rule.outcome_language_block",
        unit_type="rule",
        domain="domain_rule",
        family="domain_rule_gate",
        title="Domain paths block outcome language unless evidence and counter-evidence are cited.",
        source_family_ids=["v30.source.yuan_hai_zi_ping_pattern_catalog"],
        condition_supports=["rule_domain_outcome_boundary", "domain_rule_review_candidate"],
        condition_weakens=[
            "fixed_wealth_outcome_claim",
            "fixed_career_outcome_claim",
            "fixed_relationship_outcome_claim",
            "fixed_health_outcome_claim",
        ],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["domain_outcome_language_boundary"],
        portrait_tags=["domain_outcome_language_block"],
        answer_guidance=["领域语言只作为结构路径说明，不作为具体人生结果断语。"],
        training_tags=["m3_g2", "domain_rule", "outcome_language_block"],
        boundary="rule_unit_domain_outcome_language_block",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.domain_rule.cross_domain_bridge_review",
        unit_type="knowledge",
        domain="domain_rule",
        family="domain_rule_gate",
        title="Cross-domain bridges require separate evidence for each affected domain.",
        source_family_ids=["v30.source.di_tian_sui_flow_mechanism", "v30.source.yuan_hai_zi_ping_pattern_catalog"],
        condition_supports=[
            "domain_rule_family:wealth_authority_bridge_path",
            "domain_rule_family:zhihua_wealth_authority_resource_path",
        ],
        condition_weakens=["fixed_wealth_outcome_claim", "fixed_career_outcome_claim", "fixed_useful_god_verdict"],
        mechanism_hooks=["dynamic_graph.domain_path", "dynamic_graph.tongguan_zhihua"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["cross_domain_bridge_review"],
        portrait_tags=["cross_domain_bridge_requires_evidence"],
        answer_guidance=["Separate wealth, career, and useful-god implications instead of merging them into one verdict."],
        training_tags=["m3_g2", "domain_rule", "cross_domain_bridge"],
        boundary="knowledge_unit_cross_domain_bridge_not_combined_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.rule_counterevidence.silent_override_block",
        unit_type="rule",
        domain="rule_counterevidence",
        family="counterevidence_trace",
        title="Silent policy overrides are blocked unless rule evidence remains traceable.",
        source_family_ids=["v30.source.synthetic_runtime_baseline"],
        condition_supports=["rule_silent_policy_override_blocked", "rule_counterevidence_trace_required"],
        condition_weakens=["silent_rule_override", "untracked_policy_override", "training_chart_fact_generation"],
        mechanism_hooks=["dynamic_graph.counterevidence"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["silent_override_boundary"],
        portrait_tags=["silent_override_blocked"],
        answer_guidance=["Never hide rule-state changes behind policy or training language."],
        training_tags=["m3_g2", "counterevidence", "silent_override_block"],
        boundary="rule_unit_silent_policy_override_blocked",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.structure.pattern_success_failure_rescue_review",
        unit_type="rule",
        domain="structure_pattern",
        family="source_backed_pattern",
        title="Pattern review must inspect success, failure, rescue, and counterforce paths.",
        source_family_ids=["v30.source.zi_ping_pattern_month_command"],
        reference_asset_ids=["v30.m3.reference.v20_expanded_knowledge_units"],
        condition_supports=["rule_pattern_success_failure_rescue_review", "month_command_review", "structure_pattern_candidate"],
        condition_weakens=["fixed_geju_verdict", "fixed_strength_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["pattern_success_failure_rescue"],
        portrait_tags=["pattern_rescue_counterforce_review"],
        answer_guidance=["Name pattern candidates only after checking failure, rescue, and counterforce evidence."],
        training_tags=["m3_g2", "structure_pattern", "success_failure_rescue"],
        boundary="rule_unit_pattern_success_failure_rescue_not_fixed_geju",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.time_context.explicit_time_layer_required",
        unit_type="rule",
        domain="time_context",
        family="time_layer_boundary",
        title="Timing interpretation requires explicit luck, flow-year, or flow-month evidence.",
        source_family_ids=["v30.source.san_ming_tong_hui_system_catalog"],
        condition_supports=["rule_explicit_time_layer_required", "rule_time_boundary"],
        condition_weakens=["timing_claim", "special_year_claim", "flow_month_claim_without_context"],
        mechanism_hooks=["dynamic_graph.time_layer_boundary"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["time_layer_boundary"],
        portrait_tags=["explicit_time_layer_required"],
        answer_guidance=["Block timing language unless the required time layer is present and cited."],
        training_tags=["m3_g2", "time_context", "time_layer_boundary"],
        boundary="rule_unit_time_layer_required_for_timing_language",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.hidden_factor.feedback_calibration",
        unit_type="portrait",
        domain="hidden_factor",
        required_context=["hidden_factor_user_feedback"],
        title="Hidden factors require user feedback calibration before amplifier use.",
        condition_supports=["rule_hidden_factor_dialogue_boundary", "hidden_factor_user_calibrated"],
        question_hooks=["discover_hidden_factor_amplifier"],
        portrait_dimensions=["latent_amplifier"],
        portrait_tags=["hidden_factor_calibration"],
        answer_guidance=["Treat hidden factors as hypotheses unless feedback evidence counters the dialogue gate."],
        training_tags=["hidden_factor", "feedback_calibration"],
        boundary="portrait_unit_feedback_required",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.hidden_factor.dialogue_boundary",
        unit_type="rule",
        domain="hidden_factor",
        title="Hidden-factor conclusions are blocked until dialogue discovers boundary events.",
        condition_supports=["rule_hidden_factor_dialogue_boundary"],
        condition_weakens=["deterministic_hidden_factor_claim"],
        question_hooks=["discover_hidden_factor_amplifier"],
        portrait_tags=["hidden_factor_dialogue_required"],
        answer_guidance=["Ask for special years and repeated states before using hidden factors as amplifiers."],
        boundary="rule_unit_hidden_factor_dialogue_required",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.hidden_factor.user_calibrated_counter",
        unit_type="portrait",
        domain="hidden_factor",
        title="User-confirmed special events can counter the hidden-factor dialogue gate.",
        condition_supports=["hidden_factor_user_calibrated", "rule_decision_state:countered"],
        question_hooks=["discover_hidden_factor_amplifier"],
        portrait_tags=["hidden_factor_feedback_counter"],
        answer_guidance=["Use calibrated feedback as a hypothesis-strengthening signal, not a chart fact rewrite."],
        boundary="portrait_unit_feedback_counter_not_chart_fact",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.branch_relation.dynamic_review",
        unit_type="rule",
        domain="branch_relation",
        required_context=["branch_relation_evidence"],
        counter_context=["branch_single_factor_confirmed"],
        title="Branch relations require layered dynamic review before single-factor reading.",
        condition_supports=["rule_structure_dynamic_review", "structure_dynamic_review"],
        condition_weakens=["single_factor_reading"],
        mechanism_hooks=["mechanism.branch_relation_dynamic_review"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["structure_dynamic"],
        portrait_tags=["branch_relation_dynamic_review"],
        answer_guidance=["Explain branch relations through dynamic paths and counter-evidence gates."],
        training_tags=["branch_relation", "dynamic_review"],
        boundary="rule_unit_branch_relation_not_single_factor",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.branch_relation.conflict_family",
        unit_type="rule",
        domain="branch_relation",
        family="branch_conflict",
        title="Clash, harm, break, and punishment relations are conflict-family evidence for dynamic review.",
        condition_supports=[
            "branch_conflict_family:clash",
            "branch_conflict_family:harm",
            "branch_conflict_family:break",
            "branch_conflict_family:punishment",
        ],
        condition_weakens=["single_factor_reading"],
        mechanism_hooks=["dynamic_graph.conflict_family"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["branch_conflict"],
        portrait_tags=["branch_conflict_family"],
        answer_guidance=["Name branch conflict families only as reviewed dynamics, never as isolated event predictions."],
        training_tags=["branch_relation", "conflict_family", "anti_single_factor"],
        boundary="rule_unit_branch_conflict_family_requires_context",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.branch_relation.alignment_family",
        unit_type="knowledge",
        domain="branch_relation",
        family="branch_alignment",
        title="Harmony and meeting relations are alignment-family evidence, not automatic good outcomes.",
        condition_supports=[
            "branch_alignment_family:harmony",
            "branch_alignment_family:three_harmony",
            "branch_alignment_family:three_meeting",
        ],
        mechanism_hooks=["dynamic_graph.conflict_family"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["branch_alignment"],
        portrait_tags=["branch_alignment_family"],
        answer_guidance=["Use alignment relations as path-continuity context, not favorable outcome promises."],
        training_tags=["branch_relation", "alignment_family"],
        boundary="knowledge_unit_branch_alignment_not_outcome_prediction",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.structure.dynamic_path",
        unit_type="knowledge",
        domain="structure_dynamic",
        required_context=["dynamic_graph_path"],
        title="Dynamic graph paths connect ten-god families through generate/control relations.",
        condition_supports=["rule_structure_dynamic_review"],
        mechanism_hooks=["dynamic_graph.v2"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["structure_dynamic"],
        portrait_tags=["dynamic_path_context"],
        answer_guidance=["Use dynamic path scores as structure context, not single-factor verdicts."],
        training_tags=["structure_dynamic", "path_scoring"],
        boundary="knowledge_unit_dynamic_path_not_single_factor",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.structure.path_resolution_review",
        unit_type="knowledge",
        domain="structure_dynamic",
        family="path_resolution",
        title="Generate/control paths can indicate resolution candidates before final structure language.",
        condition_supports=["strength_review_candidate", "structure_pattern_candidate"],
        mechanism_hooks=["dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["path_resolution"],
        portrait_tags=["path_resolution_candidate"],
        answer_guidance=["Use path-resolution language to explain why a candidate path remains under review."],
        training_tags=["structure_dynamic", "path_resolution", "candidate_review"],
        boundary="knowledge_unit_path_resolution_not_final_structure",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.rule.counterevidence.trace",
        unit_type="rule",
        domain="rule_counterevidence",
        title="Counter-evidence changes rule state while preserving traceability.",
        condition_supports=["rule_decision_state:countered"],
        question_hooks=["review_current_chart_mainline"],
        portrait_tags=["counterevidence_trace"],
        answer_guidance=["Show which evidence countered a rule instead of deleting the original rule boundary."],
        boundary="rule_unit_counterevidence_preserves_trace",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.source.month_command.pattern_gate",
        unit_type="rule",
        domain="structure_pattern",
        family="source_backed_pattern",
        title="Month-command pattern review must precede fixed 格局 language.",
        source_family_ids=["v30.source.zi_ping_pattern_month_command"],
        reference_asset_ids=["v30.m3.reference.v20_expanded_knowledge_units"],
        condition_supports=["month_command_review", "structure_pattern_candidate"],
        condition_weakens=["fixed_geju_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["month_command_pattern_review"],
        portrait_tags=["month_command_pattern_gate"],
        answer_guidance=["Name 格局 only as a candidate until month-command support, counter-force, and path evidence are reviewed."],
        training_tags=["source_backed", "month_command", "pattern_boundary"],
        boundary="rule_unit_month_command_pattern_gate_not_fixed_geju",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.source.wang_xiang_strength_review",
        unit_type="knowledge",
        domain="element",
        family="source_backed_strength",
        title="旺相休囚死 is seasonal state evidence, not a standalone strength verdict.",
        source_family_ids=["v30.source.san_ming_tong_hui_system_catalog"],
        reference_asset_ids=["v30.m3.reference.v20_expanded_knowledge_units"],
        condition_supports=["wang_xiang_xiu_qiu_si_review"],
        condition_weakens=["fixed_strength_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["seasonal_element_state"],
        portrait_tags=["wang_xiang_state_review"],
        answer_guidance=["Use 旺相休囚死 as a seasonal element-state input and keep final strength candidate-bound."],
        training_tags=["source_backed", "seasonal_state", "strength_review"],
        boundary="knowledge_unit_wang_xiang_state_not_strength_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.source.tiaohou.climate_review",
        unit_type="rule",
        domain="useful_god",
        family="tiaohou",
        title="调候 is a climate-review path and must compete with扶抑, 通关, and病药 paths.",
        source_family_ids=["v30.source.qiong_tong_bao_jian_climate_review"],
        reference_asset_ids=["v30.m3.reference.v20_expanded_knowledge_units"],
        condition_supports=["climate_regulation_review", "tiaohou_candidate_path"],
        condition_weakens=["fixed_useful_god_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution"],
        question_hooks=["review_useful_god_candidate_paths"],
        portrait_dimensions=["tiaohou_path_review"],
        portrait_tags=["tiaohou_candidate_path"],
        answer_guidance=["Treat 调候 as a ranked useful-god candidate path, not the final useful-god by itself."],
        training_tags=["source_backed", "tiaohou", "useful_god_boundary"],
        boundary="rule_unit_tiaohou_climate_review_not_final_useful_god",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.source.bingyao.blockage_review",
        unit_type="rule",
        domain="useful_god",
        family="bingyao",
        title="病药 review identifies blockage and remedy candidates without overriding chart facts.",
        source_family_ids=["v30.source.shen_feng_tong_kao_disease_medicine"],
        reference_asset_ids=["v30.m3.reference.v20_expanded_knowledge_units"],
        condition_supports=["bingyao_blockage_review", "bingyao_remedy_candidate_path"],
        condition_weakens=["fixed_useful_god_verdict"],
        mechanism_hooks=["dynamic_graph.path_resolution", "dynamic_graph.tongguan_zhihua"],
        question_hooks=["review_useful_god_candidate_paths"],
        portrait_dimensions=["bingyao_path_review"],
        portrait_tags=["bingyao_remedy_candidate"],
        answer_guidance=["Use 病药 to explain supporting and weakening evidence for useful-god candidates."],
        training_tags=["source_backed", "bingyao", "counterevidence"],
        boundary="rule_unit_bingyao_review_not_fixed_useful_god",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.source.element.flow_transform",
        unit_type="knowledge",
        domain="structure_dynamic",
        family="flow_transform",
        title="五行流通、通关、制化 must be represented as dynamic paths.",
        source_family_ids=["v30.source.di_tian_sui_flow_mechanism"],
        reference_asset_ids=["v30.m3.reference.v20_expanded_knowledge_units", "v30.m3.reference.v20_structure_dynamics_graph_v2"],
        condition_supports=["element_flow_transform_review", "tongguan_candidate_path", "zhihua_candidate_path"],
        condition_weakens=["single_factor_reading"],
        mechanism_hooks=["dynamic_graph.path_resolution", "dynamic_graph.tongguan_zhihua"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["element_flow_transform"],
        portrait_tags=["element_flow_transform_review"],
        answer_guidance=["Represent flow, 通关, and 制化 as scored paths with blockage and counter-evidence."],
        training_tags=["source_backed", "flow_transform", "dynamic_path"],
        boundary="knowledge_unit_element_flow_transform_requires_dynamic_path",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.source.branch.arbitration",
        unit_type="rule",
        domain="branch_relation",
        family="branch_arbitration",
        title="冲合刑害破并见 must be arbitrated instead of collapsed into one relation name.",
        source_family_ids=["v30.source.san_ming_tong_hui_system_catalog", "v30.source.yuan_hai_zi_ping_pattern_catalog"],
        reference_asset_ids=["v30.m3.reference.v20_expanded_knowledge_units"],
        condition_supports=["branch_relation_arbitration_review"],
        condition_weakens=["single_factor_reading"],
        mechanism_hooks=["dynamic_graph.conflict_family"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["branch_relation_arbitration"],
        portrait_tags=["branch_arbitration_boundary"],
        answer_guidance=["Separate relation type, involved branches, transformation support, interference, and source layer."],
        training_tags=["source_backed", "branch_relation", "arbitration"],
        boundary="rule_unit_branch_arbitration_not_relation_name_verdict",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.source.ten_god.role_set",
        unit_type="knowledge",
        domain="ten_god",
        family="ten_god_role_set",
        title="Ten-god review must preserve the ten distinct roles and visible/hidden/position context.",
        source_family_ids=["v30.source.yuan_hai_zi_ping_pattern_catalog"],
        reference_asset_ids=["v30.m3.reference.v20_expanded_knowledge_units"],
        condition_supports=["ten_god_role_set_review", "ten_god_visibility", "hidden_stem_context"],
        condition_weakens=["single_factor_reading"],
        mechanism_hooks=["dynamic_graph.v2"],
        question_hooks=["review_current_chart_mainline", "review_useful_god_candidate_paths"],
        portrait_dimensions=["ten_god_role_set"],
        portrait_tags=["ten_god_full_role_set"],
        answer_guidance=["Do not collapse wealth, authority, resource, peer, and output into one generic meaning."],
        training_tags=["source_backed", "ten_god", "role_set"],
        boundary="knowledge_unit_ten_god_role_set_not_generic_personality_claim",
    ),
    KnowledgeRulePortraitUnit(
        unit_id="v30.krp.source.palace.position_boundary",
        unit_type="rule",
        domain="relationship",
        family="palace_position",
        title="Palace and pillar position locate topic layers but cannot imply private facts.",
        source_family_ids=["v30.source.yuan_hai_zi_ping_pattern_catalog"],
        reference_asset_ids=["v30.m3.reference.v20_expanded_knowledge_units"],
        condition_supports=["palace_position_review"],
        condition_weakens=["fixed_relationship_outcome_claim"],
        mechanism_hooks=["dynamic_graph.domain_path"],
        question_hooks=["review_current_chart_mainline"],
        portrait_dimensions=["palace_position_layer"],
        portrait_tags=["palace_position_boundary"],
        answer_guidance=["Use palace position as a topic locator that must be checked against ten-god, branch, capacity, and time evidence."],
        training_tags=["source_backed", "palace", "privacy_boundary"],
        boundary="rule_unit_palace_position_not_private_fact",
    ),
)


def match_krp_library_units(
    evidence: list[FeatureEvidence],
    policy_payload: dict[str, object] | None = None,
) -> list[dict[str, object]]:
    supports = {support for row in evidence for support in row.supports}
    weakens = {weaken for row in evidence for weaken in row.weakens}
    rows: list[dict[str, object]] = []
    for unit in KRP_LIBRARY_UNITS:
        matched_supports = sorted(set(unit.condition_supports) & supports)
        matched_weakens = sorted(set(unit.condition_weakens) & weakens)
        matched = [*matched_supports, *[f"weakens:{row}" for row in matched_weakens]]
        if not matched:
            continue
        score, score_reasons = _unit_score(unit, matched, policy_payload)
        rows.append(
            {
                "unit_id": unit.unit_id,
                "pack_id": unit.pack_id,
                "pack_version": unit.pack_version,
                "unit_type": unit.unit_type,
                "domain": unit.domain,
                "family": unit.family,
                "source_family_ids": _source_family_ids(unit),
                "reference_asset_ids": unit.reference_asset_ids,
                "title": unit.title,
                "required_context": unit.required_context,
                "counter_context": unit.counter_context,
                "matched_supports": matched,
                "matched_weakens": matched_weakens,
                "score": score,
                "score_reasons": score_reasons,
                "mechanism_hooks": unit.mechanism_hooks,
                "question_hooks": unit.question_hooks,
                "portrait_dimensions": unit.portrait_dimensions,
                "portrait_tags": unit.portrait_tags,
                "answer_guidance": unit.answer_guidance,
                "training_tags": unit.training_tags,
                "locale_terms": unit.locale_terms,
                "boundary": unit.boundary,
            }
        )
    return sorted(rows, key=lambda row: (-float(row["score"]), str(row["unit_id"])))


def summarize_krp_library_units(units: list[dict[str, object]]) -> dict[str, object]:
    by_type: dict[str, int] = {}
    by_domain: dict[str, int] = {}
    pack_ids: set[str] = set()
    pack_versions: set[str] = set()
    portrait_tags: set[str] = set()
    portrait_dimensions: set[str] = set()
    question_hooks: set[str] = set()
    mechanism_hooks: set[str] = set()
    training_tags: set[str] = set()
    source_family_ids: set[str] = set()
    reference_asset_ids: set[str] = set()
    boundary_count = 0
    for unit in units:
        unit_type = str(unit.get("unit_type", ""))
        domain = str(unit.get("domain", ""))
        if unit_type:
            by_type[unit_type] = by_type.get(unit_type, 0) + 1
        if domain:
            by_domain[domain] = by_domain.get(domain, 0) + 1
        if unit.get("boundary"):
            boundary_count += 1
        pack_ids.add(str(unit.get("pack_id", "")))
        pack_versions.add(str(unit.get("pack_version", "")))
        portrait_tags.update(_string_list(unit.get("portrait_tags", [])))
        portrait_dimensions.update(_string_list(unit.get("portrait_dimensions", [])))
        question_hooks.update(_string_list(unit.get("question_hooks", [])))
        mechanism_hooks.update(_string_list(unit.get("mechanism_hooks", [])))
        training_tags.update(_string_list(unit.get("training_tags", [])))
        source_family_ids.update(_string_list(unit.get("source_family_ids", [])))
        reference_asset_ids.update(_string_list(unit.get("reference_asset_ids", [])))
    return {
        "unit_count": len(units),
        "pack_ids": sorted(row for row in pack_ids if row),
        "pack_versions": sorted(row for row in pack_versions if row),
        "by_type": dict(sorted(by_type.items())),
        "by_domain": dict(sorted(by_domain.items())),
        "boundary_count": boundary_count,
        "portrait_tags": sorted(portrait_tags),
        "portrait_dimensions": sorted(portrait_dimensions),
        "question_hooks": sorted(question_hooks),
        "mechanism_hooks": sorted(mechanism_hooks),
        "training_tags": sorted(training_tags),
        "source_family_ids": sorted(source_family_ids),
        "source_family_count": len(source_family_ids),
        "reference_asset_ids": sorted(reference_asset_ids),
        "reference_asset_count": len(reference_asset_ids),
    }


def _source_family_ids(unit: KnowledgeRulePortraitUnit) -> list[str]:
    if unit.source_family_ids:
        return unit.source_family_ids
    return DEFAULT_SOURCE_FAMILY_BY_DOMAIN.get(unit.domain, ["v30.source.synthetic_runtime_baseline"])


def _unit_score(
    unit: KnowledgeRulePortraitUnit,
    matched_supports: list[str],
    policy_payload: dict[str, object] | None,
) -> tuple[float, list[str]]:
    base = min(1.0, 0.58 + 0.14 * len(matched_supports))
    weights = _krp_weights(policy_payload)
    unit_weight = weights.get(unit.unit_id, weights.get(unit.domain, weights.get("*", 1.0)))
    score = round(min(1.0, base * float(unit_weight)), 3)
    return score, [
        f"matched_support_count:{len(matched_supports)}",
        f"krp_policy_weight:{round(float(unit_weight), 3)}",
    ]


def _krp_weights(policy_payload: dict[str, object] | None) -> dict[str, float]:
    raw_weights = (policy_payload or {}).get("krp_unit_weights", {})
    if not isinstance(raw_weights, dict):
        return {"*": 1.0}
    weights: dict[str, float] = {"*": 1.0}
    for key, value in raw_weights.items():
        try:
            weights[str(key)] = float(value)
        except (TypeError, ValueError):
            continue
    return weights


def _string_list(value: object) -> set[str]:
    if not isinstance(value, list):
        return set()
    return {str(row) for row in value if str(row)}
