export type ClassicalPatternStatus = "implemented" | "partial" | "planned";

export type ClassicalPatternEntry = {
  id: string;
  name: string;
  family: string;
  status: ClassicalPatternStatus;
  definition: string;
  conditions: string[];
  breakers: string[];
  implementedBy?: string[];
  notes?: string;
  references?: string[];
};

export const classicalPatternCatalog: ClassicalPatternEntry[] = [
  {
    id: "zhengguan",
    name: "正官格",
    family: "正格八格",
    status: "partial",
    definition: "月令官星当权，以官为格，重在官星清纯、得护、不受伤。",
    conditions: ["月令主气或司令透出为正官", "官星不被严重冲克刑破", "可走官印、财官等成格路线"],
    breakers: ["伤官直克官星", "官杀混杂失清", "官轻无根又受冲破"],
    implementedBy: ["ten_god_pattern", "classical.pattern.axis.v1", "classical.pattern.finance_officer.v1"],
    references: ["《子平真诠》八格/六格脉络", "《子平正宗》定格与破格例"],
  },
  {
    id: "qisha",
    name: "七杀格",
    family: "正格八格",
    status: "partial",
    definition: "月令七杀当权，以杀立格，要求有制、有化或有情，不可横暴无制。",
    conditions: ["月令主气或司令透出为七杀", "存在食神制杀、印化杀、刃合杀等路线之一", "杀星有根而不过杂"],
    breakers: ["七杀旺而无制无化", "财星助杀过甚", "制化并立互相妨碍导致格局不清"],
    implementedBy: ["ten_god_pattern", "classical.pattern.axis.v1", "classical.pattern.congshi.v1"],
    references: ["《子平真诠》七杀格", "《八字正解》六格大义"],
  },
  {
    id: "zhengcai",
    name: "正财格",
    family: "正格八格",
    status: "partial",
    definition: "月令正财司权，以财为格，重在财星有源、可用、不过分被比劫夺取。",
    conditions: ["月令主气为正财或财透清", "财星有根有源", "配官、食、印时形成稳定路线"],
    breakers: ["比劫重重夺财", "财轻身强而无官食引化", "财透杀混致格败"],
    implementedBy: ["classical.pattern.wealth_star.v1"],
    references: ["《子平真诠》财格败例", "八格法财格综述"],
  },
  {
    id: "piancai",
    name: "偏财格",
    family: "正格八格",
    status: "partial",
    definition: "月令偏财秉令，以偏财为格，偏重流通与驭财能力。",
    conditions: ["月令司令为偏财", "财有根气并能流向官或食", "身不至于过弱失驭"],
    breakers: ["比劫争财", "财多坏印", "财旺生杀失控"],
    implementedBy: ["classical.pattern.wealth_star.v1"],
    references: ["八格法财格延伸口径", "《三命通会》财官类例"],
  },
  {
    id: "zhengyin",
    name: "正印格",
    family: "正格八格",
    status: "partial",
    definition: "月令印绶当权，以印为格，重在印能护身护官而不壅滞。",
    conditions: ["月令主气为正印", "印星得时得地", "可走官印相生或印用官路线"],
    breakers: ["财星重破印", "印重身强而无泄化", "印轻又受财伤"],
    implementedBy: ["classical.pattern.seal_star.v1"],
    references: ["《子平真诠》印格败例", "《子平正宗》取用"],
  },
  {
    id: "pianyin",
    name: "偏印格",
    family: "正格八格",
    status: "partial",
    definition: "月令偏印秉令，以枭印为格，偏印可为格，但要防夺食与壅滞。",
    conditions: ["月令主气为偏印", "印有清纯或能转化七杀", "与食伤关系需单独审计"],
    breakers: ["枭神夺食", "印重闭塞无财疏通", "印食同透失衡"],
    implementedBy: ["ten_god_pattern", "classical.ziping.balance.v1", "classical.ziping.yongshen.v1"],
    references: ["十格/八格中枭印口径", "《子平真诠》偏印与食神辨义"],
  },
  {
    id: "shishen",
    name: "食神格",
    family: "正格八格",
    status: "partial",
    definition: "月令食神秉令，以食神为格，重在清秀流通，可生财、制杀。",
    conditions: ["月令主气为食神", "食神有气而不受枭夺", "可行食神生财或食神制杀路线"],
    breakers: ["枭印夺食", "生财同时露杀失清", "食神太轻无力制杀"],
    implementedBy: ["ten_god_pattern", "classical.pattern.axis.v1"],
    references: ["《子平真诠》食神格败例", "八格法食神格综述"],
  },
  {
    id: "shangguan",
    name: "伤官格",
    family: "正格八格",
    status: "partial",
    definition: "月令伤官秉令，以伤官为格，宜配印、财，不宜裸见官。",
    conditions: ["月令主气为伤官", "有印护官或有财承泄", "伤官力量清晰且有去路"],
    breakers: ["非金水伤官而见官", "生财带杀失控", "伤轻身旺又佩印不足"],
    implementedBy: ["ten_god_pattern", "classical.pattern.axis.v1", "classical.ziping.month_command.v1"],
    references: ["《子平真诠》伤官格败例", "八格法伤官配印脉络"],
  },
  {
    id: "jianlu",
    name: "建禄格",
    family: "禄劫刃",
    status: "partial",
    definition: "月令值日主临官之地，以建禄立格，身常偏旺，喜财官引化。",
    conditions: ["月令与日主同气而处临官", "身旺可取官或财为相神", "不宜比劫再重无制"],
    breakers: ["无财官可用", "比劫太重争财", "用官而伤官并发无印护"],
    implementedBy: ["classical.pattern.jianlu_yuejie.v1", "classical.ziping.balance.v1"],
    references: ["《子平真诠》建禄月劫", "建禄格综述资料"],
  },
  {
    id: "yuejie",
    name: "月劫格",
    family: "禄劫刃",
    status: "partial",
    definition: "月令为劫财司令，常与建禄并论，重点在能否用财官化比劫之争。",
    conditions: ["月令主气为劫财", "原局能见财官制衡", "不被纯比劫拖入争夺态"],
    breakers: ["比劫太旺无财官", "透杀透印反使格局混浊", "劫重财轻难成格"],
    implementedBy: ["classical.pattern.jianlu_yuejie.v1", "classical.ziping.balance.v1"],
    references: ["《子平真诠》建禄月劫之格败也", "建禄月劫并论资料"],
  },
  {
    id: "yangren",
    name: "羊刃格",
    family: "禄劫刃",
    status: "partial",
    definition: "月令为帝旺之刃气，以羊刃立格，气势猛烈，常需官杀制伏或财食引导。",
    conditions: ["月令为阳刃所临", "官杀可制身刃", "财星有根亦可为用"],
    breakers: ["无官杀无财可制", "刑冲太重", "刃重再逢刃身过暴"],
    implementedBy: ["classical.pattern.yangren.v1"],
    references: ["羊刃格综述", "《子平真诠》阳刃无官杀，刃格败也"],
  },
  {
    id: "zaqi_caiguan",
    name: "杂气财官格",
    family: "杂气格",
    status: "partial",
    definition: "辰戌丑未等杂气月中，财官透出而取格，重在司令与透干配合。",
    conditions: ["生于辰戌丑未杂气月", "财或官透干得清", "杂气主次与透干一致"],
    breakers: ["杂而不清", "透而无根", "被冲破失令"],
    implementedBy: ["classical.pattern.zaqi_caiguan.v1"],
    references: ["《三命通变渊源》十八格", "杂气格网络综述"],
  },
  {
    id: "zaqi_yin",
    name: "杂气印绶格",
    family: "杂气格",
    status: "partial",
    definition: "杂气月中印绶透出成格，依赖月令藏干与透干定主。",
    conditions: ["辰戌丑未月", "正印或偏印透干", "印有根且可护格"],
    breakers: ["财破印", "杂透失清", "透印而印无根"],
    implementedBy: ["classical.pattern.zaqi_yin.v1"],
    references: ["《子平三命通变渊源》十八格", "《子平核心》杂气举例"],
  },
  {
    id: "zaqi_qisha",
    name: "杂气七杀格",
    family: "杂气格",
    status: "partial",
    definition: "杂气月中七杀透干，以杂气七杀成格，尤需制化路线。",
    conditions: ["杂气月杀透", "有印化、食制、刃合等路线", "杀有根但不过暴"],
    breakers: ["杀旺无制", "财助杀太过", "制化混乱"],
    implementedBy: ["classical.pattern.zaqi_qisha.v1"],
    references: ["杂气七杀现代整理", "杀格制化原理"],
  },
  {
    id: "guanyin_xiangsheng",
    name: "官印相生",
    family: "组合成格",
    status: "partial",
    definition: "官格或印格中，官生印、印护官，形成相互成就的清贵路线。",
    conditions: ["官印两全且不相战", "官可生印、印可护官", "食伤不致破官"],
    breakers: ["财星坏印", "伤官破官", "官杀混杂"],
    implementedBy: ["classical.pattern.guanyin.v1"],
    references: ["《子平真诠》正官佩印者", "官印相生传统口径"],
  },
  {
    id: "shayin_xiangsheng",
    name: "杀印相生",
    family: "组合成格",
    status: "partial",
    definition: "七杀有印化之，使凶神受教化，转为权柄之源。",
    conditions: ["月令或主轴为七杀", "印星透出得力", "印能化杀且不被财坏"],
    breakers: ["财坏印", "印轻杀重", "食制与印化并立互碍"],
    implementedBy: ["classical.pattern.shayin.v1"],
    references: ["《八字正解》六格大义", "杀印相生成格综述"],
  },
  {
    id: "shishen_zhisha",
    name: "食神制杀",
    family: "组合成格",
    status: "partial",
    definition: "七杀旺而食神透，以食神制服七杀，是杀格最重要路线之一。",
    conditions: ["七杀得令或有力", "食神透出且有根", "制杀不过度亦不失力"],
    breakers: ["枭印夺食", "财泄食生杀", "食轻杀重无力制"],
    implementedBy: ["classical.pattern.shishen_zhisha.v1"],
    references: ["《子平真诠》食神带煞", "《八字正解》用食神克制七杀"],
  },
  {
    id: "shangguan_peiyin",
    name: "伤官配印",
    family: "组合成格",
    status: "partial",
    definition: "伤官旺而见印，以印制伤护官，是伤官格高级成格路线。",
    conditions: ["伤官旺而成势", "印星得力可制伤", "官星或事业轴可被保护"],
    breakers: ["财运坏印", "伤轻而印过重", "伤官与官直接冲突无印救"],
    implementedBy: ["classical.pattern.shangguan_peiyin.v1"],
    references: ["《子平真诠》伤官佩印", "伤官配印命理综述"],
  },
  {
    id: "shangguan_shengcai",
    name: "伤官生财",
    family: "组合成格",
    status: "partial",
    definition: "伤官之气顺泄到财星，形成才华变现、输出成财的路线。",
    conditions: ["伤官旺而财有承接", "财星有根", "不被官杀打断"],
    breakers: ["见官破局", "比劫夺财", "财弱无承接"],
    implementedBy: ["classical.pattern.shangguan_shengcai.v1"],
    references: ["伤官生财常见格路", "月令格与流通法结合"],
  },
  {
    id: "shishen_shengcai",
    name: "食神生财",
    family: "组合成格",
    status: "partial",
    definition: "食神吐秀而生财，气机温润，属清纯流通路线。",
    conditions: ["食神有力", "财星得承", "不被枭印破食"],
    breakers: ["枭神夺食", "杀星杂出", "食轻财重失衡"],
    implementedBy: ["classical.pattern.shishen_shengcai.v1"],
    references: ["《子平真诠》食神格", "食神生财常规路线"],
  },
  {
    id: "yangren_jiasha",
    name: "阳刃驾杀",
    family: "组合成格",
    status: "partial",
    definition: "羊刃身旺，借七杀为权，形成刚猛有制的权格路线。",
    conditions: ["身旺刃强", "七杀得用", "刃杀相成而不过战"],
    breakers: ["无制成暴", "食伤反克杀", "官杀虚浮无根"],
    implementedBy: ["classical.pattern.yangren_jiasha.v1"],
    references: ["羊刃格与驾杀口径", "《子平真诠》阳刃用杀"],
  },
  {
    id: "congwang",
    name: "从旺格",
    family: "从格",
    status: "partial",
    definition: "日主与印比成势一边倒，财官食伤皆弱或被去尽，顺其旺势而从。",
    conditions: ["日主生旺月令", "印比禄刃成势", "克泄耗几乎无气"],
    breakers: ["财官食伤有根有力", "日主虽旺但仍可取常格", "杂气破从"],
    implementedBy: ["classical.pattern.congwang.v1"],
    references: ["从旺格综述", "《子平真诠》或从或化及一方专旺"],
  },
  {
    id: "congqiang",
    name: "从强格",
    family: "从格",
    status: "partial",
    definition: "与从旺近似，强调日主及帮扶之神绝对主导，取顺势不逆。",
    conditions: ["日主和印比同党压倒全局", "异党无根或尽去", "顺势为用"],
    breakers: ["存在可用常格路线", "异党透而通根", "刑冲合化破局"],
    implementedBy: ["classical.pattern.congqiang.v1"],
    references: ["从强/从旺现代整理", "《子平真诠》一方专旺"],
  },
  {
    id: "congcai",
    name: "从财格",
    family: "从格",
    status: "partial",
    definition: "日主极弱而财党成势，顺财势而从之。",
    conditions: ["财星成势", "日主极弱无根", "印比不能扶起日主"],
    breakers: ["印比透出有根", "官杀食伤杂乱破纯", "财势不专"],
    implementedBy: ["classical.pattern.congcai.v1"],
    references: ["从财格常见定义", "从格系统整理"],
  },
  {
    id: "congsha",
    name: "从杀格",
    family: "从格",
    status: "partial",
    definition: "日主极弱，七杀独旺成势，弃命从杀。",
    conditions: ["杀星成势独旺", "日主无根无助", "印食比劫不能救起日主"],
    breakers: ["印星化杀", "食神制杀", "比劫扶身令其不从"],
    implementedBy: ["classical.pattern.congsha.v1"],
    references: ["从杀格资料", "《子平真诠》从格脉络"],
  },
  {
    id: "conger",
    name: "从儿格",
    family: "从格",
    status: "partial",
    definition: "食伤成党而日主无力抗衡，顺从食伤泄秀之势。",
    conditions: ["食伤极旺", "日主弱无根", "印比不足以回扶"],
    breakers: ["印星有力回身", "官杀破食伤之势", "财杀混杂不纯"],
    implementedBy: ["classical.pattern.conger.v1"],
    references: ["从儿格资料", "食伤一方专旺口径"],
  },
  {
    id: "congruo",
    name: "从弱格",
    family: "从格",
    status: "partial",
    definition: "日主一切扶助皆弱，整体顺从异党之势，不再按扶抑常格取用。",
    conditions: ["日主弱极", "扶身之神少且无根", "异党集中成势"],
    breakers: ["印比可扶起", "日主并非真弱", "一方不专"],
    implementedBy: ["classical.pattern.congruo.v1"],
    references: ["从弱格现代整理", "从格总论"],
  },
  {
    id: "huaqi",
    name: "化气格",
    family: "化气格",
    status: "partial",
    definition: "天干合化成功，化神得时乘令，四支局全，原气让位于化神。",
    conditions: ["符合天干五合", "化神得时乘令", "四支助化或成局", "原神受制不能争化"],
    breakers: ["合而不化", "化神失令失地", "原气太强反客为主"],
    implementedBy: ["classical.pattern.huaqi.v1"],
    references: ["《子平真诠评注》论杂格", "化气格网络索引"],
  },
  {
    id: "quzhi",
    name: "曲直格",
    family: "专旺外格",
    status: "partial",
    definition: "木气专旺成林，顺木势而行。",
    conditions: ["木势专旺", "金土等逆党弱或无", "格局成一方专旺"],
    breakers: ["金克木强力介入", "杂气破纯", "无法专旺"],
    implementedBy: ["classical.pattern.quzhi.v1"],
    references: ["专旺五格常规分类", "外格系统整理"],
  },
  {
    id: "yanshang",
    name: "炎上格",
    family: "专旺外格",
    status: "partial",
    definition: "火势炎上，一片火气专旺。",
    conditions: ["火势成党", "木生火助", "水金不足以制衡"],
    breakers: ["水来灭火", "土金杂出泄势", "不成专旺"],
    implementedBy: ["classical.pattern.yanshang.v1"],
    references: ["专旺五格常规分类", "外格系统整理"],
  },
  {
    id: "jiase",
    name: "稼穑格",
    family: "专旺外格",
    status: "partial",
    definition: "土气专旺，以厚重成势。",
    conditions: ["土势集中", "火助土成势", "木水不成破局"],
    breakers: ["木强克土", "水多冲土", "杂气不专"],
    implementedBy: ["classical.pattern.jiase.v1"],
    references: ["专旺五格常规分类", "外格系统整理"],
  },
  {
    id: "congge",
    name: "从革格",
    family: "专旺外格",
    status: "partial",
    definition: "金气专旺，顺其肃杀收敛之势。",
    conditions: ["金势成党", "土助金", "火木不成实破"],
    breakers: ["火强炼金", "木强耗金", "不成一气"],
    implementedBy: ["classical.pattern.congge.v1"],
    references: ["专旺五格常规分类", "外格系统整理"],
  },
  {
    id: "runxia",
    name: "润下格",
    family: "专旺外格",
    status: "partial",
    definition: "水气专旺，顺其流润之势。",
    conditions: ["水势成党", "金助水", "土火不成强力阻断"],
    breakers: ["土重塞水", "火重耗水", "局势不专"],
    implementedBy: ["classical.pattern.runxia.v1"],
    references: ["专旺五格常规分类", "外格系统整理"],
  },
  {
    id: "liangshen_chengxiang",
    name: "两神成象",
    family: "外格",
    status: "partial",
    definition: "两类五行/十神高度集中，对峙而成稳定象局。",
    conditions: ["两神势力集中且成象", "第三方干扰少", "结构稳定可辨"],
    breakers: ["第三方介入打破纯度", "主次颠倒", "不成专象"],
    implementedBy: ["classical.pattern.liangshen.v1"],
    references: ["外格系统整理", "现代格局归类资料"],
  },
  {
    id: "tianyuan_yiqi",
    name: "天元一气",
    family: "外格",
    status: "partial",
    definition: "天干地支同气或高度一元化，形成一气纯粹之局。",
    conditions: ["干支同气高度统一", "杂神不扰", "气势单纯"],
    breakers: ["冲合刑害破纯", "异气强透", "只局部同气不成全局"],
    implementedBy: ["classical.pattern.tianyuan.v1"],
    references: ["外格系统整理", "国易堂外格名录摘要"],
  },
];

export function summarizeClassicalPatternCatalog() {
  const total = classicalPatternCatalog.length;
  const implemented = classicalPatternCatalog.filter((item) => item.status === "implemented").length;
  const partial = classicalPatternCatalog.filter((item) => item.status === "partial").length;
  const planned = classicalPatternCatalog.filter((item) => item.status === "planned").length;
  const familyCounts = classicalPatternCatalog.reduce<Record<string, number>>((acc, item) => {
    acc[item.family] = (acc[item.family] || 0) + 1;
    return acc;
  }, {});
  return { total, implemented, partial, planned, familyCounts };
}
