from __future__ import annotations

from typing import Any, Dict, List


def core_seed_units() -> List[Dict[str, Any]]:
    return [
        _unit(
            "core.heavenly_stems",
            "core_structure",
            "Heavenly Stems",
            "The ten heavenly stems are visible stem symbols used in Bazi pillar construction.",
            ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"],
            ["stem", "pillar", "天干", "四柱"],
            "core_symbol_evidence",
        ),
        _unit(
            "core.earthly_branches",
            "core_structure",
            "Earthly Branches",
            "The twelve earthly branches are branch symbols used in pillars and branch relation detection.",
            ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"],
            ["branch", "pillar", "地支", "冲", "合"],
            "core_symbol_evidence",
        ),
        _unit(
            "core.five_elements",
            "five_element",
            "Five Elements",
            "The five elements classify stems, branches, hidden stems, and relation mapping inputs.",
            ["wood", "fire", "earth", "metal", "water"],
            ["element", "五行", "生克", "ten_god"],
            "element_classification_evidence",
        ),
        _unit(
            "core.stem_element_yinyang",
            "five_element",
            "Stem Element and Yin Yang Mapping",
            "Each heavenly stem maps to one element and one yin-yang polarity.",
            ["甲=wood/yang", "乙=wood/yin", "丙=fire/yang", "丁=fire/yin", "戊=earth/yang", "己=earth/yin", "庚=metal/yang", "辛=metal/yin", "壬=water/yang", "癸=water/yin"],
            ["stem", "element", "yin_yang", "日主"],
            "stem_metadata_evidence",
        ),
        _unit(
            "core.month_command_anchor",
            "core_structure",
            "Month Command as Structural Anchor",
            "月令 is the month-branch layer used as an entry point for reading season, environment, and structural background. In V19 it explains context and evidence priority; it is not a standalone verdict.",
            ["month_branch", "season_context", "environment_anchor", "evidence_priority"],
            ["月令", "月支", "month command", "season", "得令", "失令", "结构入口"],
            "month_command_structure_evidence",
        ),
        _unit(
            "core.day_master_anchor",
            "core_structure",
            "Day Master as Reference Point",
            "日主 is the reference stem from which relationship metadata such as ten-god labels and element relations are calculated. It is a structural reference point, not a personality or fate conclusion by itself.",
            ["day_stem", "reference_stem", "relationship_origin", "not_personality_verdict"],
            ["日主", "日干", "day master", "reference", "结构基点"],
            "day_master_reference_evidence",
        ),
        _unit(
            "core.day_master_month_relation",
            "strength",
            "Day Master and Month Branch Relationship",
            "The day-master/month-branch relation is a primary structure question: it asks how the reference stem is situated inside the seasonal environment. V19 must describe the relation as evidence, not as a single strength judgement.",
            ["day_master", "month_branch", "seasonal_environment", "strength_evidence_candidate"],
            ["日主", "月令", "身强", "身弱", "得令", "失令", "承载力"],
            "day_month_relation_evidence",
        ),
        _unit(
            "core.hidden_stem_structure_layers",
            "core_structure",
            "Hidden Stems as Structure Sources",
            "藏干 show what stems are contained inside a branch. They explain where a relationship or element signal can come from, but a hidden stem alone must not be treated as a conclusion.",
            ["branch", "hidden_stems", "main_middle_residual_layers", "signal_source"],
            ["藏干", "地支藏干", "透干", "结构来源", "hidden stem"],
            "hidden_stem_layer_evidence",
        ),
        _unit(
            "core.visible_hidden_layering",
            "core_structure",
            "Visible and Hidden Layers",
            "Visible stems, branch surfaces, and hidden stems are different structure layers. V19 should explain which layer a fact belongs to before composing an answer.",
            ["visible_stem_layer", "branch_surface_layer", "hidden_stem_layer", "layered_explanation"],
            ["透干", "藏干", "明现", "隐藏", "层级", "visible", "hidden"],
            "structure_layering_evidence",
        ),
        _unit(
            "core.ten_god_mapping_boundary",
            "ten_god",
            "Ten God Mapping Boundary",
            "Ten-god labels are relational metadata derived from day-master element/polarity versus target stem element/polarity; labels alone are not conclusions.",
            ["requires day_master", "requires target_stem", "output is relation label only"],
            ["ten_god", "十神", "日主", "income_stability"],
            "ten_god_relation_evidence",
        ),
        _unit(
            "ten_god.relationship_metadata_plain_language",
            "ten_god",
            "Ten God Labels as Relationship Metadata",
            "十神 labels should be explained as relationship metadata: 比劫, 食伤, 财, 官杀, and 印 describe relation types around the day master. They do not directly mean wealth, job, marriage, health, or fate.",
            ["peer", "output", "wealth", "officer", "resource", "relationship_metadata_only"],
            ["十神", "比劫", "食伤", "财星", "官杀", "印星", "关系元数据"],
            "ten_god_plain_language_evidence",
        ),
        _unit(
            "ten_god.wealth_star_boundary",
            "wealth",
            "Wealth Star Boundary",
            "财星 is a relationship label in the ten-god system. In V19 it can support wealth-structure or income-stability evidence only when connected to explicit structure facts; it is not by itself a money prediction.",
            ["wealth_star_label", "requires_structure_context", "not_money_prediction", "income_signal_candidate"],
            ["财星", "正财", "偏财", "财富", "收入", "wealth", "money"],
            "wealth_star_boundary_evidence",
        ),
        _unit(
            "five_element.generation_control_boundary",
            "five_element",
            "Element Generation and Control Boundary",
            "五行生克 describes structural relationships among elements. In V19 it can explain support, drain, control, or same-element relation, but it must not be converted into good/bad language without a reviewed rule.",
            ["generate", "control", "same", "support_drain_control", "no_good_bad_by_default"],
            ["五行", "生克", "相生", "相克", "帮扶", "泄耗", "克制"],
            "element_relation_boundary_evidence",
        ),
        _unit(
            "wealth.income_stability_rule_basis",
            "wealth",
            "Income Stability Rule Basis",
            "Income stability is a bounded wealth-domain structure signal derived from self capacity, wealth presence, wealth accessibility, volatility, and structure binding. It is not a fortune prediction.",
            [
                "self_capacity",
                "wealth_presence",
                "wealth_accessibility",
                "volatility",
                "structure_binding",
                "income_stability",
            ],
            ["income_stability", "收入稳定性", "wealth", "财富", "stability", "规则依据"],
            "income_stability_evidence",
        ),
        _unit(
            "wealth.income_path_structure_boundary",
            "wealth",
            "Income Path as Structure",
            "An income-path answer should explain how structure signals are organized: carrying capacity, wealth presence, accessibility, volatility, and binding. It should not promise income level, timing, or financial outcome.",
            ["self_capacity", "wealth_presence", "wealth_accessibility", "volatility", "structure_binding", "no_timing_claim"],
            ["收入路径", "收入稳定", "财路", "财富结构", "可达性", "波动", "牵制"],
            "income_path_structure_evidence",
        ),
        _unit(
            "core.pillar_structure",
            "core_structure",
            "Pillar Structure",
            "A Bazi chart is represented as four pillars: year, month, day, and hour, each containing a stem and branch.",
            ["year_pillar", "month_pillar", "day_pillar", "hour_pillar"],
            ["chart", "pillar", "四柱", "排盘"],
            "pillar_structure_evidence",
        ),
        _unit(
            "core.six_clash",
            "core_structure",
            "Six Clash",
            "Six clash is a structural branch-pair relation. In V19 it is represented as relation evidence only, not a good/bad judgement.",
            ["子午", "丑未", "寅申", "卯酉", "辰戌", "巳亥"],
            ["clash", "冲", "流年", "大运", "relation"],
            "branch_relation_evidence",
        ),
        _unit(
            "core.six_combination",
            "core_structure",
            "Six Combination",
            "Six combination is a structural branch-pair relation. In V19 it records relation presence without producing prediction text.",
            ["子丑", "寅亥", "卯戌", "辰酉", "巳申", "午未"],
            ["combination", "合", "六合", "流年", "大运", "relation"],
            "branch_relation_evidence",
        ),
        _unit(
            "core.three_harmony",
            "core_structure",
            "Three Harmony",
            "Three harmony is a branch-set structure used as relation evidence when the required branches appear in natal or time context.",
            ["申子辰", "亥卯未", "寅午戌", "巳酉丑"],
            ["three_harmony", "三合", "流年", "relation"],
            "branch_set_relation_evidence",
        ),
        _unit(
            "core.branch_relation_layer_boundary",
            "core_structure",
            "Branch Relation Layer Boundary",
            "Branch relations must be separated by layer: natal-internal relations describe the base chart, while luck-cycle and flow-year relations describe time context. The same relation word should not be mixed across layers.",
            ["natal_internal", "luck_cycle_to_natal", "flow_year_to_natal", "layer_required"],
            ["地支关系", "冲合", "六合", "三合", "本命", "大运", "流年", "层级"],
            "branch_relation_layer_evidence",
        ),
        _unit(
            "core.vault_structure_boundary",
            "core_structure",
            "Vault Structure Reading Boundary",
            "辰、戌、丑、未 can be read as vault/storage branches. V19 should answer where the vault appears and what hidden stems it contains; it must not claim a vault opens, closes, or changes fortune without a reviewed rule.",
            ["辰", "戌", "丑", "未", "location_first", "hidden_stems", "no_vault_opening_claim"],
            ["墓库", "库", "辰戌丑未", "藏干", "开库", "结构层"],
            "vault_boundary_evidence",
        ),
        _unit(
            "core.time_structure_context",
            "luck_flow",
            "Time Structure Context",
            "Luck cycle and flow year provide time-context structures for later inference. They do not directly generate fortune, narrative, or ResultCard changes.",
            ["natal", "luck_cycle", "flow_year", "context_only"],
            ["flow_year", "luck_cycle", "大运", "流年", "time_context"],
            "time_context_evidence",
        ),
        _unit(
            "luck_flow.time_context_boundary_plain_language",
            "luck_flow",
            "Time Context Boundary in Plain Language",
            "大运 and 流年 are timing layers. They can explain why a question is relevant now or which relation is visible, but V19 must not automatically use them to mutate income_stability or make year-specific predictions.",
            ["luck_cycle_context", "flow_year_context", "question_guidance", "no_result_mutation"],
            ["时间背景", "大运", "流年", "今年", "当前", "不改变结果", "context only"],
            "time_context_plain_language_evidence",
        ),
        _unit(
            "luck_flow.time_relation_context_only",
            "luck_flow",
            "Timing Relations as Context Only",
            "When a luck cycle or flow year forms a branch relation with the natal chart, V19 should state the relation and its layer, then stop at context explanation unless a separate reviewed rule explicitly consumes it.",
            ["relation_name", "time_layer", "natal_target", "requires_reviewed_rule_for_result"],
            ["流年冲合", "大运冲合", "关系背景", "时间层", "只作背景"],
            "time_relation_context_evidence",
        ),
        _unit(
            "core.inference_input_boundary",
            "theme_mapping",
            "Inference Input Boundary",
            "V19 inference must consume explicit structured inputs and reviewed evidence templates. Knowledge units do not directly become predictions.",
            ["knowledge=evidence_template_only", "inference=separate_layer", "no_direct_prediction"],
            ["inference", "agent", "knowledge", "边界"],
            "runtime_boundary_evidence",
        ),
        _unit(
            "core.day_master_strength_boundary",
            "strength",
            "Day Master Strength Boundary",
            "Day-master strength can be a carrying-capacity signal only after feature extraction; it must not be guessed from a single symbol or used as a standalone conclusion.",
            ["requires month command", "requires roots", "requires support pressure balance"],
            ["strength", "旺衰", "身强", "身弱", "日主"],
            "core_strength_evidence",
        ),
        _unit(
            "strength.root_and_capacity_evidence",
            "strength",
            "Root and Carrying Capacity Evidence",
            "根气、通根、同党和印星 support can be treated as carrying-capacity evidence only when extracted from explicit stems, branches, hidden stems, and month context. V19 should report evidence, not guess strength from one symbol.",
            ["root_evidence", "same_element_support", "resource_support", "month_context", "capacity_signal"],
            ["根气", "通根", "同党", "印星", "承载力", "身强", "身弱"],
            "capacity_evidence_boundary",
        ),
        _unit(
            "answer.structure_plain_language",
            "answer_expression",
            "Plain-Language Structure Answer",
            "A useful V19 answer should name the user's question, name the matched facts, explain the structural meaning in ordinary language, and avoid internal IDs or generic disclaimers unless the user asks about boundaries.",
            ["user_question", "matched_facts", "plain_language", "no_internal_debug_dump"],
            ["回答", "说人话", "结构回答", "解释", "用户问题", "answer"],
            "answer_expression_evidence",
        ),
        _unit(
            "answer.unsupported_question_boundary",
            "answer_expression",
            "Unsupported Question Boundary",
            "If a question asks for marriage, health, exact timing, luck, rich/poor judgement, or other unsupported predictions, V19 should say the current system only supports structure reading and offer a supported structural question.",
            ["unsupported_intent", "clear_boundary", "offer_supported_question", "no_fake_answer"],
            ["不支持", "婚姻", "健康", "发财", "什么时候", "预测", "空回答"],
            "unsupported_answer_boundary_evidence",
        ),
    ]


def _unit(
    knowledge_id: str,
    domain: str,
    title: str,
    statement: str,
    facts: List[str],
    keywords: List[str],
    evidence_type: str,
) -> Dict[str, Any]:
    return {
        "knowledge_id": knowledge_id,
        "domain": domain,
        "title": title,
        "statement": statement,
        "conditions": {
            "structured_facts": facts,
            "keywords": keywords,
            "allowed_usage": ["evidence_template", "structure_explanation", "agent_context"],
            "forbidden_usage": ["fortune", "score", "good_bad_judgement", "traditional_prediction_text"],
        },
        "feature_mapping": {
            "evidence_type": evidence_type,
            "input_requirements": ["chart_structure", "time_context_optional", "user_question"],
            "detection_logic": {"op": "contextual_keyword_and_structure_match"},
            "output_fields": ["knowledge_id", "title", "statement", "structured_facts", "guardrails"],
        },
        "effects": {"runtime_scope": "evidence_only"},
        "risks": ["May be misused as prediction if separated from guardrails."],
        "uncertainty": ["Exact downstream inference requires separate reviewed rules."],
        "conflicts": [],
        "source_refs": ["docs/bazi_knowledge/core/core_units_v1.md", "docs/v19/V19_KNOWLEDGE_KERNEL_CHARTER.md"],
        "confidence_prior": 0.82,
        "version": "v1",
    }
