from __future__ import annotations

from typing import Any, Dict, List


def core_seed_units() -> List[Dict[str, Any]]:
    return [
        _unit(
            "core.heavenly_stems",
            "core_structure",
            "Heavenly Stems",
            "The ten heavenly stems are visible stem symbols used in Bazi pillar construction.",
            ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"],
            ["stem", "pillar", "天干", "四柱"],
            "core_symbol_evidence",
        ),
        _unit(
            "core.earthly_branches",
            "core_structure",
            "Earthly Branches",
            "The twelve earthly branches are branch symbols used in pillars and branch relation detection.",
            ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"],
            ["branch", "pillar", "地支", "冲", "合"],
            "core_symbol_evidence",
        ),
        _unit(
            "core.five_elements",
            "five_element",
            "Five Elements",
            "The five elements classify stems, branches, hidden stems, and relation mapping inputs.",
            ["wood", "fire", "earth", "metal", "water"],
            ["element", "五行", "生克", "ten_god"],
            "element_classification_evidence",
        ),
        _unit(
            "core.stem_element_yinyang",
            "five_element",
            "Stem Element and Yin Yang Mapping",
            "Each heavenly stem maps to one element and one yin-yang polarity.",
            ["甲=wood/yang", "乙=wood/yin", "丙=fire/yang", "丁=fire/yin", "戊=earth/yang", "己=earth/yin", "庚=metal/yang", "辛=metal/yin", "壬=water/yang", "癸=water/yin"],
            ["stem", "element", "yin_yang", "日主"],
            "stem_metadata_evidence",
        ),
        _unit(
            "core.ten_god_mapping_boundary",
            "ten_god",
            "Ten God Mapping Boundary",
            "Ten-god labels are relational metadata derived from day-master element/polarity versus target stem element/polarity; labels alone are not conclusions.",
            ["requires day_master", "requires target_stem", "output is relation label only"],
            ["ten_god", "十神", "日主", "income_stability"],
            "ten_god_relation_evidence",
        ),
        _unit(
            "wealth.income_stability_rule_basis",
            "wealth",
            "Income Stability Rule Basis",
            "Income stability is a bounded wealth-domain structure signal derived from self capacity, wealth presence, wealth accessibility, volatility, and structure binding. It is not a fortune prediction.",
            [
                "self_capacity",
                "wealth_presence",
                "wealth_accessibility",
                "volatility",
                "structure_binding",
                "income_stability",
            ],
            ["income_stability", "收入稳定性", "wealth", "财富", "stability", "规则依据"],
            "income_stability_evidence",
        ),
        _unit(
            "core.pillar_structure",
            "core_structure",
            "Pillar Structure",
            "A Bazi chart is represented as four pillars: year, month, day, and hour, each containing a stem and branch.",
            ["year_pillar", "month_pillar", "day_pillar", "hour_pillar"],
            ["chart", "pillar", "四柱", "排盘"],
            "pillar_structure_evidence",
        ),
        _unit(
            "core.six_clash",
            "core_structure",
            "Six Clash",
            "Six clash is a structural branch-pair relation. In V19 it is represented as relation evidence only, not a good/bad judgement.",
            ["子午", "丑未", "寅申", "卯酉", "辰戌", "巳亥"],
            ["clash", "冲", "流年", "大运", "relation"],
            "branch_relation_evidence",
        ),
        _unit(
            "core.six_combination",
            "core_structure",
            "Six Combination",
            "Six combination is a structural branch-pair relation. In V19 it records relation presence without producing prediction text.",
            ["子丑", "寅亥", "卯戌", "辰酉", "巳申", "午未"],
            ["combination", "合", "六合", "流年", "大运", "relation"],
            "branch_relation_evidence",
        ),
        _unit(
            "core.three_harmony",
            "core_structure",
            "Three Harmony",
            "Three harmony is a branch-set structure used as relation evidence when the required branches appear in natal or time context.",
            ["申子辰", "亥卯未", "寅午戌", "巳酉丑"],
            ["three_harmony", "三合", "流年", "relation"],
            "branch_set_relation_evidence",
        ),
        _unit(
            "core.time_structure_context",
            "luck_flow",
            "Time Structure Context",
            "Luck cycle and flow year provide time-context structures for later inference. They do not directly generate fortune, narrative, or ResultCard changes.",
            ["natal", "luck_cycle", "flow_year", "context_only"],
            ["flow_year", "luck_cycle", "大运", "流年", "time_context"],
            "time_context_evidence",
        ),
        _unit(
            "core.inference_input_boundary",
            "theme_mapping",
            "Inference Input Boundary",
            "V19 inference must consume explicit structured inputs and reviewed evidence templates. Knowledge units do not directly become predictions.",
            ["knowledge=evidence_template_only", "inference=separate_layer", "no_direct_prediction"],
            ["inference", "agent", "knowledge", "边界"],
            "runtime_boundary_evidence",
        ),
        _unit(
            "core.day_master_strength_boundary",
            "strength",
            "Day Master Strength Boundary",
            "Day-master strength can be a carrying-capacity signal only after feature extraction; it must not be guessed from a single symbol or used as a standalone conclusion.",
            ["requires month command", "requires roots", "requires support pressure balance"],
            ["strength", "旺衰", "身强", "身弱", "日主"],
            "core_strength_evidence",
        ),
    ]


def _unit(
    knowledge_id: str,
    domain: str,
    title: str,
    statement: str,
    facts: List[str],
    keywords: List[str],
    evidence_type: str,
) -> Dict[str, Any]:
    return {
        "knowledge_id": knowledge_id,
        "domain": domain,
        "title": title,
        "statement": statement,
        "conditions": {
            "structured_facts": facts,
            "keywords": keywords,
            "allowed_usage": ["evidence_template", "structure_explanation", "agent_context"],
            "forbidden_usage": ["fortune", "score", "good_bad_judgement", "traditional_prediction_text"],
        },
        "feature_mapping": {
            "evidence_type": evidence_type,
            "input_requirements": ["chart_structure", "time_context_optional", "user_question"],
            "detection_logic": {"op": "contextual_keyword_and_structure_match"},
            "output_fields": ["knowledge_id", "title", "statement", "structured_facts", "guardrails"],
        },
        "effects": {"runtime_scope": "evidence_only"},
        "risks": ["May be misused as prediction if separated from guardrails."],
        "uncertainty": ["Exact downstream inference requires separate reviewed rules."],
        "conflicts": [],
        "source_refs": ["docs/bazi_knowledge/core/core_units_v1.md", "docs/v19/V19_KNOWLEDGE_KERNEL_CHARTER.md"],
        "confidence_prior": 0.82,
        "version": "v1",
    }
