from __future__ import annotations

from collections import Counter

from v30.production.contracts import AssertionLevelHint, SignalPolarity
from v30.ziwei.contracts import ZiweiDomainKey, ZiweiDomainRule


def _rule(
    rule_id: str,
    domain: ZiweiDomainKey,
    condition: str,
    claim_key: str,
    probe_trigger: str,
    *,
    palace_refs: list[str],
    transform_refs: list[str] | None = None,
    related_palaces: list[str] | None = None,
    star_refs: list[str] | None = None,
    claim: str,
    strength: float = 0.58,
    hidden: list[str] | None = None,
) -> ZiweiDomainRule:
    return ZiweiDomainRule(
        rule_id=rule_id,
        domain=domain,
        condition=condition,
        palace_refs=palace_refs,
        star_refs=star_refs or [],
        transform_refs=transform_refs or [],
        related_palaces=related_palaces or [],
        claim=claim,
        claim_key=claim_key,
        probe_trigger=probe_trigger,
        polarity=SignalPolarity.SUPPORT,
        strength_hint=strength,
        confidence_hint=min(0.72, strength + 0.04),
        assertion_level_hint=AssertionLevelHint.WEAK_CANDIDATE,
        target_hidden_attributes=hidden or [],
    )


ZIWEI_V1_DOMAIN_RULES: tuple[ZiweiDomainRule, ...] = (
    _rule(
        "ZW-WEALTH-01",
        "wealth",
        "财帛宫化禄",
        "ziwei_wealth_resource_opportunity",
        "wealth_source_probe",
        palace_refs=["wealth"],
        transform_refs=["lu"],
        claim="财帛宫化禄提示资源或机会进入财务主题，需验证钱从哪里来。",
        hidden=["wealth_source"],
    ),
    _rule(
        "ZW-WEALTH-02",
        "wealth",
        "财帛宫化忌",
        "ziwei_wealth_blockage_or_leakage",
        "wealth_capture_probe",
        palace_refs=["wealth"],
        transform_refs=["ji"],
        claim="财帛宫化忌提示财务卡点或流失风险，需验证守财与回款方式。",
        hidden=["wealth_capture"],
    ),
    _rule(
        "ZW-WEALTH-03",
        "wealth",
        "官禄宫化禄或化权联动财帛",
        "ziwei_career_driven_wealth",
        "career_income_source_probe",
        palace_refs=["career"],
        related_palaces=["wealth"],
        transform_refs=["lu", "quan"],
        claim="官禄宫禄权联动财帛提示收入更可能由职责、平台或职位驱动。",
        hidden=["career_income_source"],
    ),
    _rule(
        "ZW-WEALTH-04",
        "wealth",
        "迁移宫化禄联动财帛",
        "ziwei_external_wealth_opportunity",
        "external_opportunity_probe",
        palace_refs=["travel"],
        related_palaces=["wealth"],
        transform_refs=["lu"],
        claim="迁移宫化禄联动财帛提示外部市场、异地或跨圈层资源可能带来财机。",
        hidden=["external_opportunity"],
    ),
    _rule(
        "ZW-WEALTH-05",
        "wealth",
        "交友宫化忌联动财帛",
        "ziwei_peer_money_friction",
        "partnership_money_probe",
        palace_refs=["friends"],
        related_palaces=["wealth"],
        transform_refs=["ji"],
        claim="交友宫化忌联动财帛提示合作、同辈或分配关系里可能有财务摩擦。",
        hidden=["partnership_money_boundary"],
    ),
    _rule(
        "ZW-WEALTH-06",
        "wealth",
        "田宅宫化禄或禄存入田宅",
        "ziwei_property_asset_opportunity",
        "property_asset_probe",
        palace_refs=["property"],
        transform_refs=["lu"],
        star_refs=["lucun"],
        claim="田宅宫见禄提示不动产、稳定资产或家庭资源可作为财务线索。",
        hidden=["property_asset"],
    ),
    _rule(
        "ZW-CAREER-01",
        "career",
        "官禄宫化禄",
        "ziwei_career_opportunity",
        "career_path_probe",
        palace_refs=["career"],
        transform_refs=["lu"],
        claim="官禄宫化禄提示事业机会和平台资源，需要验证具体赛道。",
        hidden=["career_path"],
    ),
    _rule(
        "ZW-CAREER-02",
        "career",
        "官禄宫化权",
        "ziwei_career_authority_pressure",
        "authority_pressure_probe",
        palace_refs=["career"],
        transform_refs=["quan"],
        claim="官禄宫化权提示职责、权力和压力同时上升，需要验证承压方式。",
        hidden=["authority_pressure"],
    ),
    _rule(
        "ZW-CAREER-03",
        "career",
        "官禄宫化忌",
        "ziwei_career_blockage",
        "career_obstacle_probe",
        palace_refs=["career"],
        transform_refs=["ji"],
        claim="官禄宫化忌提示事业路径存在卡点，需要验证阻塞来自规则、能力还是环境。",
        hidden=["career_obstacle"],
    ),
    _rule(
        "ZW-CAREER-04",
        "career",
        "父母宫化科或文昌文曲入父母/官禄",
        "ziwei_institutional_recognition",
        "platform_support_probe",
        palace_refs=["parents"],
        related_palaces=["career"],
        transform_refs=["ke"],
        star_refs=["wenchang", "wenqu"],
        claim="父母宫化科或文昌文曲联动官禄提示制度、资质、文书或平台认可有作用。",
        hidden=["platform_support"],
    ),
    _rule(
        "ZW-CAREER-05",
        "career",
        "交友宫吉辅支持官禄",
        "ziwei_network_career_support",
        "team_support_probe",
        palace_refs=["friends"],
        related_palaces=["career"],
        star_refs=["zuofu", "youbi", "tiankui", "tianyue"],
        claim="交友宫吉辅联动官禄提示团队、贵人和协作网络可能支撑事业。",
        hidden=["team_support"],
    ),
    _rule(
        "ZW-CAREER-06",
        "career",
        "迁移宫化权/化禄支持官禄",
        "ziwei_external_career_driver",
        "external_career_probe",
        palace_refs=["travel"],
        related_palaces=["career"],
        transform_refs=["lu", "quan"],
        claim="迁移宫禄权支持官禄提示外部环境、出差异地或跨平台机会推动事业。",
        hidden=["external_career_driver"],
    ),
    _rule(
        "ZW-REL-01",
        "relationship",
        "夫妻宫化禄",
        "ziwei_relationship_attraction_or_resource",
        "relationship_mode_probe",
        palace_refs=["spouse"],
        transform_refs=["lu"],
        claim="夫妻宫化禄提示关系中的吸引、资源或互惠感较强，需要验证相处模式。",
        hidden=["relationship_mode"],
    ),
    _rule(
        "ZW-REL-02",
        "relationship",
        "夫妻宫化权",
        "ziwei_relationship_power_pressure",
        "relationship_pressure_probe",
        palace_refs=["spouse"],
        transform_refs=["quan"],
        claim="夫妻宫化权提示关系中权责、控制感或强势互动需要被看见。",
        hidden=["relationship_power_boundary"],
    ),
    _rule(
        "ZW-REL-03",
        "relationship",
        "夫妻宫化忌",
        "ziwei_relationship_blockage",
        "relationship_obstacle_probe",
        palace_refs=["spouse"],
        transform_refs=["ji"],
        claim="夫妻宫化忌提示亲密关系卡点，需要验证反复矛盾的触发点。",
        hidden=["relationship_obstacle"],
    ),
    _rule(
        "ZW-REL-04",
        "relationship",
        "福德宫化忌联动夫妻",
        "ziwei_relationship_emotional_load",
        "emotional_security_probe",
        palace_refs=["fortune"],
        related_palaces=["spouse"],
        transform_refs=["ji"],
        claim="福德宫化忌联动夫妻提示情绪负荷、安全感和恢复力会影响关系判断。",
        hidden=["emotional_security"],
    ),
    _rule(
        "ZW-REL-05",
        "relationship",
        "迁移宫信号联动夫妻",
        "ziwei_relationship_mobility_factor",
        "relationship_distance_probe",
        palace_refs=["travel"],
        related_palaces=["spouse"],
        claim="迁移宫联动夫妻提示距离、外部圈层或生活流动会影响关系节奏。",
        hidden=["relationship_distance"],
    ),
    _rule(
        "ZW-REL-06",
        "relationship",
        "财帛宫化忌联动夫妻",
        "ziwei_relationship_money_pressure",
        "relationship_resource_probe",
        palace_refs=["wealth"],
        related_palaces=["spouse"],
        transform_refs=["ji"],
        claim="财帛宫化忌联动夫妻提示钱、资源分配或安全感可能进入关系压力点。",
        hidden=["relationship_resource_pressure"],
    ),
    _rule(
        "ZW-MOB-01",
        "mobility",
        "迁移宫化禄",
        "ziwei_external_opportunity",
        "mobility_opportunity_probe",
        palace_refs=["travel"],
        transform_refs=["lu"],
        claim="迁移宫化禄提示外部机会和流动资源，需要验证是否适合向外发展。",
        hidden=["mobility_opportunity"],
    ),
    _rule(
        "ZW-MOB-02",
        "mobility",
        "迁移宫化权",
        "ziwei_external_pressure_driver",
        "external_pressure_probe",
        palace_refs=["travel"],
        transform_refs=["quan"],
        claim="迁移宫化权提示外部压力会驱动选择，需验证压力是否能转成行动。",
        hidden=["external_pressure"],
    ),
    _rule(
        "ZW-MOB-03",
        "mobility",
        "迁移宫化忌",
        "ziwei_mobility_blockage",
        "mobility_blockage_probe",
        palace_refs=["travel"],
        transform_refs=["ji"],
        claim="迁移宫化忌提示出行、换环境或外部合作存在阻塞，需要验证阻塞形态。",
        hidden=["mobility_blockage"],
    ),
    _rule(
        "ZW-MOB-04",
        "mobility",
        "迁移宫联动财帛",
        "ziwei_external_market_wealth",
        "external_wealth_probe",
        palace_refs=["travel"],
        related_palaces=["wealth"],
        claim="迁移宫联动财帛提示外部市场与财务机会相关，需要验证收益来源。",
        hidden=["external_wealth"],
    ),
    _rule(
        "ZW-MOB-05",
        "mobility",
        "迁移宫联动官禄",
        "ziwei_external_career_opportunity",
        "external_career_probe",
        palace_refs=["travel"],
        related_palaces=["career"],
        claim="迁移宫联动官禄提示外部平台、地域或跨界机会可能推动事业。",
        hidden=["external_career_driver"],
    ),
    _rule(
        "ZW-MOB-06",
        "mobility",
        "田宅宫化忌且迁移宫强",
        "ziwei_home_mobility_tension",
        "home_mobility_probe",
        palace_refs=["property", "travel"],
        transform_refs=["ji"],
        claim="田宅宫化忌而迁移宫强提示家宅稳定与外部流动之间存在拉扯。",
        hidden=["home_mobility_tension"],
    ),
    _rule(
        "ZW-HEALTH-01",
        "health_pressure",
        "疾厄宫化忌",
        "ziwei_health_pressure_signal",
        "stress_manifestation_probe",
        palace_refs=["health"],
        transform_refs=["ji"],
        claim="疾厄宫化忌提示压力容易有身体化表现，需要验证压力如何显现。",
        hidden=["stress_manifestation"],
    ),
    _rule(
        "ZW-HEALTH-02",
        "health_pressure",
        "疾厄宫化权",
        "ziwei_overwork_or_tension",
        "overwork_pattern_probe",
        palace_refs=["health"],
        transform_refs=["quan"],
        claim="疾厄宫化权提示紧绷、过劳或高压承担，需要验证工作与休息边界。",
        hidden=["overwork_pattern"],
    ),
    _rule(
        "ZW-HEALTH-03",
        "health_pressure",
        "福德宫化忌",
        "ziwei_mental_load_or_recovery_issue",
        "recovery_capacity_probe",
        palace_refs=["fortune"],
        transform_refs=["ji"],
        claim="福德宫化忌提示精神负荷和恢复力是关键变量。",
        hidden=["recovery_capacity"],
    ),
    _rule(
        "ZW-HEALTH-04",
        "health_pressure",
        "官禄宫化忌联动疾厄",
        "ziwei_work_pressure_health_cost",
        "work_stress_probe",
        palace_refs=["career"],
        related_palaces=["health"],
        transform_refs=["ji"],
        claim="官禄宫化忌联动疾厄提示事业压力可能转化为身心成本。",
        hidden=["work_stress_cost"],
    ),
    _rule(
        "ZW-HEALTH-05",
        "health_pressure",
        "财帛宫化忌联动福德/疾厄",
        "ziwei_money_pressure_health_cost",
        "money_stress_probe",
        palace_refs=["wealth"],
        related_palaces=["fortune", "health"],
        transform_refs=["ji"],
        claim="财帛宫化忌联动福德或疾厄提示金钱压力会影响恢复和身心状态。",
        hidden=["money_stress_cost"],
    ),
    _rule(
        "ZW-HEALTH-06",
        "health_pressure",
        "福德宫化禄",
        "ziwei_recovery_resource",
        "recovery_style_probe",
        palace_refs=["fortune"],
        transform_refs=["lu"],
        claim="福德宫化禄提示恢复资源较可用，需要验证最有效的恢复方式。",
        hidden=["recovery_style"],
    ),
    _rule(
        "ZW-PROP-01",
        "property",
        "田宅宫化禄",
        "ziwei_property_opportunity",
        "property_asset_probe",
        palace_refs=["property"],
        transform_refs=["lu"],
        claim="田宅宫化禄提示房产、空间、长期资产或家庭资源有机会。",
        hidden=["property_asset"],
    ),
    _rule(
        "ZW-PROP-02",
        "property",
        "田宅宫化权",
        "ziwei_property_control_pressure",
        "property_pressure_probe",
        palace_refs=["property"],
        transform_refs=["quan"],
        claim="田宅宫化权提示房产、家庭或空间安排里有控制权和压力。",
        hidden=["property_control_pressure"],
    ),
    _rule(
        "ZW-PROP-03",
        "property",
        "田宅宫化忌",
        "ziwei_property_blockage",
        "property_blockage_probe",
        palace_refs=["property"],
        transform_refs=["ji"],
        claim="田宅宫化忌提示居住、资产或家庭资源存在卡点。",
        hidden=["property_blockage"],
    ),
    _rule(
        "ZW-PROP-04",
        "property",
        "父母宫化禄/化科联动田宅",
        "ziwei_family_asset_support",
        "family_asset_probe",
        palace_refs=["parents"],
        related_palaces=["property"],
        transform_refs=["lu", "ke"],
        claim="父母宫禄科联动田宅提示家庭、长辈或制度性资源可能支撑资产。",
        hidden=["family_asset_support"],
    ),
    _rule(
        "ZW-PROP-05",
        "property",
        "财帛宫化忌联动田宅",
        "ziwei_cashflow_asset_tension",
        "cashflow_asset_probe",
        palace_refs=["wealth"],
        related_palaces=["property"],
        transform_refs=["ji"],
        claim="财帛宫化忌联动田宅提示现金流与长期资产之间有张力。",
        hidden=["cashflow_asset_tension"],
    ),
    _rule(
        "ZW-PROP-06",
        "property",
        "迁移宫强联动田宅",
        "ziwei_property_mobility_link",
        "home_mobility_probe",
        palace_refs=["travel"],
        related_palaces=["property"],
        claim="迁移宫强联动田宅提示居住、资产和外部流动之间需要合看。",
        hidden=["home_mobility_tension"],
    ),
)


def load_ziwei_v1_domain_rules() -> list[ZiweiDomainRule]:
    return list(ZIWEI_V1_DOMAIN_RULES)


def rules_by_domain(domain: ZiweiDomainKey) -> list[ZiweiDomainRule]:
    return [rule for rule in ZIWEI_V1_DOMAIN_RULES if rule.domain == domain]


def rule_domain_counts() -> dict[str, int]:
    return dict(Counter(rule.domain for rule in ZIWEI_V1_DOMAIN_RULES))
