from __future__ import annotations


def contract_manifest() -> dict[str, object]:
    return {
        "version": "v40.contract_manifest.v1",
        "context": [
            "LocaleContext",
            "MingliTermEntry",
            "MingliTermDictionary",
            "RoleContext",
            "UserAppSessionContext",
            "ClientContext",
            "EngineContext",
            "EngineCapability",
            "RuntimeContext",
        ],
        "runtime": ["RuntimeRequest", "RuntimeResult"],
        "chart": ["BirthInputCanonical", "BaziChartFacts", "ZiweiChartFacts", "SyntheticCaseSeed"],
        "engine": ["EnginePlan", "EngineRunRequest", "EngineRunResult", "MultiEngineRunResult"],
        "signal": ["RuntimeSignal", "SignalRegistrySnapshot"],
        "decision": [
            "DecisionInputBundle",
            "BranchCandidate",
            "DecisionVerdict",
            "AdvicePlan",
            "ProbeCandidate",
            "DecisionEngineOutput",
        ],
        "probe": [
            "AnswerSignal",
            "HiddenAttributeUpdate",
            "ProbeAnswerResult",
        ],
        "review": [
            "ConsentGrant",
            "AnonymizedCaseView",
            "PractitionerReviewRequest",
            "PractitionerReviewQueueItem",
            "PractitionerReviewResult",
        ],
        "output": [
            "ProductVerdictCard",
            "BranchCard",
            "ProductAdviceCard",
            "LLMExpressionTask",
            "LLMExpressionResult",
            "AcceptanceResult",
            "ExpressionTelemetry",
            "ConversationSeed",
            "ConversationTurn",
            "ProductProjectionBundle",
            "SurfaceSection",
            "SurfaceBundle",
        ],
        "evaluation": [
            "EvaluationCaseSpec",
            "GoldenCase",
            "MetricSummary",
            "EvaluationRunResult",
            "EvaluationBatchSummary",
            "ReleaseGateResult",
            "ReleaseReadinessSummary",
            "ShadowCompareResult",
            "ShadowCompareBatchSummary",
            "TrainingExampleReplayResult",
            "TrainingReplayBatchSummary",
        ],
        "training": [
            "TrainingLabelEvent",
            "TrainableUnit",
            "TrainablePolicyRegistry",
            "TrainingAttribution",
            "BatchTrainerV1Result",
            "TrainingExampleV2",
            "TrainingImpactDiff",
            "LocalOverlay",
            "GlobalWeightVersion",
            "WeightActivationReview",
            "WeightActivationExecution",
        ],
        "migration": ["V30ExportEnvelope", "V30ToV40MigrationPlan"],
        "boundaries": {
            "v30_runtime_import_allowed": False,
            "v30_database_access_allowed": False,
            "v30_redis_access_allowed": False,
            "chart_fact_training_allowed": False,
            "llm_verdict_authority_allowed": False,
            "central_brain_verdict_authority_allowed": False,
            "shadow_compare_writes_production": False,
            "frontend_translation_as_primary_locale_strategy_allowed": False,
            "ui_role_hiding_as_permission_model_allowed": False,
            "client_layout_changes_verdict_allowed": False,
            "engine_direct_verdict_allowed": False,
        },
    }
