import { describe, expect, it, vi } from "vitest";

import type { StreamBoardViewModel } from "@/features/stream-board";
import { buildStreamBoardViewDerivedState } from "@/features/stream-board/viewModel";

function createViewModel(overrides: Partial<StreamBoardViewModel> = {}): StreamBoardViewModel {
  return {
    lang: "ZH",
    setLang: vi.fn(),
    busy: false,
    pipelinePhase: "READY",
    narrativeReshapeActive: false,
    consultationId: 12,
    metadata: null,
    timeline: null,
    referenceYear: new Date().getFullYear(),
    setReferenceYear: vi.fn(),
    seedPreviewPillars: null,
    seedPreviewTimeline: null,
    seedPreviewBusy: false,
    seedPreviewError: "",
    scheduleSeedDraftPreview: vi.fn(),
    refreshSeedPreview: vi.fn().mockResolvedValue(undefined),
    clearLabPipelineForSeedDraft: vi.fn(),
    lastCommittedSeedSignature: "",
    selectedBranch: undefined,
    setSelectedBranch: vi.fn(),
    auditItems: [],
    health: { dbOk: true, llmOk: true },
    llmModelName: "gpt",
    i18nCalls: 0,
    deityScores: {},
    deityEnergyAxes: {},
    deityComponents: {},
    deityTraceDetails: {},
    hoveredDeity: undefined,
    setHoveredDeity: vi.fn(),
    confirmedConflicts: [],
    auditInboxConfirmationBlockedReason: null,
    llmDiagnosticData: null,
    globalEntropy: null,
    consensusHistory: [],
    cards: [],
    resultLogs: [],
    streamingText: "",
    showPreInjectionAbsSnapshot: false,
    setShowPreInjectionAbsSnapshot: vi.fn(),
    mangpaiChipLogsForTrace: [],
    conflictScanLabels: [],
    verdictSkeletonContentKey: "",
    verdictBodyRenderNonce: 0,
    finalVerdictBody: "",
    finalVerdictChangeLog: {},
    finalLogicalEvidence: [],
    finalWorkVector: null,
    finalTopologyGraphV1: null,
    finalStructureCandidatesV0: null,
    finalStructureFinalDecisionV0: null,
    confirmedDecisions: [],
    confirmedDecisionIds: [],
    setConfirmedDecisionIds: vi.fn(),
    urlDecisionHydrated: false,
    snapshotUrlTag: "",
    setAsBaseline: vi.fn().mockResolvedValue(undefined),
    logicDiff: undefined,
    stressTestResult: null,
    genderComparisonResult: null,
    finalVerdictHistory: [],
    selectionResetToken: 0,
    finalVerdictVersionId: "",
    conclusionVersion: 3,
    summaryChanged: false,
    l1Certified: false,
    physicsAudit: null,
    physicsConfidence: null,
    physicsEvidence: [],
    labConfig: {
      WEIGHT_LUCK: 0.4,
      WEIGHT_YEAR: 0.2,
      BASE_BACKFIRE_RISK: 0.2,
      HIGH_IMBALANCE_RISK: 0.35,
      TOMB_LOCK_RATE: 0.9,
      CLIMATE_INTENSITY: 1.0,
      STEM_RESONANCE_BOOST: 1.5,
      TRANSFER_DISTANCE_DECAY: 0.1,
      WORK_MIN_THRESHOLD: 0.5,
      SHOW_WEAK_WORK_PATHS: 1,
      L0_HIDDEN_ENERGY_SCALE: 1.0,
      L0_ROOT_BOOST_FACTOR: 1.0,
      L0_YM_DH_WEIGHT_RATIO: 1.0,
      L1_OP_PROD_ETA: 1.0,
      L1_OP_DEST_ETA: 1.0,
      L1_OP_CONN_ETA: 1.0,
      INTERDIMENSIONAL_CONDUCTIVITY: 0.0,
      INTERDIMENSIONAL_BARRIER_STRENGTH: 1.0,
      CONDUCTIVITY_DECAY_RATE: 0.7,
      GHOST_ENERGY_DAMPING: 0.3,
      MANGPAI_ETA_DIMENSIONAL_CRUSH: 0.6,
      MANGPAI_ROOT_RESONANCE: 1.2,
      INTERDIMENSIONAL_SHIELD_ENABLE: 1.0,
      STEM_BRANCH_ROOT_RESONANCE_ENABLE: 1.0,
      STEM_BRANCH_VERTICAL_CRUSH_ENABLE: 1.0,
    },
    pluginWeights: { blindSchool: 0.8, wangshuai: 0.6 },
    setPluginWeights: vi.fn(),
    streamThemeChroma: {
      bgColor: "#1f2a1f",
      blindRatio: 0.57,
      wangshuaiRatio: 0.43,
      isConflictOverload: false,
      hasPolarityReversal: false,
    },
    rerunFinalVerdictWithWeights: vi.fn().mockResolvedValue(undefined),
    logicDrawerOpen: false,
    logicDrawerTitle: "Logic",
    logicDrawerFocus: "",
    logicDrawerDetails: [],
    logicDrawerTrace: null,
    setLogicDrawerOpen: vi.fn(),
    onSeedSubmit: vi.fn().mockResolvedValue({ ok: true, physics_tensor: null }),
    scheduleSilentInternalLoopOnApprovalSelection: vi.fn(),
    executeDecisionAndRefresh: vi.fn().mockResolvedValue(undefined),
    appendSystemAuditLog: vi.fn(),
    revokeConfirmedDecision: vi.fn().mockResolvedValue(undefined),
    openLogicDrawer: vi.fn(),
    openLogicDrawerByDeity: vi.fn(),
    onEvidenceItemClick: vi.fn(),
    showVerdictHistory: vi.fn(),
    applyCurrentSqlPatch: vi.fn().mockResolvedValue(undefined),
    runStressTest: vi.fn().mockResolvedValue(undefined),
    runGenderComparison: vi.fn().mockResolvedValue(undefined),
    t: (text: string) => text,
    inboxResetNonce: 0,
    sigShiftFlashKey: 0,
    isFinalized: false,
    finalizeVerdict: vi.fn().mockResolvedValue(true),
    runFinalVerdictSynthesis: vi.fn().mockResolvedValue(undefined),
    ...overrides,
  } as unknown as StreamBoardViewModel;
}

describe("stream-board viewModel", () => {
  it("derives audit and verdict display values", () => {
    const derived = buildStreamBoardViewDerivedState(createViewModel({
      deityEnergyAxes: { 比肩: { absolute_energy: 12.3 } },
      finalVerdictVersionId: "v2.0408",
      finalVerdictHistory: [
        { versionId: "v1", body: "one", changeLog: {}, logicalEvidence: [], createdAt: "2026-04-08T00:00:00.000Z" },
        { versionId: "v2", body: "two", changeLog: {}, logicalEvidence: [], createdAt: "2026-04-09T00:00:00.000Z" },
      ],
      finalWorkVector: { work_expectation: 1.25, backfire_risk: 0.42, released_energy: 0.6 },
      physicsAudit: {
        param_version_id: "abcdef123456",
        trace: {
          hard_route_logs: ["CF_FLOATING_DECAY=0.15"],
          climate_adjustment: { season: "spring" },
        },
      },
    }));

    expect(derived.hardRouteLogs).toEqual(["CF_FLOATING_DECAY=0.15"]);
    expect(derived.climateSeason).toBe("spring");
    expect(derived.energyPeakAbs).toBe(12.3);
    expect(derived.workExpectation).toBe(1.25);
    expect(derived.backfireRiskVal).toBe(0.42);
    expect(derived.releasedEnergyVal).toBe(0.6);
    expect(derived.summaryVersionLabel).toContain("v2.0408");
    expect(derived.summaryVersionLabel).toContain("abcdef12");
    expect(derived.hasVerdictHistory).toBe(true);
  });
});
