from __future__ import annotations

from v20.testing.schema import TestCommand, TestTier


TEST_TIERS: tuple[TestTier, ...] = (
    TestTier(
        name="smoke",
        purpose="Sub-second to few-second contract check for syntax, runtime spine, and ops profile health.",
        budget_seconds=8,
        default_for=("small_python_edit", "doc_adjacent_code_edit", "pre_commit_first_pass"),
        commands=(
            TestCommand(
                name="py_compile_v20",
                argv=("__PYTHON_BIN__", "-m", "py_compile", "__V20_PY_FILES__"),
                purpose="Compile V20 Python files only.",
            ),
            TestCommand(
                name="runtime_spine_smoke",
                argv=(
                    "__PYTHON_BIN__",
                    "-m",
                    "pytest",
                    "-q",
                    "v20/tests/test_v20_runtime.py::test_v20_runtime_builds_dynamic_decision_answer_plan",
                    "v20/tests/test_v20_ops.py::test_v20_ops_profiles_cover_macos_linux_postgres_and_redis",
                ),
                purpose="Check the deterministic Bazi measurement spine and runtime profiles.",
            ),
        ),
    ),
    TestTier(
        name="fast",
        purpose="Default V20 developer loop; representative local sentinels, no services, no network.",
        budget_seconds=90,
        default_for=("normal_code_edit", "feature_spine_edit", "ops_config_edit", "llm_contract_edit"),
        commands=(
            TestCommand(
                name="py_compile_v20",
                argv=("__PYTHON_BIN__", "-m", "py_compile", "__V20_PY_FILES__"),
                purpose="Compile V20 Python files only.",
            ),
            TestCommand(
                name="pytest_v20_fast_sentinels",
                argv=(
                    "__PYTHON_BIN__",
                    "-m",
                    "pytest",
                    "-q",
                    "v20/tests/test_v20_runtime.py::test_v20_runtime_builds_dynamic_decision_answer_plan",
                    "v20/tests/test_v20_mainline_status.py",
                    "v20/tests/test_v20_admin_training_tasks.py::test_v20_admin_training_task_registry_exposes_safe_tasks",
                    "v20/tests/test_v20_question_ranking.py::test_v20_question_source_graph_consumes_quality_signal_as_rerank_only_boost",
                    "v20/tests/test_v20_ui.py::test_v20_entry_and_route_assets_are_wired",
                    "v20/tests/test_v20_testing.py",
                ),
                purpose="Run the mainline runtime, admin training, question, UI, and test-system sentinels.",
            ),
        ),
    ),
    TestTier(
        name="core",
        purpose="Runtime, API, ops, storage, auth, and system status contracts.",
        budget_seconds=180,
        default_for=("runtime_edit", "server_edit", "ops_storage_edit", "auth_edit"),
        commands=(
            TestCommand(
                name="pytest_v20_core",
                argv=(
                    "__PYTHON_BIN__",
                    "-m",
                    "pytest",
                    "-q",
                    "v20/tests/test_v20_access.py",
                    "v20/tests/test_v20_auth_security.py",
                    "v20/tests/test_v20_calendar_profile_defaults.py",
                    "v20/tests/test_v20_element_features.py",
                    "v20/tests/test_v20_i18n_runtime.py",
                    "v20/tests/test_v20_logging.py",
                    "v20/tests/test_v20_local_jsonl_store.py",
                    "v20/tests/test_v20_ops.py",
                    "v20/tests/test_v20_postgres_pool.py",
                    "v20/tests/test_v20_redis.py",
                    "v20/tests/test_v20_runtime.py",
                    "v20/tests/test_v20_runtime_guardrails.py",
                    "v20/tests/test_v20_script_contract.py",
                    "v20/tests/test_v20_server.py",
                    "v20/tests/test_v20_service_unit.py",
                    "v20/tests/test_v20_storage.py",
                    "v20/tests/test_v20_structure_dynamics.py",
                    "v20/tests/test_v20_system_status.py",
                    "v20/tests/test_v20_testing.py",
                    "v20/tests/test_v20_useful_god.py",
                ),
                purpose="Run deterministic runtime and platform contracts.",
            ),
        ),
    ),
    TestTier(
        name="brain",
        purpose="Central brain, question chain, role view, prompt context, and orchestrator contracts.",
        budget_seconds=240,
        default_for=("orchestrator_edit", "question_flow_edit", "role_view_edit", "llm_context_edit"),
        commands=(
            TestCommand(
                name="pytest_v20_brain",
                argv=(
                    "__PYTHON_BIN__",
                    "-m",
                    "pytest",
                    "-q",
                    "v20/tests/test_v20_central_brain_architecture.py",
                    "v20/tests/test_v20_orchestrator.py",
                    "v20/tests/test_v20_orchestrator_brain_state.py",
                    "v20/tests/test_v20_orchestrator_evidence.py",
                    "v20/tests/test_v20_orchestrator_memory.py",
                    "v20/tests/test_v20_orchestrator_memory_record.py",
                    "v20/tests/test_v20_orchestrator_policy_candidates.py",
                    "v20/tests/test_v20_orchestrator_policy_observability.py",
                    "v20/tests/test_v20_orchestrator_policy_observability_record.py",
                    "v20/tests/test_v20_orchestrator_policy_versioning.py",
                    "v20/tests/test_v20_orchestrator_runtime_policy.py",
                    "v20/tests/test_v20_question_dag.py",
                    "v20/tests/test_v20_question_dag_coherence.py",
                    "v20/tests/test_v20_question_dag_policy_promotion.py",
                    "v20/tests/test_v20_question_dag_policy_replay.py",
                    "v20/tests/test_v20_question_mainline_focus.py",
                    "v20/tests/test_v20_question_ranking.py",
                    "v20/tests/test_v20_question_review.py",
                    "v20/tests/test_v20_role_question_click.py",
                    "v20/tests/test_v20_role_question_narrative_prompt_framework.py",
                    "v20/tests/test_v20_role_view_completion.py",
                ),
                purpose="Run the central orchestration and role-aware question contracts.",
            ),
        ),
    ),
    TestTier(
        name="training",
        purpose="Direct-apply training, runtime pointers, knowledge/rule growth, synthetic data, and corpus previews.",
        budget_seconds=360,
        default_for=("training_edit", "knowledge_rule_edit", "synthetic_case_edit", "runtime_pointer_edit"),
        commands=(
            TestCommand(
                name="pytest_v20_training",
                argv=(
                    "__PYTHON_BIN__",
                    "-m",
                    "pytest",
                    "-q",
                    "v20/tests/test_v20_admin_config.py",
                    "v20/tests/test_v20_admin_training_tasks.py",
                    "v20/tests/test_v20_answer_governance_training.py",
                    "v20/tests/test_v20_answer_safety_evaluator.py",
                    "v20/tests/test_v20_confidence_calibration.py",
                    "v20/tests/test_v20_corpus_runtime_pointer.py",
                    "v20/tests/test_v20_dynamic_decision_training.py",
                    "v20/tests/test_v20_feedback_learning.py",
                    "v20/tests/test_v20_intelligence_generation.py",
                    "v20/tests/test_v20_knowledge_completeness_audit.py",
                    "v20/tests/test_v20_knowledge_docs.py",
                    "v20/tests/test_v20_knowledge_ranking.py",
                    "v20/tests/test_v20_knowledge_review_and_rules.py",
                    "v20/tests/test_v20_knowledge_rule_growth.py",
                    "v20/tests/test_v20_knowledge_rule_orchestrator.py",
                    "v20/tests/test_v20_knowledge_runtime_consumer.py",
                    "v20/tests/test_v20_knowledge_runtime_pointer.py",
                    "v20/tests/test_v20_latent_event_calibration.py",
                    "v20/tests/test_v20_learning_corpus_artifacts.py",
                    "v20/tests/test_v20_learning_corpus.py",
                    "v20/tests/test_v20_orchestrator_memory_training.py",
                    "v20/tests/test_v20_portrait_calibration.py",
                    "v20/tests/test_v20_portrait_runtime_consumer.py",
                    "v20/tests/test_v20_portrait_runtime_pointer.py",
                    "v20/tests/test_v20_practitioner_calibration_training.py",
                    "v20/tests/test_v20_question_dag_training.py",
                    "v20/tests/test_v20_question_review_training.py",
                    "v20/tests/test_v20_question_runtime_pointer.py",
                    "v20/tests/test_v20_question_source_training.py",
                    "v20/tests/test_v20_release_smoke.py",
                    "v20/tests/test_v20_role_interaction_training.py",
                    "v20/tests/test_v20_role_question_click_training.py",
                    "v20/tests/test_v20_role_view_policy_calibration.py",
                    "v20/tests/test_v20_role_view_policy_candidates.py",
                    "v20/tests/test_v20_role_view_policy_promotion.py",
                    "v20/tests/test_v20_role_view_policy_replay.py",
                    "v20/tests/test_v20_role_view_runtime_pointer.py",
                    "v20/tests/test_v20_rule_portrait_batch.py",
                    "v20/tests/test_v20_rule_runtime_consumer.py",
                    "v20/tests/test_v20_rule_runtime_pointer.py",
                    "v20/tests/test_v20_runtime_consumption_audit.py",
                    "v20/tests/test_v20_runtime_question_source_recording.py",
                    "v20/tests/test_v20_synthetic_bazi_case_schema.py",
                    "v20/tests/test_v20_synthetic_bazi_evaluator.py",
                    "v20/tests/test_v20_synthetic_bazi_replay.py",
                    "v20/tests/test_v20_synthetic_case_suite.py",
                ),
                purpose="Run all local training and runtime-pointer contracts without service opt-in.",
            ),
        ),
    ),
    TestTier(
        name="ui",
        purpose="Static Admin and workbench UI contracts.",
        budget_seconds=45,
        default_for=("admin_ui_edit", "workbench_ui_edit", "frontend_static_edit"),
        commands=(
            TestCommand(
                name="pytest_v20_ui",
                argv=("__PYTHON_BIN__", "-m", "pytest", "-q", "v20/tests/test_v20_ui.py"),
                purpose="Run static UI shell and wiring tests.",
            ),
        ),
    ),
    TestTier(
        name="targeted",
        purpose="Run selected V20 tests by pytest expression or explicit paths.",
        budget_seconds=45,
        default_for=("focused_bugfix", "module_specific_refactor", "mainline_target_check"),
        commands=(
            TestCommand(
                name="pytest_v20_targeted",
                argv=("__PYTHON_BIN__", "-m", "pytest", "-q", "v20/tests", "__PYTEST_ARGS__"),
                purpose="Run explicit pytest selectors without expanding to slow suites.",
            ),
        ),
    ),
    TestTier(
        name="full",
        purpose="All V20 local tests. Use this as the closeout gate after split tiers pass.",
        budget_seconds=900,
        default_for=("phase_closeout", "cross_module_refactor", "before_commit"),
        commands=(
            TestCommand(
                name="py_compile_v20",
                argv=("__PYTHON_BIN__", "-m", "py_compile", "__V20_PY_FILES__"),
                purpose="Compile V20 Python files only.",
            ),
            TestCommand(
                name="pytest_v20_all_local",
                argv=("__PYTHON_BIN__", "-m", "pytest", "-q", "v20/tests"),
                purpose="Run all local V20 tests.",
            ),
            TestCommand(
                name="git_diff_check",
                argv=("git", "diff", "--check"),
                purpose="Catch whitespace and conflict marker issues.",
            ),
        ),
    ),
    TestTier(
        name="services",
        purpose="Explicit opt-in checks for Postgres, Redis, Linux/macOS sync, and server health.",
        budget_seconds=180,
        default_for=("database_migration", "redis_queue_change", "deploy_or_sync_change"),
        commands=(
            TestCommand(
                name="pytest_v20_services",
                argv=("__PYTHON_BIN__", "-m", "pytest", "-q", "v20/tests", "-k", "service or postgres or redis or sync"),
                purpose="Service-dependent tests; skipped unless the env gate is set.",
                opt_in_env="RUN_V20_SERVICE_TESTS",
            ),
        ),
        guardrails=(
            "TEST_TIER_IS_EXPLICIT",
            "SERVICE_TESTS_REQUIRE_OPT_IN",
            "NO_SECRET_VALUES_IN_TEST_OUTPUT",
            "NO_PRODUCTION_DATA_MUTATION",
        ),
    ),
    TestTier(
        name="corpus",
        purpose="Explicit opt-in synthetic corpus and full 518K coverage jobs.",
        budget_seconds=3600,
        default_for=("corpus_precompute", "learning_dataset_generation", "coverage_report"),
        commands=(
            TestCommand(
                name="pytest_v20_corpus",
                argv=("__PYTHON_BIN__", "-m", "pytest", "-q", "v20/tests", "-k", "corpus or coverage or full_518k"),
                purpose="Long-running corpus tests; never part of default loops.",
                opt_in_env="RUN_V20_CORPUS_TESTS",
            ),
        ),
        guardrails=(
            "TEST_TIER_IS_EXPLICIT",
            "CORPUS_TESTS_REQUIRE_OPT_IN",
            "LONG_JOBS_WRITE_RUN_LEDGER",
            "NO_RUNTIME_RULE_MUTATION",
        ),
    ),
)


def get_tier(name: str) -> TestTier:
    for tier in TEST_TIERS:
        if tier.name == name:
            return tier
    raise KeyError(name)


def test_tier_manifest() -> dict[str, object]:
    return {
        "version": "v20.test_tier_manifest.v1",
        "tiers": [tier.to_dict() for tier in TEST_TIERS],
        "default_tier": "fast",
        "fast_budget_seconds": get_tier("fast").budget_seconds,
        "guardrails": [
            "FAST_TESTS_ARE_SENTINELS_NOT_FULL_TESTS",
            "DOMAIN_TIERS_SPLIT_CORE_BRAIN_TRAINING_UI",
            "SERVICE_AND_CORPUS_TESTS_REQUIRE_OPT_IN",
            "MARKDOWN_DOCS_MIRROR_EXECUTABLE_MANIFEST",
        ],
    }
