from __future__ import annotations

from typing import Protocol

from core.contracts import BirthInputCanonical


class ProductStoreError(ValueError):
    pass


class ProductStore(Protocol):
    persistent: bool
    storage_name: str

    def register_account(self, *, email: str, password: str, display_name: str, role: str) -> dict[str, object]: ...
    def authenticate(self, *, email: str, password: str) -> dict[str, object] | None: ...
    def ensure_admin_account(self, *, email: str, password: str, display_name: str) -> dict[str, object]: ...
    def create_session(self, *, user_id: str) -> str: ...
    def account_for_token(self, token: str) -> dict[str, object] | None: ...
    def revoke_session(self, token: str) -> None: ...
    def save_profile(self, *, user_id: str, birth_input: BirthInputCanonical, profile_id: str | None = None) -> dict[str, object]: ...
    def list_profiles(self, *, user_id: str) -> list[dict[str, object]]: ...
    def get_profile(self, *, user_id: str, profile_id: str) -> dict[str, object] | None: ...
    def delete_profile(self, *, user_id: str, profile_id: str) -> bool: ...
