from __future__ import annotations

from core.timing.schemas import (
    TimingChange,
    TimingLayer,
    TimingModelCandidate,
    TimingModelFamily,
    TimingRelation,
    TimingSimulatorOutput,
)


def build_timing_model_candidates_v1() -> list[TimingModelCandidate]:
    return [
        _candidate(
            "timing.luck.second_month_command.v1",
            TimingLayer.LUCK,
            TimingModelFamily.SECOND_MONTH_COMMAND,
            0.42,
            changes=[TimingChange.NODE_ENERGY, TimingChange.EDGE_STRENGTH, TimingChange.PATH_ACTIVATION, TimingChange.MECHANISM_RANKING],
            relation_to_natal=[TimingRelation.OVERLAY, TimingRelation.SUPPRESS, TimingRelation.AMPLIFY],
            outputs=[TimingSimulatorOutput.STATE_DELTA, TimingSimulatorOutput.STRENGTHENED_NODES, TimingSimulatorOutput.WEAKENED_NODES, TimingSimulatorOutput.MECHANISM_SHIFT],
            risks=["may overpower natal structure and recreate month-command bias"],
            source="docs/research/timing/F001_WHAT_IS_LUCK.md#second-month-command-model",
        ),
        _candidate(
            "timing.luck.long_term_field.v1",
            TimingLayer.LUCK,
            TimingModelFamily.LONG_TERM_FIELD,
            0.62,
            changes=[TimingChange.NODE_ENERGY, TimingChange.PATH_COST, TimingChange.TOPIC_TIMING],
            relation_to_natal=[TimingRelation.OVERLAY, TimingRelation.AMPLIFY, TimingRelation.NEUTRALIZE, TimingRelation.SUPPRESS],
            outputs=[TimingSimulatorOutput.FIELD_DELTA, TimingSimulatorOutput.STATE_DELTA, TimingSimulatorOutput.MECHANISM_SHIFT],
            risks=["may under-detect decade-level reroutes if used alone"],
            source="docs/research/timing/F001_WHAT_IS_LUCK.md#long-term-field-model",
        ),
        _candidate(
            "timing.luck.perturbation_source.v1",
            TimingLayer.LUCK,
            TimingModelFamily.PERTURBATION_SOURCE,
            0.68,
            changes=[TimingChange.PATH_ACTIVATION, TimingChange.PATH_COST, TimingChange.MECHANISM_RANKING],
            relation_to_natal=[TimingRelation.REROUTE, TimingRelation.BREAK, TimingRelation.COMPLETE],
            outputs=[TimingSimulatorOutput.STATE_DELTA, TimingSimulatorOutput.REROUTED_FLOW, TimingSimulatorOutput.WEAKENED_NODES, TimingSimulatorOutput.ACTIVATED_PATHS],
            risks=["requires synthetic reroute fixtures before runtime promotion"],
            source="docs/research/timing/F001_WHAT_IS_LUCK.md#perturbation-source-model",
        ),
        _candidate(
            "timing.luck.stage_dominant_variable.v1",
            TimingLayer.LUCK,
            TimingModelFamily.STAGE_DOMINANT_VARIABLE,
            0.58,
            changes=[TimingChange.TOPIC_PRIORITY, TimingChange.MECHANISM_RANKING, TimingChange.TOPIC_TIMING],
            relation_to_natal=[TimingRelation.OVERLAY, TimingRelation.FOCUS],
            outputs=[TimingSimulatorOutput.TOPIC_TIMING_SIGNAL, TimingSimulatorOutput.MECHANISM_SHIFT],
            risks=["can become topic-label bias without path evidence"],
            source="docs/research/timing/F001_WHAT_IS_LUCK.md#stage-dominant-variable-model",
        ),
        _candidate(
            "timing.year.trigger.v1",
            TimingLayer.YEAR,
            TimingModelFamily.TRIGGER,
            0.55,
            changes=[TimingChange.PATH_ACTIVATION, TimingChange.TOPIC_TIMING],
            relation_to_natal=[TimingRelation.ACTIVATE, TimingRelation.TRIGGER],
            outputs=[TimingSimulatorOutput.ACTIVATED_PATHS, TimingSimulatorOutput.TOPIC_TIMING_SIGNAL, TimingSimulatorOutput.EVENT_WINDOW_SCORE],
            risks=["may understate years that complete missing structures"],
            source="docs/research/timing/F002_WHAT_IS_YEAR.md#trigger-model",
        ),
        _candidate(
            "timing.year.short_term_field.v1",
            TimingLayer.YEAR,
            TimingModelFamily.SHORT_TERM_FIELD,
            0.52,
            changes=[TimingChange.NODE_ENERGY, TimingChange.EDGE_STRENGTH, TimingChange.PATH_COST],
            relation_to_natal=[TimingRelation.OVERLAY, TimingRelation.SUPPRESS, TimingRelation.AMPLIFY, TimingRelation.NEUTRALIZE],
            outputs=[TimingSimulatorOutput.STATE_DELTA, TimingSimulatorOutput.STRENGTHENED_NODES, TimingSimulatorOutput.WEAKENED_NODES, TimingSimulatorOutput.MECHANISM_SHIFT],
            risks=["can overwrite decade field if not traced against luck layer"],
            source="docs/research/timing/F002_WHAT_IS_YEAR.md#short-term-field-model",
        ),
        _candidate(
            "timing.year.activation_event.v1",
            TimingLayer.YEAR,
            TimingModelFamily.ACTIVATION_EVENT,
            0.66,
            changes=[TimingChange.PATH_ACTIVATION, TimingChange.TOPIC_TIMING, TimingChange.MECHANISM_RANKING],
            relation_to_natal=[TimingRelation.ACTIVATE, TimingRelation.FOCUS],
            relation_to_other=[TimingRelation.TRIGGER, TimingRelation.AMPLIFY, TimingRelation.CONFLICT],
            outputs=[TimingSimulatorOutput.ACTIVATED_PATHS, TimingSimulatorOutput.TOPIC_TIMING_SIGNAL, TimingSimulatorOutput.EVENT_PRESSURE_SCORE, TimingSimulatorOutput.MECHANISM_SHIFT],
            risks=["needs topic gate validation"],
            source="docs/research/timing/F002_WHAT_IS_YEAR.md#activation-event-model",
        ),
        _candidate(
            "timing.year.structure_completion.v1",
            TimingLayer.YEAR,
            TimingModelFamily.STRUCTURE_COMPLETION,
            0.60,
            changes=[TimingChange.PATH_ACTIVATION, TimingChange.EDGE_STRENGTH],
            relation_to_natal=[TimingRelation.COMPLETE, TimingRelation.BREAK, TimingRelation.ACTIVATE],
            outputs=[TimingSimulatorOutput.COMPLETED_PATHS, TimingSimulatorOutput.BROKEN_PATHS, TimingSimulatorOutput.MECHANISM_SHIFT],
            risks=["must not rewrite natal original completeness"],
            source="docs/research/timing/F002_WHAT_IS_YEAR.md#structure-completion-model",
        ),
        _candidate(
            "timing.month.fine_grained_trigger.v1",
            TimingLayer.MONTH,
            TimingModelFamily.FINE_GRAINED_TRIGGER,
            0.55,
            changes=[TimingChange.EVENT_WINDOW, TimingChange.PATH_ACTIVATION, TimingChange.TOPIC_TIMING],
            relation_to_natal=[TimingRelation.ACTIVATE, TimingRelation.FOCUS],
            relation_to_other=[TimingRelation.TRIGGER, TimingRelation.FOCUS],
            outputs=[TimingSimulatorOutput.EVENT_WINDOW_SCORE, TimingSimulatorOutput.TIMING_PRECISION_SCORE, TimingSimulatorOutput.ACTIVATED_PATHS],
            risks=["false precision without annual support"],
            source="docs/research/timing/F003_WHAT_IS_MONTH.md#fine-grained-trigger-model",
        ),
        _candidate(
            "timing.month.short_pulse_field.v1",
            TimingLayer.MONTH,
            TimingModelFamily.SHORT_PULSE_FIELD,
            0.44,
            changes=[TimingChange.NODE_ENERGY, TimingChange.EDGE_STRENGTH, TimingChange.PATH_COST],
            relation_to_natal=[TimingRelation.OVERLAY, TimingRelation.AMPLIFY, TimingRelation.NEUTRALIZE],
            outputs=[TimingSimulatorOutput.STATE_DELTA, TimingSimulatorOutput.STRENGTHENED_NODES, TimingSimulatorOutput.WEAKENED_NODES],
            risks=["highest false precision risk among month models"],
            source="docs/research/timing/F003_WHAT_IS_MONTH.md#short-pulse-field-model",
        ),
        _candidate(
            "timing.month.event_window.v1",
            TimingLayer.MONTH,
            TimingModelFamily.EVENT_WINDOW,
            0.61,
            changes=[TimingChange.EVENT_WINDOW, TimingChange.TOPIC_TIMING],
            relation_to_natal=[TimingRelation.FOCUS, TimingRelation.ACTIVATE],
            relation_to_other=[TimingRelation.FOCUS, TimingRelation.TRIGGER],
            outputs=[TimingSimulatorOutput.EVENT_WINDOW_SCORE, TimingSimulatorOutput.TIMING_PRECISION_SCORE],
            risks=["does not create event alone"],
            source="docs/research/timing/F003_WHAT_IS_MONTH.md#event-window-model",
        ),
        _candidate(
            "timing.month.micro_structure_completion.v1",
            TimingLayer.MONTH,
            TimingModelFamily.MICRO_STRUCTURE_COMPLETION,
            0.50,
            changes=[TimingChange.PATH_ACTIVATION, TimingChange.EDGE_STRENGTH, TimingChange.EVENT_WINDOW],
            relation_to_natal=[TimingRelation.COMPLETE, TimingRelation.BREAK, TimingRelation.TRIGGER],
            relation_to_other=[TimingRelation.AMPLIFY, TimingRelation.CONFLICT],
            outputs=[TimingSimulatorOutput.COMPLETED_PATHS, TimingSimulatorOutput.BROKEN_PATHS, TimingSimulatorOutput.EVENT_WINDOW_SCORE],
            risks=["should remain low confidence without luck/year support"],
            source="docs/research/timing/F003_WHAT_IS_MONTH.md#micro-structure-completion-model",
        ),
    ]


def _candidate(
    model_id: str,
    timing_layer: TimingLayer,
    model_family: TimingModelFamily,
    confidence: float,
    *,
    changes: list[TimingChange],
    relation_to_natal: list[TimingRelation],
    outputs: list[TimingSimulatorOutput],
    risks: list[str],
    source: str,
    relation_to_other: list[TimingRelation] | None = None,
) -> TimingModelCandidate:
    return TimingModelCandidate(
        model_id=model_id,
        timing_layer=timing_layer,
        model_family=model_family,
        current_confidence=confidence,
        changes=changes,
        does_not_change=[
            "natal_immutable_facts",
            "original_structure_existence",
            "birth_input",
        ],
        relation_to_natal=relation_to_natal,
        relation_to_other_timing_layers=relation_to_other or [TimingRelation.COOPERATE, TimingRelation.CONFLICT, TimingRelation.AMPLIFY, TimingRelation.NEUTRALIZE],
        simulator_outputs=outputs,
        validation_plan=[
            "synthetic_cases",
            "counter_examples",
            "state_delta_diff",
            "must_not_rewrite_natal_structure",
        ],
        risk_notes=risks,
        source_refs=[source],
    )

