from __future__ import annotations

from v20.knowledge.schema import KnowledgeUnit


def default_knowledge_units() -> tuple[KnowledgeUnit, ...]:
    return (
        KnowledgeUnit(
            "v20.core.strength_boundary",
            "Strength evidence boundary",
            "strength",
            "Day-master capacity should be explained through support, pressure, and uncertainty evidence.",
            "Use support score, pressure score, and source-layer evidence before naming any capacity tendency.",
            "Do not hard-judge strong or weak in Phase 1.",
            source_refs=("docs/v20.prestart.strength",),
            feature_hooks=("feature.strength",),
            question_hooks=("q_strength_assessment",),
        ),
        KnowledgeUnit(
            "v20.core.branch_relation_boundary",
            "Branch relation boundary",
            "branch",
            "Branch relations identify visible structural interactions and must be layer-aware.",
            "Name the relation type and branches; explain that relation names alone do not imply good or bad outcomes.",
            "Do not infer fortune from clash, harmony, punishment, harm, break, three harmony, or three meeting.",
            source_refs=("docs/v20.prestart.branch",),
            feature_hooks=("feature.branch",),
            question_hooks=("q_branch_relation_detail",),
        ),
        KnowledgeUnit(
            "v20.core.time_layer_boundary",
            "Time layer boundary",
            "time",
            "Time layers can describe explicit luck or flow pillar interaction with the natal chart.",
            "Use only supplied time pillars, time ten-god labels, and time-to-natal relation hits as evidence.",
            "Do not infer exact dates, fixed events, guaranteed timing, or calendar facts that were not supplied.",
            source_refs=("docs/v20.prestart.time_layer",),
            feature_hooks=("feature.time",),
            question_hooks=("q_time_layer_context", "q_time_relation_triggers"),
            retrieval_tags=("time_layer", "flow_year", "luck"),
        ),
        KnowledgeUnit(
            "v20.core.wealth_material_boundary",
            "Wealth material boundary",
            "wealth",
            "Wealth ten-god material can describe structural availability, source layer, and constraints.",
            "Use visible/hidden wealth ten-god evidence and relation context as structural material only.",
            "Do not predict wealth events, amounts, gains, losses, or timing.",
            source_refs=("docs/v20.prestart.wealth",),
            feature_hooks=("feature.wealth",),
            question_hooks=("q_income_stability",),
        ),
        KnowledgeUnit(
            "v20.applied.career_projection_boundary",
            "Career projection boundary",
            "career",
            "Career readings are applied-domain projections over ten-god, pattern, strength, and branch features.",
            "Use role structure, authority-output relation, and constraint/support paths only when source features are present.",
            "Do not predict promotion, job loss, salary, title, or guaranteed workplace events.",
            source_refs=("docs/v20.prestart.career",),
            feature_hooks=("feature.ten_god", "feature.pattern", "feature.strength", "feature.branch"),
            question_hooks=("q_career_structure",),
            retrieval_tags=("applied_domain", "career", "projection"),
        ),
        KnowledgeUnit(
            "v20.applied.relationship_projection_boundary",
            "Relationship projection boundary",
            "relationship",
            "Relationship readings are applied-domain projections over interaction and ten-god structure.",
            "Use visible/hidden relation material and branch interaction as context for relationship questions.",
            "Do not predict marriage, divorce, partner identity, private partner facts, or guaranteed relationship events.",
            source_refs=("docs/v20.prestart.relationship",),
            feature_hooks=("feature.ten_god", "feature.branch", "feature.strength"),
            question_hooks=("q_relationship_structure",),
            retrieval_tags=("applied_domain", "relationship", "projection"),
        ),
        KnowledgeUnit(
            "v20.applied.health_projection_boundary",
            "Health projection boundary",
            "health",
            "Health-adjacent readings are limited to five-element balance and stress-boundary context.",
            "Use strength, branch, and pattern features only to discuss structural balance boundaries.",
            "Do not diagnose, predict disease, recommend treatment, or replace medical advice.",
            source_refs=("docs/v20.prestart.health",),
            feature_hooks=("feature.strength", "feature.branch", "feature.pattern"),
            question_hooks=("q_health_balance_boundary",),
            retrieval_tags=("applied_domain", "health", "projection"),
        ),
        KnowledgeUnit(
            "v20.core.useful_god_gate",
            "Useful-god evidence gate",
            "useful_god",
            "Useful-god discussion requires candidate paths and explicit evidence gates.",
            "Explain whether support, output, constraint, or unresolved evidence paths are present.",
            "Do not state fixed favorable or unfavorable gods in Phase 1.",
            source_refs=("docs/v20.prestart.useful_god",),
            feature_hooks=("feature.useful_god",),
            question_hooks=("q_useful_god_candidates", "q_useful_god_evidence_gaps"),
            retrieval_tags=("candidate_path", "evidence_gate", "arbitration"),
        ),
        KnowledgeUnit(
            "v20.core.useful_god_candidate_paths",
            "Useful-god candidate paths",
            "useful_god",
            "Candidate paths are derived from capacity, element distribution, and structural pressure only.",
            "Name candidate path types such as support, release, channel, constraint, or evidence gap.",
            "Do not convert a candidate path into fixed favorable or unfavorable gods without validation.",
            source_refs=("docs/v20.useful_god_candidates",),
            feature_hooks=("feature.useful_god.candidate_paths",),
            question_hooks=("q_useful_god_candidates", "q_useful_god_evidence_gaps"),
            retrieval_tags=("candidate_path", "element_distribution", "strength_capacity"),
        ),
        KnowledgeUnit(
            "v20.core.ten_god_boundary",
            "Ten-god interpretation boundary",
            "ten_god",
            "Ten-god labels describe relation type and source layer before any applied domain reading.",
            "Name whether the relation is visible or hidden, then keep it as structural material unless a verified feature connects it to a question.",
            "Do not convert ten-god labels directly into personality, career, money, relationship, or health conclusions.",
            source_refs=("docs/v20.prestart.ten_god",),
            feature_hooks=("feature.ten_god",),
            question_hooks=("q_ten_god_focus", "q_hidden_stem_role", "q_ten_god_metadata"),
            retrieval_tags=("visible", "hidden", "relation_label"),
        ),
        KnowledgeUnit(
            "v20.core.element_distribution_boundary",
            "Five-element distribution boundary",
            "element",
            "Five-element distribution describes structural balance, concentration, and gaps before applied readings.",
            "Use visible stems and hidden-stem weights to name distribution tendencies and evidence boundaries.",
            "Do not convert element imbalance directly into health diagnosis, fixed fortune, or guaranteed events.",
            source_refs=("docs/v20.prestart.element_distribution",),
            feature_hooks=("feature.element",),
            question_hooks=("q_element_balance", "q_element_support_pressure"),
            retrieval_tags=("five_element", "balance", "foundation"),
        ),
        KnowledgeUnit(
            "v20.core.pattern_review_boundary",
            "Pattern review boundary",
            "pattern",
            "Pattern material is a review index that needs rule-path and evidence arbitration.",
            "Use pattern evidence to open a structured review path, not to name a final pattern prematurely.",
            "Do not declare a fixed pattern, grade, or outcome from a preliminary index.",
            source_refs=("docs/v20.prestart.pattern",),
            feature_hooks=("feature.pattern",),
            question_hooks=("q_pattern_structure",),
            retrieval_tags=("review_index", "arbitration", "rule_path"),
        ),
    )
