import type { Lang } from "@/types/bazi";
import { resolveQiazhiApiBase } from "@/lib/qiazhiApiBase";

export const API_BASE = resolveQiazhiApiBase();
export const ADMIN_TOKEN = process.env.NEXT_PUBLIC_QIAZHI_ADMIN_TOKEN ?? "";
export const adminHeaders: Record<string, string> = ADMIN_TOKEN ? { "X-Admin-Token": ADMIN_TOKEN } : {};
export const fetcher = (url: string) => fetch(url).then((r) => r.json());
export const VERDICT_TIMEOUT_MS = 45000;
/** 设为 1 时终判走 `/api/v1/final-verdict/stream`（NDJSON），失败则回退普通 JSON POST */
export const FINAL_VERDICT_TRY_NDJSON_STREAM =
  typeof process !== "undefined" &&
  String(process.env.NEXT_PUBLIC_QIAZHI_FINAL_VERDICT_NDJSON || "").toLowerCase() === "1";
/** 设为 0 时静默环回退 `POST /v1/orchestrator/internal-loop` JSON；默认走 SSE 全链路 */
export const ORCHESTRATOR_USE_SSE_STREAM =
  typeof process !== "undefined" &&
  String(process.env.NEXT_PUBLIC_QIAZHI_ORCHESTRATOR_SSE || "1").toLowerCase() !== "0";
/** 终审签发：|logic_diff.abs_delta| 低于此值且 Inbox 无剩余项时主按钮进入「签发终审」态（纯 UI 门闩，非物理常数） */
export const FINAL_VERDICT_ABS_DELTA_THRESHOLD = 30;
export const TRANSLATION_DEBOUNCE_MS = 500;
export const TRANSLATION_CACHE_MAX = 200;

export const I18N: Record<Lang, { title: string; subtitle: string }> = {
  ZH: { title: "掐指一算", subtitle: "意志重塑现实 · 对话即推演，卡片即逻辑" },
  EN: { title: "Qiazhi-Bazi", subtitle: "Will reshapes the narrative · dialogue as inference, cards as logic." },
  KO: { title: "Qiazhi-Bazi", subtitle: "의지가 서사를 재구성 · 대화는 추론, 카드는 논리." },
};

import { STATIC_I18N } from "@/constants/locales";

export { STATIC_I18N };

/** 不经过翻译队列的静态表查找（Shell、桥接页等轻量场景）。 */
export function staticT(lang: Lang, zhKey: string): string {
  if (lang === "ZH") return zhKey;
  return STATIC_I18N[lang]?.[zhKey] ?? zhKey;
}

export const PRELOAD_UI_TEXTS = [
  "掐指一算",
  "掐指再算",
  "下次再算",
  "意志正在重塑现实…",
  "意志注塑中…",
  "物理骨架与终审判词并行展示（不等待 LLM 正文）",
  "引擎直出",
  "物理层 · 事实",
  "语义层 · 解释",
  "流式叙事；与上方物理事实可对照，不替代引擎结论",
  "逻辑检察院 · 实时监控中",
  "审计备忘",
  "物理审计 LLM 定性（终审前即可见）",
  "物理审计",
  "点击条目展开本轮完整 diagnosis / 模型输出",
  "查看逻辑指纹",
  "收起逻辑指纹",
  "指纹已写入 DOM 注释，亦可在展开区复制用于审计。",
  "意志注塑成功：{deity} 能量 {sign}{pct}%",
  "逻辑演化轴",
  "逻辑演化轴：尚无审计或意志记录；勾选 Inbox 或触发静默环后将在此堆叠。",
  "逻辑脉冲回放",
  "关闭",
  "脉冲回放：环形缓冲未命中，以下为最近可得快照或空态。",
  "能量图快照",
  "引擎骨架快照",
  "无十神能量条可展示",
  "无 verdict_skeleton",
  "该轮次模型回复摘录",
  "已确认意志项",
  "撤销此条",
  "✨ 物理已收敛：终审整合已执行。你可无限次「掐指再算」；改参或改运后将重新进入初算节拍。",
  "逻辑已收敛，当前参数下物理态保持稳定。",
  "计算完成，已更新逻辑视图",
  "✨ 物理逻辑已达收敛稳态，当前参数配置已为最优解。",
  "对话即推演，卡片即逻辑",
  "流式对话与决策卡片",
  "批量勾选后，一次性执行全局裁决。",
  "暂无可裁决冲合项。",
  "已认同",
  "执行中...",
  "执行全局裁决",
  "已选",
  "项",
  "等待确认后生成阶段结论…",
  "动态命盘卡片",
  "点击地支查看辩证",
  "命盘卡片将在输入后出现。",
  "大运",
  "流年",
  "暂无冲突点。",
  "Audit Sidebar",
  "权力三角：Arbiter / Core / Auditor",
  "DB(本地)",
  "LLM(0.10)",
  "等待交互步骤…",
  "Step",
  "The Seed",
  "输入生日后，系统将进入流式推演。",
  "公历",
  "农历",
  "日期时刻",
  "年",
  "月",
  "日",
  "时",
  "分",
  "推演中…",
  "第一波：物理排盘中…",
  "第二波：特征扫描中…",
  "扫描完毕，发现",
  "处冲合特征，正在生成首条判词…",
  "全局裁决完成，终极判词已生成。",
  "已确认",
  "，正在执行全局裁决…",
  "✅ 终极判词：",
  "[KO] 结果提取失败。",
  "实验室",
  "黑匣子",
  "机房",
  "Layer 1 Fully Aligned",
  "左",
  "右",
  "正在重组因果现场...",
  "视觉仪表盘",
  "指令舱",
  "黑匣子（L1 审计）→",
  "跳转插件碰撞审计",
  "第一层完全对齐",
  "滑动主区域切换视图，或点右下角浮动按钮",
  "视觉场 · 全局熵",
  "（沉浸式看盘）",
  "当前已有排盘结果，可随时修改生辰重算。",
  "尚未排盘：请先录入生辰八字。",
  "修改生辰",
  "录入生辰（地法）",
  "命盘仪表盘",
  "生辰八字 · 地法（The Seed）",
  "收起表单",
  "展开表单",
  "掐指一算后在此显示：四柱 / 大运 / 流年",
  "测算八字",
  "预览",
  "流年（参考年）",
  "环境方位",
  "预览加载失败",
  "选择出生日期",
  "选定开始测算",
  "返回重新测算",
  "命盘 · 六柱与流年",
  "预览更新中…",
  "参考年",
  "已随测算写入命盘",
  "流年参考年说明",
  "表单已收起。点击「展开表单」可再次录入/修改公历、农历、时刻与性别并重新排盘。",
  "提交 IDs：",
  "做功路径摘要",
  "期望",
  "反噬风险",
  "释放能",
  "暂无批注内容。",
  "已签发 (Issued)",
  "主权占优",
  "终审已签发 · 公文压底",
  "乾造（男）",
  "坤造（女）",
  "东",
  "南",
  "西",
  "北",
  "中",
  "地理场演示：南强化火、北强化水（需重新测算）",
  "检测到能量高度淤积（Abs: {abs}），做功路径受阻。",
  "已开启逻辑透深。",
  "逻辑坍缩中...",
  "物理排盘：开启因果",
  "[因果确认：执行裁决]",
  "语义重构：重新裁决",
  "因果锚点已固化",
  "设置当前为基线",
  "暂无可执行决策项。",
  "勾选决策项后可在统一动作条触发语义裁决。",
  "核心看板（Strategic HUD + 盲派镜像）",
  "收起",
  "展开",
  "语义权重滑杆（Plugin Weights）",
  "盲派 ",
  "旺衰 ",
  "应用权重并重算",
  "结果总览（Result Summary）",
  "查看历史版本",
  "变更差分（Physics / Consensus / Text）",
  "物理场变动",
  "共识固化",
  "判词修正",
  "无",
  "- 无",
  "收起证据快照",
  "展开证据快照",
  "隐藏模块",
  "显示模块",
  "点击下钻证据",
  "盲派做功链路图（L2）",
  "触发:",
  "释放:",
  "损耗:",
  "净值:",
  "[解锁失败/链路断裂]",
  "拓扑图（Topology）",
  "格局态射仪表盘",
  "正格倾向:",
  "从格倾向:",
  "跃迁倾向:",
  "L2 格局终审结果",
  "willProxy.title",
  "willProxy.anchor.stability",
  "willProxy.anchor.wealth",
  "willProxy.anchor.fame",
  "willAudit.sectionTitle",
  "will.narrative.seek_wealth",
  "will.narrative.seek_stability",
  "will.narrative.seek_fame",
  "willAudit.sys.unset",
  "willAudit.sys.headline",
  "willAudit.sys.detailWealth",
  "willAudit.sys.detailStability",
  "willAudit.sys.detailFame",
  "topology.willReport.title",
  "topology.willReport.node",
  "topology.willReport.post",
  "topology.willReport.pre",
  "topology.willReport.factor",
  "topology.willReport.formula",
  "topology.willReport.hint",
  "topology.willReport.close",
  "pattern.waterline.preWillLegend",
  "pattern.waterline.preWillTooltip",
  "当前日主能量过剩（",
  "），急需通过做功泄耗，否则易固执与内耗。",
  "置信度:",
  "理由链",
  "回滚触发器",
  "压力测试模拟器（预埋）",
  "执行岁运压力测试",
  "模拟大运：",
  "对比镜像性别结果",
  "触发回滚",
  "男：",
  "女：",
  "[SIGNAL_GATE_ACTIVE]: 微弱因果噪声已物理屏蔽，阈值:",
  "风险提示：当前物理能耗过高（abs_delta > 100），应优先执行降耗与稳态校准。",
  "检测到能量高度淤积（Abs: {abs}），做功路径已被岁运阻断。",
  "当前已开启逻辑透深。",
  "建议开启“逻辑透深”检查被隐藏的内耗路径。",
  "查看 {deity} 的演算路径",
  "因果流通链（五行相生）",
  "阈值（归一化场强）:",
  "时空模拟（大运 / 流年）",
  "流年 {liu} · 大运 {dy}",
  "模拟公历参考年",
  "拖动将静默重算物理张量，并把当前大运/流年干支作为 ",
  " 提交后端。",
  "意志回放",
  "盲派 Skill",
  " · 本局已命中信号",
  " · 已武装",
  " · 未启用",
  "当前格局",
  "格局主权",
  " · 集中度 ",
  "喜忌反转说明（悬浮）",
  "未定：logic_diff 尚无有效 Δabs，无法宣读场强气质。",
  "共鸣：因果偏移极低，逻辑圆融。",
  "修正：意志成功校准场强，天平已稳。",
  "重构：因果发生剧烈位移，宿命被强制剥离。",
  "logic_diff：尚无结构化摘要。",
  "因果定格 · 终审存证",
  "SHA-256（缩写 · 点击拷贝完整指纹）",
  "签发时间",
  "logic_diff 最终摘要",
  "虚实比（Solid / Ghost）",
  "实（Solid）：",
  " · 虚（Ghost）：",
  "平均有效传导：",
  "记录该局干支维轴下因果能量的落地程度（越高越「实」）。",
  "本证书快照未含 solid_ghost_ratio（需排盘后 physics meta）。",
  "生效 Skill ID（规则索引）",
  "本快照未记录盲派 Skill 列表（或非盲派会话）。",
  "因果主权（Causal Sovereignty）",
  "路由策略：",
  "意志贡献度（WILL_INFUSED）：",
  "—（无冲突矩阵锚点）",
  "木",
  "火",
  "土",
  "金",
  "水",
  "熄灭",
  "衰微",
  "中和",
  "强旺",
  "盲派体用对垒仪表盘",
  "体（BODY） [家里/INTERNAL]",
  "用（USE） [家外/EXTERNAL]",
  "做功空腔（Working Chamber）",
  "[出口被封锁：能量内溢风险]",
  " 阻滞点：",
  "解锁建议（Strategic Strike）",
  "时柱出口告警：门被焊死（高压态）",
  "做功工具（午火）受大运（子水）压制，路径断裂。",
  "[能量空转 / 无功可受]",
  "[能量空转 / 微观路径已隐藏]",
  "体",
  "用",
  "冲",
  "：基础能量 ",
  " - 损耗 ",
  " - 最终做功 ",
  "食伤泄秀功能坍缩",
  "逻辑锚点：关联 Skill 的语义反馈",
  "精准",
  "偏移",
  "准",
  "偏",
  "当前为【建禄格】，物理能量处于溢出状态，排水（泄耗）是优先策略。",
  "当前为【月劫格】，争夺态明显，需以食伤泄压并谨慎控风险。",
  "当前为【身强无依】，核能空转，必须建立有效做功出口。",
  "女性语义：官杀常映射事业/伴侣压力轴；用忌建议侧重官杀链路稳定性。",
  "男性语义：财星常映射财富/伴侣压力轴；用忌建议侧重财星链路稳定性。",
  "话语权占比：盲派 {blPct}% | 旺衰 {wPct}%",
  "战略核心看板（Strategic HUD）",
  "性别坐标：",
  "峰值能量（Abs）:",
  "用神（能量出口）",
  "忌神（坍塌风险）",
  "调候（硬修正）",
  "已启用",
  "未决冲突：",
  "用神",
  "忌神",
  "调候",
  "峰值Abs",
  "对比同盘男女路径差异",
  "意志重塑现实",
  "物理骨架",
  "逻辑指纹",
  "VF · 逻辑溯源",
  "物理扫描点",
  "盲派芯片日志",
  "管线日志",
  "显示原始物理态",
  "用户决策",
] as const;
