import type { Lang } from "@/types/bazi";

const API_BASE_RAW = (process.env.NEXT_PUBLIC_QIAZHI_API ?? process.env.NEXT_PUBLIC_API_BASE_URL ?? "").replace(/\/$/, "");
const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1", "::1"]);
const resolveApiBase = () => {
  if (!API_BASE_RAW) return "";
  if (API_BASE_RAW === "/api") return "";
  if (API_BASE_RAW.startsWith("/")) return API_BASE_RAW;
  if (typeof window === "undefined") return API_BASE_RAW;
  try {
    const apiHost = new URL(API_BASE_RAW).hostname;
    const pageHost = window.location.hostname;
    if (LOOPBACK_HOSTS.has(apiHost) && !LOOPBACK_HOSTS.has(pageHost)) return "";
  } catch {
    return "";
  }
  return API_BASE_RAW;
};
export const API_BASE = resolveApiBase();
export const ADMIN_TOKEN = process.env.NEXT_PUBLIC_QIAZHI_ADMIN_TOKEN ?? "";
export const adminHeaders: Record<string, string> = ADMIN_TOKEN ? { "X-Admin-Token": ADMIN_TOKEN } : {};
export const fetcher = (url: string) => fetch(url).then((r) => r.json());
export const VERDICT_TIMEOUT_MS = 45000;
export const TRANSLATION_DEBOUNCE_MS = 500;
export const TRANSLATION_CACHE_MAX = 200;

export const I18N: Record<Lang, { title: string; subtitle: string }> = {
  ZH: { title: "掐指一算", subtitle: "对话即推演，卡片即逻辑" },
  EN: { title: "Qiazhi-Bazi", subtitle: "Dialogue as inference, cards as logic." },
  KO: { title: "Qiazhi-Bazi", subtitle: "대화는 추론, 카드는 논리." },
};

export const STATIC_I18N: Record<Lang, Record<string, string>> = {
  ZH: {
    "Layer 1 Fully Aligned": "第一层完全对齐",
  },
  EN: {
    "历史": "History",
    "流式对话与决策卡片": "Streaming dialogue and decision cards",
    "批量勾选后，一次性执行全局裁决。": "Select in batch, then execute a global decision once.",
    "暂无可裁决冲合项。": "No actionable clash/combine items.",
    "已认同": "Accepted",
    "执行中...": "Executing...",
    "执行全局裁决": "Execute Global Decision",
    "已选": "Selected",
    "项": "items",
    "等待确认后生成阶段结论…": "Awaiting confirmation to generate stage conclusion...",
    "动态命盘卡片": "Dynamic Bazi Card",
    "点击地支查看辩证": "Click branch to inspect",
    "命盘卡片将在输入后出现。": "The chart card will appear after input.",
    "大运": "Luck Pillar",
    "流年": "Annual Pillar",
    "暂无冲突点。": "No conflict points.",
    "Audit Sidebar": "Audit Sidebar",
    "权力三角：Arbiter / Core / Auditor": "Power Triangle: Arbiter / Core / Auditor",
    "DB(本地)": "DB(本地)",
    "LLM(0.10)": "LLM(0.10)",
    "等待交互步骤…": "Waiting for interaction steps...",
    "Step": "Step",
    "Decision History": "Decision History",
    "关闭": "Close",
    "暂无历史记录。": "No history records.",
    "记录回滚事件": "Record rollback event",
    "仅本地撤销": "Local undo only",
    "The Seed": "The Seed",
    "输入生日后，系统将进入流式推演。": "After entering birth data, the system starts streaming inference.",
    "公历": "Solar",
    "农历": "Lunar",
    "日期时刻": "Date & Time",
    "年": "Y",
    "月": "M",
    "日": "D",
    "时": "H",
    "分": "Min",
    "推演中…": "Inferring...",
    "掐指一算": "Analyze",
    "Decision Inbox": "Decision Inbox",
    "Atomic Conflicts Checklist": "Atomic Conflicts Checklist",
    "Result Summary": "Result Summary",
    "实验室": "Lab",
    "黑匣子": "Black Box",
    "机房": "Ops",
    "Layer 1 Fully Aligned": "Layer 1 Fully Aligned",
    "左": "L",
    "右": "R",
    "正在重组因果现场...": "Rebinding causal scene...",
    "生辰": "Birth",
    "会话已驻留": "Session pinned",
    "复制快照链接": "Copy snapshot link",
    "视觉仪表盘": "Vision",
    "指令舱": "Command",
    "黑匣子（L1 审计）→": "Black box (L1) →",
    "第一层完全对齐": "Layer 1 Fully Aligned",
    "滑动主区域切换视图，或点右下角浮动按钮": "Swipe the main area to switch views, or use the floating button.",
    "视觉场 · 全局熵": "Vision field · Global entropy",
    "（沉浸式看盘）": "(immersive chart)",
    "当前已有排盘结果，可随时修改生辰重算。": "Chart ready — you can edit birth data anytime to recalculate.",
    "尚未排盘：请先录入生辰八字。": "No chart yet — enter the birth pillars first.",
    "修改生辰": "Edit birth data",
    "录入生辰（地法）": "Enter birth (earth method)",
    "命盘仪表盘": "Chart dashboard",
    "生辰八字 · 地法（The Seed）": "Eight Characters · Earth method (The Seed)",
    "收起表单": "Collapse form",
    "展开表单": "Expand form",
    "掐指一算后在此显示：四柱 / 大运 / 流年": "After analyze: pillars / luck / annual appear here.",
    "表单已收起。点击「展开表单」或顶部「生辰」按钮可再次录入/修改公历、农历、时刻与性别并重新排盘。":
      "Form collapsed. Use “Expand form” or the Birth button to edit solar/lunar, time, gender and recalculate.",
    "提交 IDs：": "Submitted IDs:",
    "做功路径摘要": "Work path summary",
    "期望": "Expectation",
    "反噬风险": "Backfire risk",
    "释放能": "Released energy",
    "在「黑匣子」查看完整 L1 流水线与物理张量 JSON →": "Open Black Box for full L1 pipeline & physics tensor JSON →",
    "暂无批注内容。": "No annotations yet.",
    "输入快照标签（可选）": "Snapshot label (optional)",
  },
  KO: {
    "历史": "기록",
    "流式对话与决策卡片": "스트리밍 대화 및 의사결정 카드",
    "批量勾选后，一次性执行全局裁决。": "일괄 선택 후 전역 판정을 한 번에 실행합니다.",
    "暂无可裁决冲合项。": "판정 가능한 충·합 항목이 없습니다.",
    "已认同": "승인됨",
    "执行中...": "실행 중...",
    "执行全局裁决": "전역 판정 실행",
    "已选": "선택",
    "项": "개",
    "等待确认后生成阶段结论…": "확인 후 단계 결론이 생성됩니다…",
    "动态命盘卡片": "동적 명반 카드",
    "点击地支查看辩证": "지지를 눌러 확인",
    "命盘卡片将在输入后出现。": "입력 후 명반 카드가 표시됩니다.",
    "大运": "대운",
    "流年": "세운",
    "暂无冲突点。": "충돌 포인트 없음.",
    "Audit Sidebar": "감사 사이드바",
    "权力三角：Arbiter / Core / Auditor": "권한 삼각: Arbiter / Core / Auditor",
    "DB(本地)": "DB(本地)",
    "LLM(0.10)": "LLM(0.10)",
    "等待交互步骤…": "상호작용 단계를 기다리는 중…",
    "Step": "단계",
    "Decision History": "결정 이력",
    "关闭": "닫기",
    "暂无历史记录。": "이력 없음.",
    "记录回滚事件": "롤백 이벤트 기록",
    "仅本地撤销": "로컬만 취소",
    "The Seed": "입력 시드",
    "输入生日后，系统将进入流式推演。": "생년월일 입력 후 시스템이 스트리밍 추론을 시작합니다.",
    "公历": "양력",
    "农历": "음력",
    "日期时刻": "날짜/시간",
    "年": "년",
    "月": "월",
    "日": "일",
    "时": "시",
    "分": "분",
    "推演中…": "추론 중…",
    "掐指一算": "분석 시작",
    "Decision Inbox": "결정 인박스",
    "Atomic Conflicts Checklist": "원자 충돌 체크리스트",
    "Result Summary": "결과 요약",
    "[KO] 结果提取失败。": "[KO] 결과 추출에 실패했습니다. (结果提取失败)",
    "实验室": "실험실",
    "黑匣子": "블랙박스",
    "机房": "운영",
    "Layer 1 Fully Aligned": "Layer 1 정렬 완료",
    "左": "좌",
    "右": "우",
    "正在重组因果现场...": "인과 장면을 재구성하는 중...",
    "生辰": "생辰",
    "会话已驻留": "세션 고정됨",
    "复制快照链接": "스냅샷 링크 복사",
    "视觉仪表盘": "비전",
    "指令舱": "커맨드",
    "黑匣子（L1 审计）→": "블랙박스(L1)→",
    "第一层完全对齐": "레이어 1 완전 정렬",
    "滑动主区域切换视图，或点右下角浮动按钮": "메인 영역을 스와이프하거나 우하단 버튼으로 전환하세요.",
    "视觉场 · 全局熵": "비전 필드 · 전역 엔트로피",
    "（沉浸式看盘）": "(몰입형 명반)",
    "当前已有排盘结果，可随时修改生辰重算。": "명반이 있습니다. 생辰을 수정해 언제든 재계산할 수 있습니다.",
    "尚未排盘：请先录入生辰八字。": "아직 명반이 없습니다. 사주를 먼저 입력하세요.",
    "修改生辰": "생辰 수정",
    "录入生辰（地法）": "생辰 입력(지법)",
    "命盘仪表盘": "명반 대시보드",
    "生辰八字 · 地法（The Seed）": "팔자 · 지법 (The Seed)",
    "收起表单": "폼 접기",
    "展开表单": "폼 펼치기",
    "掐指一算后在此显示：四柱 / 大运 / 流年": "분석 후: 사주 / 대운 / 세운이 여기 표시됩니다.",
    "表单已收起。点击「展开表单」或顶部「生辰」按钮可再次录入/修改公历、农历、时刻与性别并重新排盘。":
      "폼이 접혀 있습니다. 「폼 펼치기」 또는 상단 「생辰」으로 양력/음력·시각·성별을 수정하고 재배반할 수 있습니다.",
    "提交 IDs：": "제출 ID:",
    "做功路径摘要": "작업 경로 요약",
    "期望": "기대",
    "反噬风险": "역습 위험",
    "释放能": "방출 에너지",
    "在「黑匣子」查看完整 L1 流水线与物理张量 JSON →": "블랙박스에서 전체 L1 파이프라인·물리 텐서 JSON →",
    "暂无批注内容。": "아직 주석이 없습니다.",
    "输入快照标签（可选）": "스냅샷 라벨(선택)",
  },
};

/** 不经过翻译队列的静态表查找（Shell、桥接页等轻量场景）。 */
export function staticT(lang: Lang, zhKey: string): string {
  if (lang === "ZH") return zhKey;
  return STATIC_I18N[lang]?.[zhKey] ?? zhKey;
}

export const PRELOAD_UI_TEXTS = [
  "掐指一算",
  "对话即推演，卡片即逻辑",
  "历史",
  "流式对话与决策卡片",
  "批量勾选后，一次性执行全局裁决。",
  "暂无可裁决冲合项。",
  "已认同",
  "执行中...",
  "执行全局裁决",
  "已选",
  "项",
  "等待确认后生成阶段结论…",
  "动态命盘卡片",
  "点击地支查看辩证",
  "命盘卡片将在输入后出现。",
  "大运",
  "流年",
  "暂无冲突点。",
  "Audit Sidebar",
  "权力三角：Arbiter / Core / Auditor",
  "DB(本地)",
  "LLM(0.10)",
  "等待交互步骤…",
  "Step",
  "Decision History",
  "关闭",
  "暂无历史记录。",
  "记录回滚事件",
  "仅本地撤销",
  "The Seed",
  "输入生日后，系统将进入流式推演。",
  "公历",
  "农历",
  "日期时刻",
  "年",
  "月",
  "日",
  "时",
  "分",
  "推演中…",
  "第一波：物理排盘中…",
  "第二波：特征扫描中…",
  "扫描完毕，发现",
  "处冲合特征，正在生成首条判词…",
  "全局裁决完成，终极判词已生成。",
  "已记录回滚事件（审计追加，不删除历史）。",
  "回滚事件写入失败：",
  "已确认",
  "，正在执行全局裁决…",
  "✅ 终极判词：",
  "[KO] 结果提取失败。",
  "实验室",
  "黑匣子",
  "机房",
  "Layer 1 Fully Aligned",
  "左",
  "右",
  "正在重组因果现场...",
  "生辰",
  "会话已驻留",
  "复制快照链接",
  "视觉仪表盘",
  "指令舱",
  "黑匣子（L1 审计）→",
  "第一层完全对齐",
  "滑动主区域切换视图，或点右下角浮动按钮",
  "视觉场 · 全局熵",
  "（沉浸式看盘）",
  "当前已有排盘结果，可随时修改生辰重算。",
  "尚未排盘：请先录入生辰八字。",
  "修改生辰",
  "录入生辰（地法）",
  "命盘仪表盘",
  "生辰八字 · 地法（The Seed）",
  "收起表单",
  "展开表单",
  "掐指一算后在此显示：四柱 / 大运 / 流年",
  "表单已收起。点击「展开表单」或顶部「生辰」按钮可再次录入/修改公历、农历、时刻与性别并重新排盘。",
  "提交 IDs：",
  "做功路径摘要",
  "期望",
  "反噬风险",
  "释放能",
  "在「黑匣子」查看完整 L1 流水线与物理张量 JSON →",
  "暂无批注内容。",
  "输入快照标签（可选）",
] as const;
