import type { Lang } from "@/types/bazi";

export const API_BASE = process.env.NEXT_PUBLIC_QIAZHI_API ?? "http://127.0.0.1:8001";
export const ADMIN_TOKEN = process.env.NEXT_PUBLIC_QIAZHI_ADMIN_TOKEN ?? "";
export const adminHeaders: Record<string, string> = ADMIN_TOKEN ? { "X-Admin-Token": ADMIN_TOKEN } : {};
export const fetcher = (url: string) => fetch(url).then((r) => r.json());
export const VERDICT_TIMEOUT_MS = 45000;
export const TRANSLATION_DEBOUNCE_MS = 500;
export const TRANSLATION_CACHE_MAX = 200;

export const I18N: Record<Lang, { title: string; subtitle: string }> = {
  ZH: { title: "掐指一算", subtitle: "对话即推演，卡片即逻辑" },
  EN: { title: "Qiazhi-Bazi", subtitle: "Dialogue as inference, cards as logic." },
  KO: { title: "Qiazhi-Bazi", subtitle: "대화는 추론, 카드는 논리." },
};

export const STATIC_I18N: Record<Lang, Record<string, string>> = {
  ZH: {},
  EN: {
    "历史": "History",
    "流式对话与决策卡片": "Streaming dialogue and decision cards",
    "批量勾选后，一次性执行全局裁决。": "Select in batch, then execute a global decision once.",
    "暂无可裁决冲合项。": "No actionable clash/combine items.",
    "已认同": "Accepted",
    "执行中...": "Executing...",
    "执行全局裁决": "Execute Global Decision",
    "已选": "Selected",
    "项": "items",
    "等待确认后生成阶段结论…": "Awaiting confirmation to generate stage conclusion...",
    "动态命盘卡片": "Dynamic Bazi Card",
    "点击地支查看辩证": "Click branch to inspect",
    "命盘卡片将在输入后出现。": "The chart card will appear after input.",
    "大运": "Luck Pillar",
    "流年": "Annual Pillar",
    "暂无冲突点。": "No conflict points.",
    "Audit Sidebar": "Audit Sidebar",
    "权力三角：Arbiter / Core / Auditor": "Power Triangle: Arbiter / Core / Auditor",
    "DB(本地)": "DB(本地)",
    "LLM(0.10)": "LLM(0.10)",
    "等待交互步骤…": "Waiting for interaction steps...",
    "Step": "Step",
    "Decision History": "Decision History",
    "关闭": "Close",
    "暂无历史记录。": "No history records.",
    "记录回滚事件": "Record rollback event",
    "仅本地撤销": "Local undo only",
    "The Seed": "The Seed",
    "输入生日后，系统将进入流式推演。": "After entering birth data, the system starts streaming inference.",
    "公历": "Solar",
    "农历": "Lunar",
    "日期时刻": "Date & Time",
    "年": "Y",
    "月": "M",
    "日": "D",
    "时": "H",
    "分": "Min",
    "推演中…": "Inferring...",
    "掐指一算": "Analyze",
    "Decision Inbox": "Decision Inbox",
    "Atomic Conflicts Checklist": "Atomic Conflicts Checklist",
    "Result Summary": "Result Summary",
  },
  KO: {
    "历史": "기록",
    "流式对话与决策卡片": "스트리밍 대화 및 의사결정 카드",
    "批量勾选后，一次性执行全局裁决。": "일괄 선택 후 전역 판정을 한 번에 실행합니다.",
    "暂无可裁决冲合项。": "판정 가능한 충·합 항목이 없습니다.",
    "已认同": "승인됨",
    "执行中...": "실행 중...",
    "执行全局裁决": "전역 판정 실행",
    "已选": "선택",
    "项": "개",
    "等待确认后生成阶段结论…": "확인 후 단계 결론이 생성됩니다…",
    "动态命盘卡片": "동적 명반 카드",
    "点击地支查看辩证": "지지를 눌러 확인",
    "命盘卡片将在输入后出现。": "입력 후 명반 카드가 표시됩니다.",
    "大运": "대운",
    "流年": "세운",
    "暂无冲突点。": "충돌 포인트 없음.",
    "Audit Sidebar": "감사 사이드바",
    "权力三角：Arbiter / Core / Auditor": "권한 삼각: Arbiter / Core / Auditor",
    "DB(本地)": "DB(本地)",
    "LLM(0.10)": "LLM(0.10)",
    "等待交互步骤…": "상호작용 단계를 기다리는 중…",
    "Step": "단계",
    "Decision History": "결정 이력",
    "关闭": "닫기",
    "暂无历史记录。": "이력 없음.",
    "记录回滚事件": "롤백 이벤트 기록",
    "仅本地撤销": "로컬만 취소",
    "The Seed": "입력 시드",
    "输入生日后，系统将进入流式推演。": "생년월일 입력 후 시스템이 스트리밍 추론을 시작합니다.",
    "公历": "양력",
    "农历": "음력",
    "日期时刻": "날짜/시간",
    "年": "년",
    "月": "월",
    "日": "일",
    "时": "시",
    "分": "분",
    "推演中…": "추론 중…",
    "掐指一算": "분석 시작",
    "Decision Inbox": "결정 인박스",
    "Atomic Conflicts Checklist": "원자 충돌 체크리스트",
    "Result Summary": "결과 요약",
    "[KO] 结果提取失败。": "[KO] 결과 추출에 실패했습니다. (结果提取失败)",
  },
};

export const PRELOAD_UI_TEXTS = [
  "掐指一算",
  "对话即推演，卡片即逻辑",
  "历史",
  "流式对话与决策卡片",
  "批量勾选后，一次性执行全局裁决。",
  "暂无可裁决冲合项。",
  "已认同",
  "执行中...",
  "执行全局裁决",
  "已选",
  "项",
  "等待确认后生成阶段结论…",
  "动态命盘卡片",
  "点击地支查看辩证",
  "命盘卡片将在输入后出现。",
  "大运",
  "流年",
  "暂无冲突点。",
  "Audit Sidebar",
  "权力三角：Arbiter / Core / Auditor",
  "DB(本地)",
  "LLM(0.10)",
  "等待交互步骤…",
  "Step",
  "Decision History",
  "关闭",
  "暂无历史记录。",
  "记录回滚事件",
  "仅本地撤销",
  "The Seed",
  "输入生日后，系统将进入流式推演。",
  "公历",
  "农历",
  "日期时刻",
  "年",
  "月",
  "日",
  "时",
  "分",
  "推演中…",
  "第一波：物理排盘中…",
  "第二波：特征扫描中…",
  "扫描完毕，发现",
  "处冲合特征，正在生成首条判词…",
  "全局裁决完成，终极判词已生成。",
  "已记录回滚事件（审计追加，不删除历史）。",
  "回滚事件写入失败：",
  "已确认",
  "，正在执行全局裁决…",
  "✅ 终极判词：",
  "[KO] 结果提取失败。",
] as const;
