import type { Lang } from "@/types/bazi";

const API_BASE_RAW = (process.env.NEXT_PUBLIC_QIAZHI_API ?? process.env.NEXT_PUBLIC_API_BASE_URL ?? "").replace(/\/$/, "");
const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1", "::1"]);
const resolveApiBase = () => {
  if (!API_BASE_RAW) return "";
  if (API_BASE_RAW === "/api") return "";
  if (API_BASE_RAW.startsWith("/")) return API_BASE_RAW;
  if (typeof window === "undefined") return API_BASE_RAW;
  try {
    const apiHost = new URL(API_BASE_RAW).hostname;
    const pageHost = window.location.hostname;
    if (LOOPBACK_HOSTS.has(apiHost) && !LOOPBACK_HOSTS.has(pageHost)) return "";
  } catch {
    return "";
  }
  return API_BASE_RAW;
};
export const API_BASE = resolveApiBase();
export const ADMIN_TOKEN = process.env.NEXT_PUBLIC_QIAZHI_ADMIN_TOKEN ?? "";
export const adminHeaders: Record<string, string> = ADMIN_TOKEN ? { "X-Admin-Token": ADMIN_TOKEN } : {};
export const fetcher = (url: string) => fetch(url).then((r) => r.json());
export const VERDICT_TIMEOUT_MS = 45000;
/** 终审签发：|logic_diff.abs_delta| 低于此值且 Inbox 无剩余项时主按钮进入「签发终审」态（纯 UI 门闩，非物理常数） */
export const FINAL_VERDICT_ABS_DELTA_THRESHOLD = 30;
export const TRANSLATION_DEBOUNCE_MS = 500;
export const TRANSLATION_CACHE_MAX = 200;

export const I18N: Record<Lang, { title: string; subtitle: string }> = {
  ZH: { title: "掐指一算", subtitle: "对话即推演，卡片即逻辑" },
  EN: { title: "Qiazhi-Bazi", subtitle: "Dialogue as inference, cards as logic." },
  KO: { title: "Qiazhi-Bazi", subtitle: "대화는 추론, 카드는 논리." },
};

export const STATIC_I18N: Record<Lang, Record<string, string>> = {
  ZH: {
    "Layer 1 Fully Aligned": "第一层完全对齐",
  },
  EN: {
    "流式对话与决策卡片": "Streaming dialogue and decision cards",
    "批量勾选后，一次性执行全局裁决。": "Select in batch, then execute a global decision once.",
    "暂无可裁决冲合项。": "No actionable clash/combine items.",
    "已认同": "Accepted",
    "执行中...": "Executing...",
    "执行全局裁决": "Execute Global Decision",
    "已选": "Selected",
    "项": "items",
    "等待确认后生成阶段结论…": "Awaiting confirmation to generate stage conclusion...",
    "动态命盘卡片": "Dynamic Bazi Card",
    "点击地支查看辩证": "Click branch to inspect",
    "命盘卡片将在输入后出现。": "The chart card will appear after input.",
    "大运": "Luck Pillar",
    "流年": "Annual Pillar",
    "暂无冲突点。": "No conflict points.",
    "Audit Sidebar": "Audit Sidebar",
    "权力三角：Arbiter / Core / Auditor": "Power Triangle: Arbiter / Core / Auditor",
    "DB(本地)": "DB(本地)",
    "LLM(0.10)": "LLM(0.10)",
    "等待交互步骤…": "Waiting for interaction steps...",
    "Step": "Step",
    "The Seed": "The Seed",
    "输入生日后，系统将进入流式推演。": "After entering birth data, the system starts streaming inference.",
    "公历": "Solar",
    "农历": "Lunar",
    "日期时刻": "Date & Time",
    "年": "Y",
    "月": "M",
    "日": "D",
    "时": "H",
    "分": "Min",
    "推演中…": "Inferring...",
    "掐指一算": "Analyze",
    "Decision Inbox": "Decision Inbox",
    "Atomic Conflicts Checklist": "Atomic Conflicts Checklist",
    "Result Summary": "Result Summary",
    "实验室": "Lab",
    "黑匣子": "Black Box",
    "机房": "Ops",
    "Layer 1 Fully Aligned": "Layer 1 Fully Aligned",
    "左": "L",
    "右": "R",
    "正在重组因果现场...": "Rebinding causal scene...",
    "视觉仪表盘": "Vision",
    "指令舱": "Command",
    "黑匣子（L1 审计）→": "Black box (L1) →",
    "第一层完全对齐": "Layer 1 Fully Aligned",
    "滑动主区域切换视图，或点右下角浮动按钮": "Swipe the main area to switch views, or use the floating button.",
    "视觉场 · 全局熵": "Vision field · Global entropy",
    "（沉浸式看盘）": "(immersive chart)",
    "当前已有排盘结果，可随时修改生辰重算。": "Chart ready — you can edit birth data anytime to recalculate.",
    "尚未排盘：请先录入生辰八字。": "No chart yet — enter the birth pillars first.",
    "修改生辰": "Edit birth data",
    "录入生辰（地法）": "Enter birth (earth method)",
    "命盘仪表盘": "Chart dashboard",
    "生辰八字 · 地法（The Seed）": "Eight Characters · Earth method (The Seed)",
    "收起表单": "Collapse form",
    "展开表单": "Expand form",
    "掐指一算后在此显示：四柱 / 大运 / 流年": "After analyze: pillars / luck / annual appear here.",
    "测算八字": "Calculate Bazi",
    "预览": "Preview",
    "流年（参考年）": "Annual pillar (reference year)",
    "环境方位": "Environment facing (geo demo)",
    "预览加载失败": "Preview failed to load",
    "选择出生日期": "Select birth date",
    "选定开始测算": "Start with this birth data",
    "返回重新测算": "Back to birth entry",
    "命盘 · 六柱与流年": "Chart · six pillars & annual pillar",
    "预览更新中…": "Refreshing preview…",
    "参考年": "Reference year",
    "已随测算写入命盘": "written to chart with this run",
    "流年参考年说明": "Luck/annual pillars use this solar year (same as backend reference_year).",
    "表单已收起。点击「展开表单」可再次录入/修改公历、农历、时刻与性别并重新排盘。":
      "Form collapsed. Use “Expand form” to edit solar/lunar, time, gender and recalculate.",
    "提交 IDs：": "Submitted IDs:",
    "做功路径摘要": "Work path summary",
    "期望": "Expectation",
    "反噬风险": "Backfire risk",
    "释放能": "Released energy",
    "在「黑匣子」查看完整 L1 流水线与物理张量 JSON →": "Open Black Box for full L1 pipeline & physics tensor JSON →",
    "暂无批注内容。": "No annotations yet.",
    "已签发 (Issued)": "Issued",
    "主权占优": "Sovereignty dominant",
    "终审已签发 · 公文压底": "Final verdict issued · certificate footer",
    "乾造（男）": "Male chart (Qian)",
    "坤造（女）": "Female chart (Kun)",
    "东": "East",
    "南": "South",
    "西": "West",
    "北": "North",
    "中": "Center",
    "地理场演示：南强化火、北强化水（需重新测算）": "Geo demo: south boosts fire, north boosts water (recalculate to apply).",
    "检测到能量高度淤积（Abs: {abs}），做功路径受阻。": "Severe energy stagnation (Abs: {abs}); work path blocked.",
    "已开启逻辑透深。": "Deep logic paths enabled.",
    "逻辑坍缩中...": "Logic collapsing…",
    "物理排盘：开启因果": "Physics layout: open causality",
    "[因果确认：执行裁决]": "[Causal confirm: run verdict]",
    "语义重构：重新裁决": "Semantic rebuild: re-run verdict",
    "因果锚点已固化": "Causal anchor locked",
    "设置当前为基线": "Set current as baseline",
    "暂无可执行决策项。": "No executable decision items.",
    "勾选决策项后可在统一动作条触发语义裁决。": "After selecting items, use the unified bar to run semantic verdict.",
    "核心看板（Strategic HUD + 盲派镜像）": "Strategic HUD + blind-school mirror",
    "收起": "Collapse",
    "展开": "Expand",
    "语义权重滑杆（Plugin Weights）": "Plugin weight sliders",
    "盲派 ": "Blind school ",
    "旺衰 ": "Strength ",
    "应用权重并重算": "Apply weights & recompute",
    "结果总览（Result Summary）": "Result overview",
    "查看历史版本": "Version history",
    "变更差分（Physics / Consensus / Text）": "Change diff (physics / consensus / text)",
    "物理场变动": "Physics field changes",
    "共识固化": "Consensus freeze",
    "判词修正": "Verdict text patch",
    "无": "None",
    "- 无": "- None",
    "收起证据快照": "Collapse evidence",
    "展开证据快照": "Expand evidence",
    "隐藏模块": "Hide section",
    "显示模块": "Show section",
    "点击下钻证据": "Drill into evidence",
    "盲派做功链路图（L2）": "Blind-school work graph (L2)",
    "触发:": "Trigger:",
    "释放:": "Release:",
    "损耗:": "Loss:",
    "净值:": "Net:",
    "[解锁失败/链路断裂]": "[Unlock failed / broken link]",
    "拓扑图（Topology）": "Topology map",
    "格局态射仪表盘（V0）": "Pattern functor HUD (V0)",
    "正格倾向:": "Stable pattern:",
    "从格倾向:": "Follower pattern:",
    "跃迁倾向:": "Leap tendency:",
    "L2 格局终审结果（V0）": "L2 pattern final (V0)",
    "当前日主能量过剩（": "Day master energy excess (",
    "），急需通过做功泄耗，否则易固执与内耗。": "); drain via work paths or risk rigidity and inner loss.",
    "置信度:": "Confidence:",
    "理由链": "Reason chain",
    "回滚触发器": "Rollback triggers",
    "压力测试模拟器（预埋）": "Stress-test simulator (stub)",
    "执行岁运压力测试": "Run luck-pillar stress test",
    "模拟大运：": "Simulate luck:",
    "对比镜像性别结果": "Compare gender mirror",
    "触发回滚": "Rollback triggered",
    "男：": "Male:",
    "女：": "Female:",
    "[SIGNAL_GATE_ACTIVE]: 微弱因果噪声已物理屏蔽，阈值:": "[SIGNAL_GATE_ACTIVE]: weak causal noise gated; threshold:",
    "风险提示：当前物理能耗过高（abs_delta > 100），应优先执行降耗与稳态校准。":
      "Risk: physics cost too high (abs_delta > 100); reduce load and stabilize first.",
    "检测到能量高度淤积（Abs: {abs}），做功路径已被岁运阻断。": "Severe stagnation (Abs: {abs}); year/luck flow blocks the work path.",
    "当前已开启逻辑透深。": "Deep logic paths are on.",
    "建议开启“逻辑透深”检查被隐藏的内耗路径。": "Enable “deep logic” to inspect hidden loss paths.",
    "查看 {deity} 的演算路径": "Open derivation for {deity}",
    "因果流通链（五行相生）": "Causal flow (five-element generation)",
    "阈值（归一化场强）:": "Threshold (normalized field):",
    "时空模拟（大运 / 流年）": "Time simulation (luck / annual)",
    "流年 {liu} · 大运 {dy}": "Annual {liu} · Luck {dy}",
    "模拟公历参考年": "Simulate solar reference year",
    "拖动将静默重算物理张量，并把当前大运/流年干支作为 ": "Drag silently recomputes physics and sends luck/annual stems/branches as ",
    " 提交后端。": " to the backend.",
    "意志回放": "Will replay",
    "盲派 Skill": "Blind-school skills",
    " · 本局已命中信号": " · hit in this chart",
    " · 已武装": " · armed",
    " · 未启用": " · off",
    "当前格局": "Current pattern",
    "格局主权": "Pattern sovereignty",
    " · 集中度 ": " · concentration ",
    "平常局": "Ordinary chart",
    "喜忌反转说明（悬浮）": "Xi/Ji reversal (hover)",
    "未定：logic_diff 尚无有效 Δabs，无法宣读场强气质。":
      "Unset: no valid Δabs in logic_diff; field tone unavailable.",
    "共鸣：因果偏移极低，逻辑圆融。": "Resonance: very low causal shift; logic is smooth.",
    "修正：意志成功校准场强，天平已稳。": "Correction: will calibrates field strength; balance holds.",
    "重构：因果发生剧烈位移，宿命被强制剥离。": "Rebuild: violent causal shift; fate thread torn.",
    "logic_diff：尚无结构化摘要。": "logic_diff: no structured summary yet.",
    "因果定格 · 终审存证": "Causal seal · final certificate",
    "SHA-256（缩写 · 点击拷贝完整指纹）": "SHA-256 (abbr · tap to copy full hash)",
    "签发时间": "Issued at",
    "logic_diff 最终摘要": "logic_diff final digest",
    "虚实比（Solid / Ghost）": "Solid / ghost ratio",
    "实（Solid）：": "Solid:",
    " · 虚（Ghost）：": " · Ghost:",
    "平均有效传导：": "Avg effective conductivity:",
    "记录该局干支维轴下因果能量的落地程度（越高越「实」）。": "How much causal energy grounds on this pillar frame (higher = more solid).",
    "本证书快照未含 solid_ghost_ratio（需排盘后 physics meta）。": "Snapshot has no solid_ghost_ratio (needs chart + physics meta).",
    "生效 Skill ID（规则索引）": "Effective skill IDs",
    "本快照未记录盲派 Skill 列表（或非盲派会话）。": "No blind-school skill list on this snapshot.",
    "因果主权（Causal Sovereignty）": "Causal sovereignty",
    "路由策略：": "Routing:",
    "意志贡献度（WILL_INFUSED）：": "Will infusion (WILL_INFUSED):",
    "—（无冲突矩阵锚点）": "— (no conflict-matrix anchor)",
    "木": "Wood",
    "火": "Fire",
    "土": "Earth",
    "金": "Metal",
    "水": "Water",
    "熄灭": "Extinguished",
    "衰微": "Weak",
    "中和": "Balanced",
    "强旺": "Strong",
    "盲派体用对垒仪表盘": "Blind school body/use duel HUD",
    "体（BODY） [家里/INTERNAL]": "Body (BODY) [internal]",
    "用（USE） [家外/EXTERNAL]": "Use (USE) [external]",
    "做功空腔（Working Chamber）": "Working chamber",
    "[出口被封锁：能量内溢风险]": "[Exit locked: inner overflow risk]",
    " 阻滞点：": " Blockers:",
    "解锁建议（Strategic Strike）": "Unlock options (strategic strike)",
    "时柱出口告警：门被焊死（高压态）": "Hour pillar exit alert: welded shut (high pressure)",
    "做功工具（午火）受大运（子水）压制，路径断裂。":
      "Work tool (Wu fire) suppressed by luck (Zi water); path broken.",
    "[能量空转 / 无功可受]": "[Idle energy / no usable sink]",
    "[能量空转 / 微观路径已隐藏]": "[Idle energy / micro paths hidden]",
    "体": "Body",
    "用": "Use",
    "冲": "Clash",
    "：基础能量 ": ": base ",
    " - 损耗 ": " - loss ",
    " - 最终做功 ": " - net work ",
    "食伤泄秀功能坍缩": "Output stars drain collapsed",
    "逻辑锚点：关联 Skill 的语义反馈": "Logic anchor: semantic feedback for skill",
    "精准": "Precise",
    "偏移": "Drift",
    "准": "OK",
    "偏": "Off",
    "当前为【建禄格】，物理能量处于溢出状态，排水（泄耗）是优先策略。":
      "Jian Lu pattern: energy overflows; draining (output) is priority.",
    "当前为【月劫格】，争夺态明显，需以食伤泄压并谨慎控风险。":
      "Yue Jie pattern: contention; use output stars to vent pressure and control risk.",
    "当前为【身强无依】，核能空转，必须建立有效做功出口。":
      "Strong-without-support: nuclear idle spin; need a real work exit.",
    "女性语义：官杀常映射事业/伴侣压力轴；用忌建议侧重官杀链路稳定性。":
      "Female reading: officer stars map career/partner stress; stabilize that axis.",
    "男性语义：财星常映射财富/伴侣压力轴；用忌建议侧重财星链路稳定性。":
      "Male reading: wealth stars map money/partner stress; stabilize that axis.",
    "话语权占比：盲派 {blPct}% | 旺衰 {wPct}%": "Voice share: blind {blPct}% · strength {wPct}%",
    "战略核心看板（Strategic HUD）": "Strategic core HUD",
    "性别坐标：": "Gender:",
    "峰值能量（Abs）:": "Peak Abs:",
    "用神（能量出口）": "Useful gods (energy exit)",
    "忌神（坍塌风险）": "Obstacle gods (collapse risk)",
    "调候（硬修正）": "Climate tuning (hard correction)",
    "已启用": "On",
    "未决冲突：": "Unresolved conflicts:",
    "用神": "Useful god",
    "忌神": "Obstacle god",
    "调候": "Climate",
    "峰值Abs": "Peak Abs",
    "对比同盘男女路径差异": "Compare male/female paths for the same chart",
    "[ROUTING]: 基础物理与盲派冲突，已按流派优先策略自动校准":
      "[ROUTING]: base physics vs blind-school conflict; auto-calibrated by school priority.",
    "暂无 physics_audit 条目；提交命盘后展示 Skill 能量贡献 Top5。":
      "No physics_audit rows yet; run a chart to see top-5 skill energy contributions.",
    "逻辑概览 · Skill 贡献 Top5": "Logic overview · top-5 skill contributions",
    "月令司令": "Month command (chronos)",
    "余气进气": "Residual qi intake",
    "旺衰·得令": "Strength · timely",
    "旺衰·得地": "Strength · rooted",
    "旺衰·得助": "Strength · assisted",
    "十二长生缩放": "12 growth-states scaling",
    "L1 相生 η": "L1 production η",
    "L1 相克 η": "L1 destruction η",
    "L1 合绊 η": "L1 connect η",
    "盖头截脚": "Vertical stem-branch crush",
    "财富·宿主能量": "Wealth · host energy",
    "财富·净做功": "Wealth · net work",
    "财富·出口闭锁": "Wealth · exit lock",
    "财富·结构锚": "Wealth · structure anchor",
    "财富·风险带": "Wealth · risk band",
    "化气": "Transformed qi",
    "合而不化": "Combined, not transformed",
    "天干五合：{stems}（{mode}）": "Five-stem combo: {stems} ({mode})",
    "巅峰": "Peak",
    "低谷": "Trough",
    "平区": "Mid band",
    " 数值审计": " numeric audit",
    "[枢纽] ": "[Pivot] ",
    "旺衰引擎标定的 Target_Pivot（用神侧能量×能效）":
      "Strength engine Target_Pivot (useful-side energy × efficiency)",
    "[审计预警] ": "[Audit alert] ",
    "当前未命中该项异常关键词。": "No anomaly keyword hit for this item.",
    "点击后可查看：基础动能 / 物理干预 / 归一化校准":
      "Click to inspect: base kinetic / interventions / normalization",
    "枢纽十神（{s}）": "Pivot deity ({s})",
    "点击查看演算路径": "Click to open derivation path",
    "! 挑刺": "! Nitpick",
    "该能量场已根据共识参数 ": "This field is locked by consensus params ",
    " 锁定": " lock",
    "调候硬修正已启用": "Climate hard-correction active",
    "十二长生能效 Work_Efficiency=": "12-state efficiency Work_Efficiency=",
    "（约 0.4 低谷 — 1.25 巅峰）": "(approx 0.4 trough — 1.25 peak)",
    "长生能效 ": "Growth-state efficiency ",
    "透:": "Stem:",
    "根:": "Root:",
    "十神纯数看板": "Ten-god numeric board",
    "已存在会话共识": "Session consensus present",
    "共识已对齐": "Consensus aligned",
    "[十神名 | 能量条 | 百分比]": "[Deity | energy bar | percent]",
  },
  KO: {
    "流式对话与决策卡片": "스트리밍 대화 및 의사결정 카드",
    "批量勾选后，一次性执行全局裁决。": "일괄 선택 후 전역 판정을 한 번에 실행합니다.",
    "暂无可裁决冲合项。": "판정 가능한 충·합 항목이 없습니다.",
    "已认同": "승인됨",
    "执行中...": "실행 중...",
    "执行全局裁决": "전역 판정 실행",
    "已选": "선택",
    "项": "개",
    "等待确认后生成阶段结论…": "확인 후 단계 결론이 생성됩니다…",
    "动态命盘卡片": "동적 명반 카드",
    "点击地支查看辩证": "지지를 눌러 확인",
    "命盘卡片将在输入后出现。": "입력 후 명반 카드가 표시됩니다.",
    "大运": "대운",
    "流年": "세운",
    "暂无冲突点。": "충돌 포인트 없음.",
    "Audit Sidebar": "감사 사이드바",
    "权力三角：Arbiter / Core / Auditor": "권한 삼각: Arbiter / Core / Auditor",
    "DB(本地)": "DB(本地)",
    "LLM(0.10)": "LLM(0.10)",
    "等待交互步骤…": "상호작용 단계를 기다리는 중…",
    "Step": "단계",
    "The Seed": "입력 시드",
    "输入生日后，系统将进入流式推演。": "생년월일 입력 후 시스템이 스트리밍 추론을 시작합니다.",
    "公历": "양력",
    "农历": "음력",
    "日期时刻": "날짜/시간",
    "年": "년",
    "月": "월",
    "日": "일",
    "时": "시",
    "分": "분",
    "推演中…": "추론 중…",
    "掐指一算": "분석 시작",
    "Decision Inbox": "결정 인박스",
    "Atomic Conflicts Checklist": "원자 충돌 체크리스트",
    "Result Summary": "결과 요약",
    "[KO] 结果提取失败。": "[KO] 결과 추출에 실패했습니다. (结果提取失败)",
    "实验室": "실험실",
    "黑匣子": "블랙박스",
    "机房": "운영",
    "Layer 1 Fully Aligned": "Layer 1 정렬 완료",
    "左": "좌",
    "右": "우",
    "正在重组因果现场...": "인과 장면을 재구성하는 중...",
    "视觉仪表盘": "비전",
    "指令舱": "커맨드",
    "黑匣子（L1 审计）→": "블랙박스(L1)→",
    "第一层完全对齐": "레이어 1 완전 정렬",
    "滑动主区域切换视图，或点右下角浮动按钮": "메인 영역을 스와이프하거나 우하단 버튼으로 전환하세요.",
    "视觉场 · 全局熵": "비전 필드 · 전역 엔트로피",
    "（沉浸式看盘）": "(몰입형 명반)",
    "当前已有排盘结果，可随时修改生辰重算。": "명반이 있습니다. 생辰을 수정해 언제든 재계산할 수 있습니다.",
    "尚未排盘：请先录入生辰八字。": "아직 명반이 없습니다. 사주를 먼저 입력하세요.",
    "修改生辰": "생辰 수정",
    "录入生辰（地法）": "생辰 입력(지법)",
    "命盘仪表盘": "명반 대시보드",
    "生辰八字 · 地法（The Seed）": "팔자 · 지법 (The Seed)",
    "收起表单": "폼 접기",
    "展开表单": "폼 펼치기",
    "掐指一算后在此显示：四柱 / 大运 / 流年": "분석 후: 사주 / 대운 / 세운이 여기 표시됩니다.",
    "测算八字": "사주 계산",
    "预览": "미리보기",
    "流年（参考年）": "세운 (기준 연도)",
    "环境方位": "방위(지리 데모)",
    "预览加载失败": "미리보기를 불러오지 못했습니다",
    "选择出生日期": "생년월일 선택",
    "选定开始测算": "이 생시로 시작",
    "返回重新测算": "생시 입력으로 돌아가기",
    "命盘 · 六柱与流年": "명반 · 육주와 세운",
    "预览更新中…": "미리보기 갱신 중…",
    "参考年": "기준 연도",
    "已随测算写入命盘": "이번 계산으로 명반에 반영됨",
    "流年参考年说明": "대운·세운은 이 양력 기준 연도로 계산됩니다(백엔드 reference_year와 동일).",
    "表单已收起。点击「展开表单」可再次录入/修改公历、农历、时刻与性别并重新排盘。":
      "폼이 접혀 있습니다. 「폼 펼치기」로 양력/음력·시각·성별을 수정하고 재배반할 수 있습니다.",
    "提交 IDs：": "제출 ID:",
    "做功路径摘要": "작업 경로 요약",
    "期望": "기대",
    "反噬风险": "역습 위험",
    "释放能": "방출 에너지",
    "在「黑匣子」查看完整 L1 流水线与物理张量 JSON →": "블랙박스에서 전체 L1 파이프라인·물리 텐서 JSON →",
    "暂无批注内容。": "아직 주석이 없습니다.",
    "已签发 (Issued)": "발행됨",
    "主权占优": "주권 우세",
    "终审已签发 · 公文压底": "최종 판정 발행 · 증명 하단",
    "乾造（男）": "남명(乾)",
    "坤造（女）": "여명(坤)",
    "东": "동",
    "南": "남",
    "西": "서",
    "北": "북",
    "中": "중",
    "地理场演示：南强化火、北强化水（需重新测算）": "지리 데모: 남은 화, 북은 수(재측정 필요).",
    "检测到能量高度淤积（Abs: {abs}），做功路径受阻。": "에너지 정체 심함(Abs: {abs}), 작업 경로 막힘.",
    "已开启逻辑透深。": "논리 심층 경로 켜짐.",
    "逻辑坍缩中...": "논리 붕괴 중…",
    "物理排盘：开启因果": "물리 배반: 인과 개시",
    "[因果确认：执行裁决]": "[인과 확인: 판정 실행]",
    "语义重构：重新裁决": "의미 재구성: 재판정",
    "因果锚点已固化": "인과 앵커 고정",
    "设置当前为基线": "현재를 기준선으로",
    "暂无可执行决策项。": "실행 가능한 결정 항목 없음.",
    "勾选决策项后可在统一动作条触发语义裁决。": "선택 후 통합 바에서 의미 판정 실행.",
    "核心看板（Strategic HUD + 盲派镜像）": "전략 HUD + 맹파 미러",
    "收起": "접기",
    "展开": "펼치기",
    "语义权重滑杆（Plugin Weights）": "플러그인 가중치 슬라이더",
    "盲派 ": "맹파 ",
    "旺衰 ": "왕쇠 ",
    "应用权重并重算": "가중치 적용 후 재계산",
    "结果总览（Result Summary）": "결과 개요",
    "查看历史版本": "버전 기록",
    "变更差分（Physics / Consensus / Text）": "변경 차분(물리/합의/텍스트)",
    "物理场变动": "물리장 변화",
    "共识固化": "합의 고정",
    "判词修正": "판문 수정",
    "无": "없음",
    "- 无": "- 없음",
    "收起证据快照": "증거 접기",
    "展开证据快照": "증거 펼치기",
    "隐藏模块": "섹션 숨기기",
    "显示模块": "섹션 보이기",
    "点击下钻证据": "증거 드릴다운",
    "盲派做功链路图（L2）": "맹파 작업 링크(L2)",
    "触发:": "트리거:",
    "释放:": "방출:",
    "损耗:": "손실:",
    "净值:": "순:",
    "[解锁失败/链路断裂]": "[잠금 해제 실패/단절]",
    "拓扑图（Topology）": "토폴로지",
    "格局态射仪表盘（V0）": "격국 사상 HUD(V0)",
    "正格倾向:": "정격 경향:",
    "从格倾向:": "종격 경향:",
    "跃迁倾向:": "도약 경향:",
    "L2 格局终审结果（V0）": "L2 격국 최종(V0)",
    "当前日主能量过剩（": "일간 에너지 과잉(",
    "），急需通过做功泄耗，否则易固执与内耗。": ") 작업으로 소모 필요, 고집·내부 소모 위험.",
    "置信度:": "신뢰도:",
    "理由链": "이유 체인",
    "回滚触发器": "롤백 트리거",
    "压力测试模拟器（预埋）": "스트레스 테스트(스텁)",
    "执行岁运压力测试": "대운 스트레스 실행",
    "模拟大运：": "대운 시뮬:",
    "对比镜像性别结果": "성별 미러 비교",
    "触发回滚": "롤백 발생",
    "男：": "남:",
    "女：": "여:",
    "[SIGNAL_GATE_ACTIVE]: 微弱因果噪声已物理屏蔽，阈值:": "[SIGNAL_GATE_ACTIVE]: 미약 인과 노이즈 차단, 임계:",
    "风险提示：当前物理能耗过高（abs_delta > 100），应优先执行降耗与稳态校准。":
      "위험: 물리 비용 과다(abs_delta>100); 부하 감소·안정 우선.",
    "检测到能量高度淤积（Abs: {abs}），做功路径已被岁运阻断。": "에너지 정체(Abs:{abs}), 세운·대운이 경로 차단.",
    "当前已开启逻辑透深。": "논리 심층 경로 사용 중.",
    "建议开启“逻辑透深”检查被隐藏的内耗路径。": "숨은 손실 경로를 보려 「논리 심층」을 켜세요.",
    "查看 {deity} 的演算路径": "{deity} 연역 경로 보기",
    "因果流通链（五行相生）": "인과 유통(오행 상생)",
    "阈值（归一化场强）:": "임계(정규화 장세):",
    "时空模拟（大运 / 流年）": "시공 시뮬(대운/세운)",
    "流年 {liu} · 大运 {dy}": "세운 {liu} · 대운 {dy}",
    "模拟公历参考年": "양력 기준 연도 시뮬",
    "拖动将静默重算物理张量，并把当前大运/流年干支作为 ": "드래그 시 물리 텐서 재계산, 대운·세운 간지를 ",
    " 提交后端。": " 로 백엔드에 전송.",
    "意志回放": "의지 리플레이",
    "盲派 Skill": "맹파 스킬",
    " · 本局已命中信号": " · 본국에서 신호 적중",
    " · 已武装": " · 무장됨",
    " · 未启用": " · 비활성",
    "当前格局": "현재 격국",
    "格局主权": "격국 주권",
    " · 集中度 ": " · 집중도 ",
    "平常局": "평범한 국면",
    "喜忌反转说明（悬浮）": "희기 반전 설명(호버)",
    "未定：logic_diff 尚无有效 Δabs，无法宣读场强气质。":
      "미정: logic_diff에 유효 Δabs 없음, 장 기질 불가.",
    "共鸣：因果偏移极低，逻辑圆融。": "공명: 인과 편차 극소, 논리 원만.",
    "修正：意志成功校准场强，天平已稳。": "수정: 의지로 장세 보정, 균형 안정.",
    "重构：因果发生剧烈位移，宿命被强制剥离。": "재구성: 격렬한 인과 이동, 숙명 분리.",
    "logic_diff：尚无结构化摘要。": "logic_diff: 구조화 요약 없음.",
    "因果定格 · 终审存证": "인과 봉인 · 최종 증명",
    "SHA-256（缩写 · 点击拷贝完整指纹）": "SHA-256(약어·탭해 전체 복사)",
    "签发时间": "발행 시각",
    "logic_diff 最终摘要": "logic_diff 최종 요약",
    "虚实比（Solid / Ghost）": "실허 비(Solid/Ghost)",
    "实（Solid）：": "실(Solid):",
    " · 虚（Ghost）：": " · 허(Ghost):",
    "平均有效传导：": "평균 유효 전도:",
    "记录该局干支维轴下因果能量的落地程度（越高越「实」）。": "간지 축에서 인과 에너지의 착지 정도(높을수록 실).",
    "本证书快照未含 solid_ghost_ratio（需排盘后 physics meta）。": "스냅샷에 solid_ghost_ratio 없음(배반+물리 meta 필요).",
    "生效 Skill ID（规则索引）": "유효 스킬 ID",
    "本快照未记录盲派 Skill 列表（或非盲派会话）。": "맹파 스킬 목록 없음(비맹파 세션).",
    "因果主权（Causal Sovereignty）": "인과 주권",
    "路由策略：": "라우팅:",
    "意志贡献度（WILL_INFUSED）：": "의지 기여(WILL_INFUSED):",
    "—（无冲突矩阵锚点）": "—(충돌 행렬 앵커 없음)",
    "木": "목",
    "火": "화",
    "土": "토",
    "金": "금",
    "水": "수",
    "熄灭": "소멸",
    "衰微": "쇠약",
    "中和": "중화",
    "强旺": "강왕",
    "盲派体用对垒仪表盘": "맹파 체용 대결 HUD",
    "体（BODY） [家里/INTERNAL]": "체(BODY)[내부]",
    "用（USE） [家外/EXTERNAL]": "용(USE)[외부]",
    "做功空腔（Working Chamber）": "작업 챔버",
    "[出口被封锁：能量内溢风险]": "[출구 봉쇄: 내부 과잉 위험]",
    " 阻滞点：": " 저지점:",
    "解锁建议（Strategic Strike）": "해제 제안(전략 타격)",
    "时柱出口告警：门被焊死（高压态）": "시주 출구 경고: 용접됨(고압)",
    "做功工具（午火）受大运（子水）压制，路径断裂。": "작업 도구(오화)가 대운(자수)에 눌림, 경로 단절.",
    "[能量空转 / 无功可受]": "[에너지 공전/받을 곳 없음]",
    "[能量空转 / 微观路径已隐藏]": "[에너지 공전/미시 경로 숨김]",
    "体": "체",
    "用": "용",
    "冲": "충",
    "：基础能量 ": ": 기본 ",
    " - 损耗 ": " - 손실 ",
    " - 最终做功 ": " - 순작 ",
    "食伤泄秀功能坍缩": "식상 설수 기능 붕괴",
    "逻辑锚点：关联 Skill 的语义反馈": "논리 앵커: 스킬 의미 피드백",
    "精准": "정확",
    "偏移": "편차",
    "准": "맞",
    "偏": "빗",
    "当前为【建禄格】，物理能量处于溢出状态，排水（泄耗）是优先策略。":
      "건록격: 에너지 과잉, 배수(설소) 우선.",
    "当前为【月劫格】，争夺态明显，需以食伤泄压并谨慎控风险。":
      "월겹격: 경쟁, 식상으로 압력 해소·위험 관리.",
    "当前为【身强无依】，核能空转，必须建立有效做功出口。":
      "신강무의: 공전, 유효 작업 출구 필요.",
    "女性语义：官杀常映射事业/伴侣压力轴；用忌建议侧重官杀链路稳定性。":
      "여성: 관살이 사업/배우자 축, 관살 링크 안정.",
    "男性语义：财星常映射财富/伴侣压力轴；用忌建议侧重财星链路稳定性。":
      "남성: 재성이 재물/배우자 축, 재성 링크 안정.",
    "话语权占比：盲派 {blPct}% | 旺衰 {wPct}%": "발언 비중: 맹파 {blPct}% · 왕쇠 {wPct}%",
    "战略核心看板（Strategic HUD）": "전략 핵심 HUD",
    "性别坐标：": "성별:",
    "峰值能量（Abs）:": "피크 Abs:",
    "用神（能量出口）": "용신(에너지 출구)",
    "忌神（坍塌风险）": "기신(붕괴 위험)",
    "调候（硬修正）": "조후(하드 보정)",
    "已启用": "켜짐",
    "未决冲突：": "미해결 충돌:",
    "用神": "용신",
    "忌神": "기신",
    "调候": "조후",
    "峰值Abs": "피크 Abs",
    "对比同盘男女路径差异": "동일 명반 남녀 경로 비교",
    "[ROUTING]: 基础物理与盲派冲突，已按流派优先策略自动校准":
      "[ROUTING]: 기초 물리 vs 맹파 충돌, 학파 우선 전략으로 자동 보정.",
    "暂无 physics_audit 条目；提交命盘后展示 Skill 能量贡献 Top5。":
      "physics_audit 항목 없음; 배반 후 스킬 에너지 기여 Top5 표시.",
    "逻辑概览 · Skill 贡献 Top5": "논리 개요 · 스킬 기여 Top5",
    "月令司令": "월령 사령",
    "余气进气": "여기 진기",
    "旺衰·得令": "왕쇠·득령",
    "旺衰·得地": "왕쇠·득지",
    "旺衰·得助": "왕쇠·득조",
    "十二长生缩放": "12장생 스케일",
    "L1 相生 η": "L1 상생 η",
    "L1 相克 η": "L1 상극 η",
    "L1 合绊 η": "L1 합반 η",
    "盖头截脚": "개두절각",
    "财富·宿主能量": "재부·숙주 에너지",
    "财富·净做功": "재부·순작업",
    "财富·出口闭锁": "재부·출구 폐쇄",
    "财富·结构锚": "재부·구조 앵커",
    "财富·风险带": "재부·위험대",
    "化气": "화기",
    "合而不化": "합이 불화",
    "天干五合：{stems}（{mode}）": "천간 오합: {stems} ({mode})",
    "巅峰": "정점",
    "低谷": "저점",
    "平区": "중간대",
    " 数值审计": " 수치 감사",
    "[枢纽] ": "[추축] ",
    "旺衰引擎标定的 Target_Pivot（用神侧能量×能效）":
      "왕쇠 엔진 Target_Pivot(용신측 에너지×효율)",
    "[审计预警] ": "[감사 경고] ",
    "当前未命中该项异常关键词。": "이 항목 이상 키워드 미적중.",
    "点击后可查看：基础动能 / 物理干预 / 归一化校准":
      "클릭 시: 기본 동능/물리 개입/정규화 보정",
    "枢纽十神（{s}）": "추십신({s})",
    "点击查看演算路径": "클릭해 연역 경로 열기",
    "! 挑刺": "! 트집",
    "该能量场已根据共识参数 ": "합의 파라미터로 이 에너지장 ",
    " 锁定": " 잠금",
    "调候硬修正已启用": "조후 하드 보정 사용",
    "十二长生能效 Work_Efficiency=": "12장생 효율 Work_Efficiency=",
    "（约 0.4 低谷 — 1.25 巅峰）": "(약 0.4 저점—1.25 정점)",
    "长生能效 ": "장생 효율 ",
    "透:": "투:",
    "根:": "근:",
    "十神纯数看板": "십신 순수 수치판",
    "已存在会话共识": "세션 합의 존재",
    "共识已对齐": "합의 정렬됨",
    "[十神名 | 能量条 | 百分比]": "[십신명 | 에너지 막대 | 백분율]",
  },
};

/** 不经过翻译队列的静态表查找（Shell、桥接页等轻量场景）。 */
export function staticT(lang: Lang, zhKey: string): string {
  if (lang === "ZH") return zhKey;
  return STATIC_I18N[lang]?.[zhKey] ?? zhKey;
}

export const PRELOAD_UI_TEXTS = [
  "掐指一算",
  "对话即推演，卡片即逻辑",
  "流式对话与决策卡片",
  "批量勾选后，一次性执行全局裁决。",
  "暂无可裁决冲合项。",
  "已认同",
  "执行中...",
  "执行全局裁决",
  "已选",
  "项",
  "等待确认后生成阶段结论…",
  "动态命盘卡片",
  "点击地支查看辩证",
  "命盘卡片将在输入后出现。",
  "大运",
  "流年",
  "暂无冲突点。",
  "Audit Sidebar",
  "权力三角：Arbiter / Core / Auditor",
  "DB(本地)",
  "LLM(0.10)",
  "等待交互步骤…",
  "Step",
  "The Seed",
  "输入生日后，系统将进入流式推演。",
  "公历",
  "农历",
  "日期时刻",
  "年",
  "月",
  "日",
  "时",
  "分",
  "推演中…",
  "第一波：物理排盘中…",
  "第二波：特征扫描中…",
  "扫描完毕，发现",
  "处冲合特征，正在生成首条判词…",
  "全局裁决完成，终极判词已生成。",
  "已确认",
  "，正在执行全局裁决…",
  "✅ 终极判词：",
  "[KO] 结果提取失败。",
  "实验室",
  "黑匣子",
  "机房",
  "Layer 1 Fully Aligned",
  "左",
  "右",
  "正在重组因果现场...",
  "视觉仪表盘",
  "指令舱",
  "黑匣子（L1 审计）→",
  "第一层完全对齐",
  "滑动主区域切换视图，或点右下角浮动按钮",
  "视觉场 · 全局熵",
  "（沉浸式看盘）",
  "当前已有排盘结果，可随时修改生辰重算。",
  "尚未排盘：请先录入生辰八字。",
  "修改生辰",
  "录入生辰（地法）",
  "命盘仪表盘",
  "生辰八字 · 地法（The Seed）",
  "收起表单",
  "展开表单",
  "掐指一算后在此显示：四柱 / 大运 / 流年",
  "测算八字",
  "预览",
  "流年（参考年）",
  "环境方位",
  "预览加载失败",
  "选择出生日期",
  "选定开始测算",
  "返回重新测算",
  "命盘 · 六柱与流年",
  "预览更新中…",
  "参考年",
  "已随测算写入命盘",
  "流年参考年说明",
  "表单已收起。点击「展开表单」可再次录入/修改公历、农历、时刻与性别并重新排盘。",
  "提交 IDs：",
  "做功路径摘要",
  "期望",
  "反噬风险",
  "释放能",
  "在「黑匣子」查看完整 L1 流水线与物理张量 JSON →",
  "暂无批注内容。",
  "已签发 (Issued)",
  "主权占优",
  "终审已签发 · 公文压底",
  "乾造（男）",
  "坤造（女）",
  "东",
  "南",
  "西",
  "北",
  "中",
  "地理场演示：南强化火、北强化水（需重新测算）",
  "检测到能量高度淤积（Abs: {abs}），做功路径受阻。",
  "已开启逻辑透深。",
  "逻辑坍缩中...",
  "物理排盘：开启因果",
  "[因果确认：执行裁决]",
  "语义重构：重新裁决",
  "因果锚点已固化",
  "设置当前为基线",
  "暂无可执行决策项。",
  "勾选决策项后可在统一动作条触发语义裁决。",
  "核心看板（Strategic HUD + 盲派镜像）",
  "收起",
  "展开",
  "语义权重滑杆（Plugin Weights）",
  "盲派 ",
  "旺衰 ",
  "应用权重并重算",
  "结果总览（Result Summary）",
  "查看历史版本",
  "变更差分（Physics / Consensus / Text）",
  "物理场变动",
  "共识固化",
  "判词修正",
  "无",
  "- 无",
  "收起证据快照",
  "展开证据快照",
  "隐藏模块",
  "显示模块",
  "点击下钻证据",
  "盲派做功链路图（L2）",
  "触发:",
  "释放:",
  "损耗:",
  "净值:",
  "[解锁失败/链路断裂]",
  "拓扑图（Topology）",
  "格局态射仪表盘（V0）",
  "正格倾向:",
  "从格倾向:",
  "跃迁倾向:",
  "L2 格局终审结果（V0）",
  "当前日主能量过剩（",
  "），急需通过做功泄耗，否则易固执与内耗。",
  "置信度:",
  "理由链",
  "回滚触发器",
  "压力测试模拟器（预埋）",
  "执行岁运压力测试",
  "模拟大运：",
  "对比镜像性别结果",
  "触发回滚",
  "男：",
  "女：",
  "[SIGNAL_GATE_ACTIVE]: 微弱因果噪声已物理屏蔽，阈值:",
  "风险提示：当前物理能耗过高（abs_delta > 100），应优先执行降耗与稳态校准。",
  "检测到能量高度淤积（Abs: {abs}），做功路径已被岁运阻断。",
  "当前已开启逻辑透深。",
  "建议开启“逻辑透深”检查被隐藏的内耗路径。",
  "查看 {deity} 的演算路径",
  "因果流通链（五行相生）",
  "阈值（归一化场强）:",
  "时空模拟（大运 / 流年）",
  "流年 {liu} · 大运 {dy}",
  "模拟公历参考年",
  "拖动将静默重算物理张量，并把当前大运/流年干支作为 ",
  " 提交后端。",
  "意志回放",
  "盲派 Skill",
  " · 本局已命中信号",
  " · 已武装",
  " · 未启用",
  "当前格局",
  "格局主权",
  " · 集中度 ",
  "平常局",
  "喜忌反转说明（悬浮）",
  "未定：logic_diff 尚无有效 Δabs，无法宣读场强气质。",
  "共鸣：因果偏移极低，逻辑圆融。",
  "修正：意志成功校准场强，天平已稳。",
  "重构：因果发生剧烈位移，宿命被强制剥离。",
  "logic_diff：尚无结构化摘要。",
  "因果定格 · 终审存证",
  "SHA-256（缩写 · 点击拷贝完整指纹）",
  "签发时间",
  "logic_diff 最终摘要",
  "虚实比（Solid / Ghost）",
  "实（Solid）：",
  " · 虚（Ghost）：",
  "平均有效传导：",
  "记录该局干支维轴下因果能量的落地程度（越高越「实」）。",
  "本证书快照未含 solid_ghost_ratio（需排盘后 physics meta）。",
  "生效 Skill ID（规则索引）",
  "本快照未记录盲派 Skill 列表（或非盲派会话）。",
  "因果主权（Causal Sovereignty）",
  "路由策略：",
  "意志贡献度（WILL_INFUSED）：",
  "—（无冲突矩阵锚点）",
  "木",
  "火",
  "土",
  "金",
  "水",
  "熄灭",
  "衰微",
  "中和",
  "强旺",
  "盲派体用对垒仪表盘",
  "体（BODY） [家里/INTERNAL]",
  "用（USE） [家外/EXTERNAL]",
  "做功空腔（Working Chamber）",
  "[出口被封锁：能量内溢风险]",
  " 阻滞点：",
  "解锁建议（Strategic Strike）",
  "时柱出口告警：门被焊死（高压态）",
  "做功工具（午火）受大运（子水）压制，路径断裂。",
  "[能量空转 / 无功可受]",
  "[能量空转 / 微观路径已隐藏]",
  "体",
  "用",
  "冲",
  "：基础能量 ",
  " - 损耗 ",
  " - 最终做功 ",
  "食伤泄秀功能坍缩",
  "逻辑锚点：关联 Skill 的语义反馈",
  "精准",
  "偏移",
  "准",
  "偏",
  "当前为【建禄格】，物理能量处于溢出状态，排水（泄耗）是优先策略。",
  "当前为【月劫格】，争夺态明显，需以食伤泄压并谨慎控风险。",
  "当前为【身强无依】，核能空转，必须建立有效做功出口。",
  "女性语义：官杀常映射事业/伴侣压力轴；用忌建议侧重官杀链路稳定性。",
  "男性语义：财星常映射财富/伴侣压力轴；用忌建议侧重财星链路稳定性。",
  "话语权占比：盲派 {blPct}% | 旺衰 {wPct}%",
  "战略核心看板（Strategic HUD）",
  "性别坐标：",
  "峰值能量（Abs）:",
  "用神（能量出口）",
  "忌神（坍塌风险）",
  "调候（硬修正）",
  "已启用",
  "未决冲突：",
  "用神",
  "忌神",
  "调候",
  "峰值Abs",
  "对比同盘男女路径差异",
] as const;
