// Generated by scripts/v50_export_experience_schemas.py. Do not edit.
// Python Pydantic contracts are the authoritative source.

export type CanvasRole = "guest" | "member" | "practitioner" | "research" | "admin";
export type CanvasStage = "natal" | "luck" | "year";
export type CanvasLayer = "generation_control" | "combination" | "conflict" | "work_path";

export interface AllowedChartFact {
  fact_ref: string;
  fact_type: string;
  display_value: string;
  visual_anchor: string;
  visibility: "participant_private";
  pillar_slot: "year" | "month" | "day" | "hour" | "";
  pillar_label: string;
  stem: string;
  branch: string;
  stem_element: "wood" | "fire" | "earth" | "metal" | "water" | "";
  stem_polarity: "yin" | "yang" | "";
  branch_element: "wood" | "fire" | "earth" | "metal" | "water" | "";
  branch_polarity: "yin" | "yang" | "";
  visible_ten_god: string;
  hidden_stems: Array<HiddenStemFact>;
}

export interface ApprovedClaim {
  claim_ref: string;
  category: string;
  approved_meaning: string;
  spoken_summary: string;
  subtitle_summary: string;
  certainty: "low" | "medium" | "high";
  conditions: Array<string>;
  counter_signals: Array<string>;
  temporal_scope: string;
  evidence_refs: Array<string>;
  visual_anchors: Array<string>;
  permitted_uses: Array<string>;
}

export interface ApprovedReasoningStep {
  step_ref: string;
  premise: string;
  conclusion: string;
  source_refs: Array<string>;
  visual_anchor: string;
}

export interface CanonicalProjectionEnvelope {
  schema_version: "deepbazi.canonical_projection_envelope.v1";
  projection_id: string;
  projection_kind: "onecanvas" | "abu" | "theater" | "xiangfa" | "workspace";
  scene_identity: CanonicalSceneIdentity;
  role_disclosure: CanonicalRoleDisclosure;
  adapter_id: string;
  payload: Record<string, unknown>;
  semantic_refs: Array<string>;
  projection_hash: string;
  creates_mingli_facts: false;
  creates_mingli_claims: false;
  writes_chart: false;
  writes_life_case: false;
}

export interface CanonicalRoleDisclosure {
  policy_version: "canonical-scene-disclosure.v1";
  role: "guest" | "member" | "practitioner" | "research" | "admin";
  disclosure_level: "chart_facts" | "approved_insights" | "professional" | "research";
  visible_fact_refs: Array<string>;
  visible_claim_refs: Array<string>;
  visible_reasoning_step_refs: Array<string>;
  visible_hypothesis_refs: Array<string>;
  visible_temporal_refs: Array<string>;
  visible_relation_assertion_refs: Array<string>;
  visible_path_assertion_refs: Array<string>;
  prohibited_fields: Array<string>;
  prohibited_capabilities: Array<string>;
  disclosure_hash: string;
}

export interface CanonicalSceneIdentity {
  scene_id: string;
  compiler_version: string;
  case_ref: string;
  chart_version_id: string;
  world_id: string;
  life_case_id: string;
  life_case_version: string;
  source_updated_at: string;
  source_hash: string;
}

export interface CanvasChangeGroup {
  change_type: "introduced" | "removed" | "activated" | "reinforced" | "weakened" | "blocked" | "reopened" | "unchanged";
  label: string;
  count: number;
  items: Array<CanvasChangeItem>;
}

export interface CanvasChangeItem {
  target_ref: string;
  object_type: string;
  label: string;
  before_state: string;
  after_state: string;
  reason_refs: Array<string>;
}

export interface CanvasCluster {
  cluster_ref: string;
  label: string;
  node_refs: Array<string>;
  relation_refs: Array<string>;
  trace: CanvasTrace;
}

export interface CanvasContextPack {
  schema_version: "deepbazi.canvas_context_pack.v1";
  context_pack_id: string;
  canvas_spec_id: string;
  diff_spec_id: string;
  role: "guest" | "member" | "practitioner" | "research" | "admin";
  current_stage: "natal" | "luck" | "year";
  selected_object_refs: Array<string>;
  visible_layers: Array<string>;
  committed_path_refs: Array<string>;
  candidate_path_refs: Array<string>;
  blocked_path_refs: Array<string>;
  hypothetical_mutations: Array<CanvasSandboxMutation>;
  diff_reason_refs: Array<string>;
  uncertainty: Array<string>;
  must_not_say: Array<string>;
  disclosed_object_refs: Array<string>;
  content_hash: string;
}

export interface CanvasContextResponse {
  status: "canvas_context_ready";
  context: CanvasContextPack;
  llm_used: false;
  formal_state_writes: false;
}

export interface CanvasDiffSpec {
  schema_version: "deepbazi.canvas_diff_spec.v1";
  diff_id: string;
  from_spec_id: string;
  to_spec_id: string;
  source_action_ref: string;
  added_nodes: Array<CanvasObjectDelta>;
  removed_nodes: Array<CanvasObjectDelta>;
  added_relations: Array<CanvasObjectDelta>;
  removed_relations: Array<CanvasObjectDelta>;
  changed_relations: Array<CanvasObjectDelta>;
  added_clusters: Array<CanvasObjectDelta>;
  removed_clusters: Array<CanvasObjectDelta>;
  introduced_paths: Array<CanvasObjectDelta>;
  removed_paths: Array<CanvasObjectDelta>;
  activated_paths: Array<CanvasObjectDelta>;
  blocked_paths: Array<CanvasObjectDelta>;
  reopened_paths: Array<CanvasObjectDelta>;
  reinforced_paths: Array<CanvasObjectDelta>;
  weakened_paths: Array<CanvasObjectDelta>;
  unchanged_paths: Array<CanvasObjectDelta>;
  changed_epistemic_status: Array<CanvasEpistemicDelta>;
  explanation_refs: Array<string>;
  uncertainty: Array<string>;
  content_hash: string;
}

export interface CanvasEpistemicDelta {
  object_type: "node" | "relation" | "cluster" | "path";
  target_ref: string;
  status_scope: "object" | "state";
  before_status: "fact" | "derived" | "candidate" | "committed" | "blocked" | "hypothetical" | "presentation_only";
  after_status: "fact" | "derived" | "candidate" | "committed" | "blocked" | "hypothetical" | "presentation_only";
  reason_refs: Array<string>;
  source_refs: Array<string>;
}

export interface CanvasEpistemology {
  epistemic_statuses: Array<"fact" | "derived" | "candidate" | "committed" | "blocked" | "hypothetical" | "presentation_only">;
  source_refs: Array<string>;
  commitment_refs: Array<string>;
  uncertainty: Array<string>;
  rejection_or_block_reasons: Array<string>;
  must_not_say: Array<string>;
}

export interface CanvasIdentity {
  canvas_spec_id: string;
  chart_version_id: string;
  temporal_snapshot_id: string;
  life_case_id: string;
  sandbox_session_id: string;
  compiler_version: string;
  compiled_at: string;
  audience_role: "guest" | "member" | "practitioner" | "research" | "admin" | null;
  content_hash: string;
}

export interface CanvasInteractionPolicy {
  allowed_interactions: Array<string>;
  immutable_slots: Array<string>;
  sandbox_mutations: Array<string>;
}

export interface CanvasLayerProjection {
  layer_id: "generation_control" | "combination" | "conflict" | "work_path";
  label: string;
  description: string;
  relation_refs: Array<string>;
  available: boolean;
  count: number;
}

export interface CanvasNode {
  node_ref: string;
  label: string;
  node_type: string;
  semantic_slot_ref: string;
  element: string;
  polarity: string;
  ten_god: string;
  trace: CanvasTrace;
}

export interface CanvasObjectDelta {
  object_type: "node" | "relation" | "cluster" | "path";
  target_ref: string;
  change_type: "introduced" | "removed" | "activated" | "reinforced" | "weakened" | "blocked" | "reopened" | "unchanged";
  before_state: string;
  after_state: string;
  reason_refs: Array<string>;
  source_refs: Array<string>;
}

export interface CanvasPath {
  path_ref: string;
  label: string;
  node_refs: Array<string>;
  relation_refs: Array<string>;
  required_refs: Array<string>;
  semantic_state: "latent" | "active" | "reinforced" | "weakened" | "blocked";
  trace: CanvasTrace;
  state_trace: CanvasTrace;
  change_reason_refs: Array<string>;
}

export interface CanvasPathAvailability {
  status: "available" | "unavailable";
  message: string;
  committed_path_count: number;
  candidate_path_count: number;
  legacy_unresolved_count: number;
}

export interface CanvasPresentation {
  visual_anchors: Array<CanvasVisualAnchor>;
  layers: Array<string>;
  emphasis: Array<string>;
  narration_targets: Array<string>;
}

export interface CanvasRelation {
  relation_ref: string;
  from_node_ref: string;
  to_node_ref: string;
  participant_node_refs: Array<string>;
  relation_type: string;
  label: string;
  semantic_state: "latent" | "active" | "reinforced" | "weakened" | "blocked";
  trace: CanvasTrace;
  state_trace: CanvasTrace;
  change_reason_refs: Array<string>;
}

export interface CanvasRendererPolicy {
  read_only: true;
  allowed_interactions: Array<string>;
  forbidden_interactions: Array<string>;
}

export interface CanvasSandboxMutation {
  mutation_id: string;
  action_type: "set_luck" | "set_year" | "replace_year" | "clear_year";
  field_path: "temporal.luck" | "temporal.year";
  before_layer_id: string;
  after_layer_id: string;
  base_snapshot_id: string;
  source_mode: "derived" | "hypothetical";
  source_refs: Array<string>;
}

export interface CanvasSemanticSlot {
  slot_ref: string;
  slot_type: "natal_year" | "natal_month" | "natal_day" | "natal_hour" | "luck" | "year";
  label: string;
  stem: string;
  branch: string;
  hidden_stems: Array<string>;
  immutable: boolean;
  trace: CanvasTrace;
}

export interface CanvasStageProjection {
  stage: "natal" | "luck" | "year";
  title: string;
  summary: string;
  spec: MingliCanvasSpec;
  diff: CanvasDiffSpec | null;
  context: CanvasContextPack;
  layers: Array<CanvasLayerProjection>;
  default_layer_id: "generation_control" | "combination" | "conflict" | "work_path";
  change_groups: Array<CanvasChangeGroup>;
}

export interface CanvasTrace {
  source_mode: "canonical" | "committed" | "derived" | "hypothetical" | "presentation";
  epistemic_status: "fact" | "derived" | "candidate" | "committed" | "blocked" | "hypothetical" | "presentation_only";
  source_refs: Array<string>;
  commitment_refs: Array<string>;
  uncertainty: Array<string>;
  rejection_or_block_reasons: Array<string>;
  disclosure: "public" | "member" | "practitioner" | "research";
}

export interface CanvasVisualAnchor {
  anchor_ref: string;
  object_ref: string;
  group: string;
  trace: CanvasTrace;
}

export interface CompetingHypothesis {
  hypothesis_ref: string;
  approved_meaning: string;
  supporting_refs: Array<string>;
  unresolved_reason: string;
}

export interface EnvelopeFallback {
  mode: "chart_facts_only" | "observer";
  allowed_content: Array<string>;
}

export interface EnvelopeSource {
  chart_version: string;
  life_case_version: string | null;
  case_ref: string | null;
  temporal_snapshot_version: string | null;
  generated_at: string;
  expires_at: string;
  source_hash: string;
}

export interface EnvelopeUncertainty {
  level: "low" | "medium" | "high";
  reasons: Array<string>;
}

export interface ExperienceCaseSummary {
  case_id: string;
  profile_id: string | null;
  display_name: string;
  case_version: string;
  status: string;
  baseline_available: boolean;
  experience_url: string;
}

export interface ExperienceCasesResponse {
  status: "experience_cases_ready";
  cases: Array<ExperienceCaseSummary>;
  cognition_source: "LifeCase";
  legacy_report_used: false;
}

export interface HiddenStemFact {
  stem: string;
  ten_god: string;
  element: "wood" | "fire" | "earth" | "metal" | "water" | "";
  polarity: "yin" | "yang" | "";
}

export interface MingliCanvasSpec {
  schema_version: "deepbazi.mingli_canvas_spec.v1";
  identity: CanvasIdentity;
  stage: "natal" | "luck" | "year";
  semantic_slots: Array<CanvasSemanticSlot>;
  nodes: Array<CanvasNode>;
  relations: Array<CanvasRelation>;
  clusters: Array<CanvasCluster>;
  paths: Array<CanvasPath>;
  epistemology: CanvasEpistemology;
  interaction: CanvasInteractionPolicy;
  presentation: CanvasPresentation;
}

export interface MingliExperienceEnvelope {
  envelope_id: string;
  schema_version: "deepbazi.mingli_experience_envelope.v1";
  mode: "personal_ready" | "chart_facts_only" | "observer";
  participant_scope: ParticipantScope;
  source: EnvelopeSource;
  topic_scope: TopicScope;
  allowed_chart_facts: Array<AllowedChartFact>;
  approved_claims: Array<ApprovedClaim>;
  approved_reasoning_steps: Array<ApprovedReasoningStep>;
  competing_hypotheses: Array<CompetingHypothesis>;
  uncertainty: EnvelopeUncertainty;
  must_not_say: Array<string>;
  fallback: EnvelopeFallback;
}

export interface MingliVisualCue {
  at_ms: number;
  action: "reveal" | "focus" | "pulse" | "flow" | "split" | "dim" | "sever" | "ghost" | "restore" | "compare";
  target: string;
}

export interface NarrationManifest {
  schema_version: "deepbazi.narration_manifest.v1";
  manifest_id: string;
  manifest_hash: string;
  scope: "participant_private";
  case_id: string;
  chart_version: string;
  life_case_version: string;
  formal_insight_id: string;
  narration_script_version: string;
  mode: "standard";
  language: string;
  voice_id: string;
  voice_version: string;
  segments: Array<NarrationSegment>;
  compiled_at: string;
  autoplay: false;
  page_available_without_audio: true;
}

export interface NarrationManifestResponse {
  status: "narration_manifest_ready";
  manifest: NarrationManifest;
  speech_assets: Record<string, NarrationStatus>;
  tts_called: false;
  llm_used: false;
  reasoner_used: false;
}

export interface NarrationSegment {
  segment_id: string;
  order: number;
  kind: "thesis" | "work_path" | "condition" | "uncertainty";
  title: string;
  text: string;
  source_claim_refs: Array<string>;
  source_refs: Array<string>;
  visual_anchor_ids: Array<string>;
  visual_cues: Array<MingliVisualCue>;
  estimated_duration_seconds: number;
}

export interface NarrationStatus {
  status: "ready" | "missing";
  speech_asset_id: string;
  audio_url: string;
  audio_format: string;
}

export interface ParticipantScope {
  participant_ref: string;
  privacy_level: "anonymous" | "account" | "client_case";
  disclosure_level: "observer" | "chart_facts" | "approved_insights";
  language: string;
}

export interface ReadOnlyCanvasSource {
  chart_version_id: string;
  life_case_id: string;
  life_case_version: string;
  cognitive_record_id: string;
  luck_pillar: string;
  luck_year_range: Array<number>;
  annual_pillar: string;
  analysis_year: number | null;
  timing_validation_status: string;
  timing_publicly_supported: boolean;
}

export interface ReadOnlySixPillarCanvas {
  schema_version: "deepbazi.read_only_six_pillar_canvas.v1";
  status: "read_only_canvas_ready";
  case_id: string;
  role: "guest" | "member" | "practitioner" | "research" | "admin";
  stage_order: Array<"natal" | "luck" | "year">;
  default_stage: "natal" | "luck" | "year";
  source: ReadOnlyCanvasSource;
  canonical_scene: CanonicalSceneIdentity;
  projection_envelope: CanonicalProjectionEnvelope;
  path_availability: CanvasPathAvailability;
  stages: Record<string, CanvasStageProjection>;
  renderer_policy: CanvasRendererPolicy;
  boundaries: Array<string>;
  llm_used: false;
  formal_state_writes: false;
  sandbox_mutations: false;
}

export interface SpeechAsset {
  schema_version: "deepbazi.speech_asset.v1";
  speech_asset_id: string;
  scope: "participant_private";
  source: SpeechAssetSource;
  voice: SpeechAssetVoice;
  media: SpeechAssetMedia;
  status: "ready";
  generated_at: string;
  generation_seconds: number | null;
}

export interface SpeechAssetMedia {
  audio_url: string;
  audio_hash: string;
  duration_ms: number;
  sample_rate: number;
  format: "wav";
  subtitle_track: Array<SpeechSubtitleItem>;
  size_bytes: number;
  playback_variants: Array<SpeechAssetMediaVariant>;
}

export interface SpeechAssetMediaVariant {
  format: "opus";
  mime_type: "audio/ogg; codecs=opus";
  audio_url: string;
  audio_hash: string;
  size_bytes: number;
  codec_profile_version: string;
}

export interface SpeechAssetResponse {
  status: "speech_asset_ready";
  speech_asset: SpeechAsset;
  cache_hit: boolean;
  tts_called: boolean;
  llm_used: false;
  reasoner_used: false;
}

export interface SpeechAssetSource {
  case_id: string;
  chart_version: string;
  life_case_version: string;
  formal_insight_id: string;
  segment_id: string;
  claim_refs: Array<string>;
  source_refs: Array<string>;
  narration_script_version: string;
  source_text_hash: string;
}

export interface SpeechAssetVoice {
  voice_id: string;
  voice_version: string;
  tts_model_version: string;
  language: string;
  speaking_style: string;
  speed: number;
  pronunciation_lexicon_version: string;
}

export interface SpeechSubtitleItem {
  start_ms: number;
  end_ms: number;
  text: string;
}

export interface TopicScope {
  topic_id: string;
  topic_version: string;
  permitted_capabilities: Array<string>;
  prohibited_capabilities: Array<string>;
}
